#+LATEX_CLASS: book
#+LATEX_CLASS_OPTIONS:[11pt,oneside]
#+LATEX_HEADER: \usepackage{book}


#+TITLE: 新阶级——对共产主义制度的分析
#+AUTHOR: 吉拉斯（陈逸 译）
#+CREATOR: 编者:万泽(德山书生)
#+DESCRIPTION: 制作者邮箱：a358003542@gmail.com



* 前言
** 作者简介
作者：吉拉斯（又称作密洛凡•德热拉斯）：生于黑山科拉欣附近的一个农民家庭，早年曾在贝尔格莱德大学攻读哲学和法律。他曾担任过南共联盟中央执委、中央书记、国民议会议长、副总统。他公开主张把南共联盟变成一个议会民主政党，实行多党制和西方式的民主。1954年，南共联盟中央决定将其开除出中央委员会，解除其党内外的一切职务，给予最后警告处分。之后，又把他开除出南共联盟，并逮捕判刑。1961年，当局提前释放了吉拉斯。1995年去世。【来自维基百科】
 
** 序言
书中所叙述的一切本是可以用其他方式表达的；这一切可以写成一本当代革命史，一本专提意见的文献，或者一个革命家的自供。上述内容已经在本书中略为提到。不过，纵或这里的有关历史、意见和回忆的综合并不完全，总能反映出我是如何努力以尽可能简短的文字对当代共产主义作尽可能周全的描绘。有些特殊的或涉及技术方面的问题可能被忽略了，但我相信，这反使主要部分更简单，更完全。
 
在本书中，我力求不涉及我个人的问题。但我的环境是凶险的，最好也不过是凶吉不可知，因此，我不得不在匆忙中草率地表达我个人的观察和经验；我希望有一天能有机会对我个人的情况作更细密的检查，这将可能补充，甚或改变我的一部分结论。

我不能描述我们当代世界这个惨痛历程中冲突的所有方面。我也不能假装知道共产主义世界以外的世界，那是我未曾生活过的世界，这可以说是我的幸运，也可以说是我的不幸。所以，当我说及我自己这个世界以外的世界时，我只是为了要把我自己的世界放在一个适当的位置上加以比较，使它的真相更清楚。

书中所写的一切几乎都在别些地方以不同的方式表达过，不过，这里或许会有一种新味道，新色彩，新心境和一些新思想。事实上，仅仅这一些东西就足够珍贵了。 _每个人的经验都是独特的，值得让其他的人知道_ 。

读者请不要想在本书中找到什么社会哲学或其他的哲学，即使是在我所作的概括性的陈述中也找不到。我的目的只是陈示共产主义世界的真相，尽管我发现有时不得不加以概括，但是，我并无意通过概括性的理论化陈述去解释共产主义世界。

在我看来，本书中的材料以置身局外的观察方式来提供，是最适当的方法。本来，我的前提和结论都可由统计数字，权威言论和重要史实的引述来巩固和证明。不过，为了使本书简明扼要，我宁愿尽可能少用统计数字和引证，而通过演绎和归纳的论证来表明我的观察结果。

我认为我的方法对于陈述我个人的经验以及对于我的工作和思维的方法都是适当的。

我成年以后，走过了一个共产党人所能走的整个路程：从权力阶梯的最低级爬到最高级，从地方性组织走进全国性组织以至国际组织，从真正共产党的形成和组织革命直到所谓社会主义社会的建立。在这段时期中，没有人曾强迫我拥护共产主义，也没有人强迫我反对共产主义。我是完全根据我个人的信念非常自由地决定一切的。尽管我是从迷梦中觉醒了，不过，我并不属于那些突然觉醒的一群。我是从本书所陈述的逐步构成的事实真相和结论中逐渐地、自觉地醒过来的。当我对于当代共产主义现实愈来越疏远时，我就愈来愈接近民主社会主义的观念。尽管本书的首要目的不在追溯我个人思想的演变，不过这一演变也反映出来了。

我认为把共产主义当作一种观念来批评是多余的，因为自有人类社会以来，人间就存在了各式各样的平等和博爱的观念（而当代共产主义是标榜这些观念的），这些观念是争取进步和自由的战士们一贯为之奋斗的主要目标。批评这些基本的观念不但是错误的，而且是无效和愚蠢的。追求平等和博爱的斗争本是人类社会的一部分。

尽管对共产主义理论的详细批评是需要的和有用的，但我并没把重点放在这上面。我把全部心神集中在对当代共产主义现实的描绘上，只有在必要时才涉及理论。

要在这部如此简短的著作中把我个人全部的观察和体验都写出来是不可能的。我只能把最紧要的部分写出来，在必要时还得用概括性的陈述来表达。

生活在共产主义世界以外的人可能觉得书中所述一切都很陌生；但在生活于共产主义世界中的人看来，那是再寻常不过的事：我并不想在对共产主义世界现实及其观念的描述这件事上求得特殊的功劳和荣誉。书中所描绘的现象和观念，仅仅是我所生活的世界中的真相和观念。我是那个世界的产儿。我曾对那个世界有所贡献。而现在我是那个世界的批评者之一。

这种不一致只限于表面。过去我曾为一个较好的世界而奋斗，而现在我仍在为一个较好的世界而奋斗。我的奋斗并不一定能产生它所希望的结果。然而，我个人行动的一致性却存在于这个长期不断奋斗的过程中。


#+LaTeX: \mainmatter


* 起源
** 一
虽然在西欧近代工业发展以前，现代共产主义还处于潜伏未动状态，但推溯其根源，却由来已久。共产主义的两个基本观念为“物质的第一性”和“变化的实在性”，这两个观念借自现代共产主义萌芽前不久的思想家们。但随着共产主义的日渐得势，这两个基本观念却反而愈来愈不占重要地位。这是可以了解的，因为共产主义已经得势，现在要想按照它自己的观念来改造世界，而且渐渐不想改变它自己了。

辩证法与唯物论，即世界的演变不以人们的意志为转移，是古典的马克思共产主义的基础。然而这些基本观念，却并非创自共产主义理论家，如马克思、思格斯等。他们不过利用这些观念编织成为一个整体，于是无意中就成了新世界观的基础。

“物质的第一性”这一观念借自十八世纪的法国唯物论者。早期的思想家，包括古希腊的徳谟克利特在内，曾以不同的方式表达这一观念。至于由矛盾对立面的斗争而引起的“变化的实在性”这一观念，即所谓辩证观，则系由德国哲学家黑格尔而来，古希腊哲学家赫拉克利特也曾以不同的方式表示过这种观念。

马克思思想与在它以前的同类理论家之间的不同，我不想在此详加论述。我在这里必须指出的是，在黑格尔提出“变化的实在性”时，他仍然保留一个不变的最高规律，即“绝对观念”。分析到最后，如黑格尔所示，在人类意志之外，仍有些不变的规律在主宰自然、社会以及人类本身。

马克思，尤其是恩格斯，尽管重视“变化的实在性”，但仍然认为客观或物质世界的规律是不变的，而且与人类无关【量子力学的存在实际上已经证明马克思哪一套世界观是错误的，可见马克思也不过是老旧时代的哲学罢了，其根本跟不上科学探索的步伐。】。马克思断定他能发现主宰生活和社会的基本规律，正如达尔文发现主宰生物的规律一样。无论如何，马克思确曾阐明一些社会规律，尤其是关于这些规律如何在工业资本主义初期发生作用的问题。

过一事实纵然确实无误，我们也不能只凭这一点就认为现代共产主义者所扬言的马克思发现了所有的社会规律之说是正确的【所有？这些人疯了！】。并且，更不能像以法国的拉马克和英国的进尔文的发现为根据来繁殖家畜那样，认为根据他们的意图来改造社会的办法是正确的。人类社会到底与动物或非生物不能相提并论。人类社会是由不断作有意识活动的个人与团体合成的，它是一直在生长与变化着的【最重要的人类既是社会的观测者也是社会的参与者，这就意味着量子化学哪一套测不准原理对于人类社会也是效应极大的。】。

_在当代共产主义的自吹自擂中是含有专制主义种子的_ ，当代的共产主义者虽未把共产主义视为唯一而绝对的科学，但至少被认为是基于辩证唯物论的最高科学。这种自负的根源，我们可在马克思的思想中找到，虽然马克思自己并未料到【恐怕马克思其人也是骄傲自大的】。

诚然，当代的共产主义并不否定客观或不变的规律的存在。但一经得势，它对于人类社会及个人的行动，却完全不是这回事，它所用以建立权力的方法，与其理论所指示者不同。

共产主义者从只有他们知道主宰社会的规律的大前提开始，推得一个过于简单而不科学的结论，即这一所谓的知识使他们有权力和专权来改变社会并管制其活动。这就是共产主义制度的主要错误。

黑格尔曾说普鲁士的君主专制是他的“绝对”观念的化身。同样，共产党人则以为他们代表了客观的社会要求。但共产党人与黑格尔却另有不同之处，这也正是共产党人与君主专制的不同。专制君主自视之高并不及共产党人，其自视之绝对也不如共产党人【可见马克思其人哲学不出黑格尔，但以另外一种更加丑陋的形态。】。


** 二
黑格尔大概曾为从他的发现所可能得出的结论而感到不安。举例说，如果一切事物都是在不断地变化着的，那么他自己的思想以及他所要求保存的社会又将怎样呢？因为他是一个由皇室任命的教授，自然不敢公开主张应该根据他的哲学来改造社会了。

马克思与黑格尔的情形不同。在年青的时候，他曾积极参加过1848年的革命。他从黑格尔的思想所引出的结论走向极端。整个欧洲为了到达新的、更高的阶段，不是在作流血的阶级斗争吗？根据马克思的解释，这不但表示黑格尔理论的正确，并且因为科学已迅速发现客观的规律，包括可实施于社会的规律在内，所以哲学的体系就失去其意义，无所用之了。

当时在科学上，哲学家康德的实证主义，曾作为研究方法而取得优势，英国的政治经济学派，如斯密、李嘉图等，也正大行其道，而在自然科学方面，划时代的规律日有发现；近代工业正依据科学技术开辟其出路。这时候，资本主义年青时期的伤痕，一方面显示其本身的苦难；另一方面也是无产阶级斗争的开始。显然，这是科学统治的开始，甚至支配到社会，同时，这也是要求消灭资本主义所有权观念的开始，因为，它已被视为人类幸福与自由的最后阻碍【所有权是人类社会进化出来的最合理的游戏规则，破坏所有权就会让人们没有积累财富的观念，人类这个物种之所以能够越来越强大正在于能够为了明天积累财富。】。

得出一个伟大结论的时机已经成熟。马克思的勇气和知识都足以表达出这个结论，但是他却没有可以凭依的社会力量。

马克思是一个科学家和思想家【一个骄傲自大的犹太人，二流的小报编辑，三流的经济学家，不入流的科学家。】。就科学家而言，他确有重要的发现，尤其是对于社会学。就思想家而言，他使现代史上最初发生于欧洲、现在传布于亚洲的最巨大和最重要的政治运动有了意识形态的基础。

但是，正由于马克思是一个科学家、经济学家和社会学家，所以他并没有想到建造一个包含一切的哲学或意识形态的体系。有一次，他说：“有一件事是肯定的，即我不是一个马克思主义者。”他的伟大的科学天才，使他比前辈的社会学家如英国的欧文和法国的傅立叶要优越得多。而且因他并不主张有包罗万象的意识形态或自己的哲学体系，所以使他显得比他的后继者优越。这些后继人物大多都是理论家，科学家的成分极少，如普列汉诺夫、拉布留拉(Labriola)、列宁、考茨基和斯大林。他们主要的愿望便是想根据马克思的观念建立一种体系，尤其是那些缺乏哲学素养而更没有哲学的天才的人更作如此想法。后来，这些马克思的后继者便有以马克思的学说作为固定而包含一切的世界观的趋势，而且以为对马克思的全部工作实际上已经是完整了。 _科学逐渐让位于宣传，结果则宣传逐渐以科学的姿态出现。_

在马克思的时代，马克思认为不需要有什么哲学。他的最亲密的朋友恩格斯曾说，由于科学的发展，哲学已经死亡。马克思的论文并不都是具有独创性。所谓科学的哲学已成了当时的一般风尚，在康德实证主义与费尔巴哈的唯物论出现以后，尤其如此。

所以对于马克思之不需要有什么哲学并且不认为有建立一种哲学的可能，我们是不难理解的。令人难以理解的倒是，为什么马克思的后继者们却要把他的思想造成无所不包的体系，成为一种独特的新哲学。他们虽然不承认有任何哲学的需要，但实际上他们造出自己的 *教条* ，以此为“最科学的”或“唯一科学的”体系。在举世热心于科学，并因科学而使日常生活和工业发生巨大变化的时期，他们不得不是唯物论者，并自以为是“唯一”科学观点和科学方法的“唯一”代表，在他们代表了一个社会阶层之后更是如此，但事实上这一社会阶层是与当代一切被接受的思想相冲突的【不得不披着科学皮的老旧分子】。

马克思的思想是受到当时的科学气氛，他个人对科学的倾向，以及他要使工人运动多少具有一个科学基础的革命愿望的影响的。马克思的门徒所受到的是另一种环境和另一种动机的影响，于是马克思的意见便变成了教条。

倘若欧洲工人的政治运动不需要有完整的新的意识形态，那么，尽管马克思在经济学和社会学两方面的研究都具有极高的科学和学术地位，自命为马克思主义的哲学，即辩证唯物论，就将被遗忘，就将被当作不是特别深刻而有创造性的学说而被舍弃。

马克思哲学的力量，不在于他的科学要素，而在于它与群众运动的联系，尤其是它的着重于社会变化的客观性。马克思学说一再地说，现存世界之所以会发生变化，只是因为它不得不变化，因为它本身含有与它自己相矛盾和使它本身毁灭的种子；而且工人阶级需要这种变化，也有力量影响其发生。由于这个哲学的影响不可避免地扩大了，于是在欧洲工人运动中就产生了一种错觉，以为这个哲学是万能的，至少在方法上如此。在并无同样情形存在的国家中，如英国和美国，其工人阶级和工人运动虽然颇有势力，但这一哲学的影响与重要性，是微不足道的。

作为一种科学来说，马克思的哲学并不重要，因为它主要是根据黑格尔的哲学和唯物思想【从来就没有所谓的马克思主义哲学，有的只是一种大杂烩，这种大杂烩披着科学的皮，实际就是个人随意的臆想和专断的满口胡诌。其和希特勒的《我的奋斗》并无本质不同。如果说这种思想有了意义，不过是因为说这种思想的人手上有枪。换句话说，他们就是在现代社会科学运动之下腐朽老旧势力的最后翻滚。】。但作为新的、被压迫的阶级的思想，尤其是作为政治运动的思想而论，它有划时代的作用，最初在欧洲，以后在俄国和亚洲，它提供了一个新的政治运动和社会制度的基础。

** 三
马克思认为，通过过两个基本阶级，即资产阶级和无产阶级的革命斗争，无产阶级可以取资本主义社会而代之。他之所以认为有此可能，显然是因为在当时的资本主义制度之下，贫富的悬殊日甚，形成社会上相互对立的两极，而这个社会又常常发生周期性的经济危机。

分析到最后，可见马克思学说的产生是由于工业革命，或工业无产阶级要求改善其生活的斗争。伴同工业革命而来的群众的极端贫苦与凄惨对于马克思的影响极大，这不是偶然的。他最重要的著作《资本论》就有关于这方面的许多重要而动人的记述。作为十九世纪资本主义特征的连续发生的经济危机，以及当时的贫困现象与人口的迅速增加，显然使马克思相信只有革命是唯一的解决方法。不过他并不认为所有各国必将发生革命，尤其是在民主制度已成为社会生活的传统的那些国家。他在一次谈话中曾列举荷兰、英国和美国作为例证。但就整个马克思的思想来说，却使人觉得他的基本信念乃是认为革命是不可避免的。他相信革命，宣传革命；他是一个革命家【马克思作为一个落魄老旧的哲学家，流浪的犹太人，主张造反和革命不出人意外。】。

马克思的革命思想本是有条件的，并不是适用于全世界的，但到了列宁手中，却被说成绝对而普遍的原则。在《共产主义运动中的“左派”幼稚病》（这可能是他最独断的著作）中，他进一步发展了这些原则，而且与马克思所认为的关于在有些国家可以避免革命的意见显然不同。列宁说，英国已不能被认为是一个可以避免革命的国家，因为在第一次大战时，英国已成为一个军国主义的国家，因此英国的工人阶级除了革命以外，已无可选择【列宁作为德国安排在俄罗斯的间谍意图破坏英国】。列宁的错误，不但是在于他不知道“英国的军国主义”只是一种暂时的、战时的发展现象，并且他更没有预见到英国及其他西方国家民主政治的发展和经济的进步。他也不了解英国工会运动的性质。列宁过分重视他自己的或马克思主义的、宿命论的科学思想，而对于比较高度工业化国家中工人阶级的潜能及其客观的社会作用却极少注意。列宁虽然表面上否认，但实际上他却自以为他的理论和俄国革命的经验是可以普遍适用于全世界的。

根据马克思的假定及其关于这一问题的结论，革命当首先发生于高度工业化的资本主义国家。马克思认为，在革命成功后，即在社会主义的新社会，可以获得一种新的自由，这种自由的水平比既有的所谓自由资本主义社会中的自由更高。这是容易理解的。马克思虽排除各种形式的资本主义，但是他却是自由资本主义时代的产儿。

马克思认为，资本主义不但将为更高的经济和社会形式，即社会主义所代替，并且还要为人类自由的更高形式所取代，社会民主党人发展了这一论点，他们有理由自认为是马克思的继承者。在这方面，他们与那些把马克思的思想当作自己思想的源泉，即认为只有用革命手段才能取代资本主义的共产党人有同样的权利。但是这两派马克思的信徒，即社会民主党与共产党，在援引马克思理论作为他们的思想基础时，却只有一部分是对的。因为他们引用马克思的理论的目的，就是为了维护他们的实际行动，而这种行动却起源于已经改变了的不同的社会。并且他们虽然都是依据马克思的理论，但社会民主党的运动与共产党的运动却向不同的方向发展【不是科学的调查思辨，而是引经据典，可见这两派都不过是老旧独断哲学的翻滚罢了。】。

但在政治与经济的进步难以展开以及工人阶级社会力量微弱的国家中，就逐渐有从马克思学说中推出一种体系和教条的需要。而且，在经济力量与社会关系还没有够得上推行工业革命的国家，如在俄国以及后来在中国，对马克思的革命理论的采用和加以教条化就更为迅速而完全。那里的工人运动，其重点尤在 _革命_ 。在这些国家中，马克思主义日趋强盛，到了革命的党派获得胜利以后，便成为压倒一切的理论。

在像德国这一类国家，那里政治经济的进步程度使革命成为不必要，则马克思学说的民主与改良部分就比革命部分更占优势。工人运动也在反教条的意识形态与政治趋向的影响下着重于 _改良_ 。

在前面一种情况下，工人运动与马克思的关系加强了，至少在表面上是如此。在后面一种情况下，工人运动与马克思的关系则减弱了。

社会的变化与理论的发展使欧洲社会主义运动造成激烈的派别对立。大体说来，政治和经济条件的变化是与社会主义理论家的观点的变化相一致的，因为他们各用其党派的见解来相对地解释实际情况，也就是说，他们的见解常常是不完全而有偏见的。

例如俄国的列宁和德国的伯恩施坦就是两个极端，而社会和经济方面的各种不同的变化，以及工人运动的各种不同的“实在性”，都通过这两个极端反映了出来。

原来的马克思主义差不多已不复存在。在西方，马克思主义已告死亡，或正在死亡之中；在东方，则由于共产主义统治的建立，马克思的辩证观与唯物论只剩了形式主卫与教条主义的渣滓，并且不过是用以巩固权力，维护暴虐并侵害人类的良知。尽管在东方各国中，马克思主义实际上已被舍弃，但它被当作严格的教条使用并且日益有力。在东方，它已不止是一种思想，而是一个新的政府，新的经济制度和新的社会制度了。

尽管马克思使其弟子们有这种发展的动力，但他原没有想到会有这样的发展，并且也并不希望有这样的发展。 _历史已经背弃了这位大师，也背弃了其他那些企图解释历史规律的人们_ 。

然而自马克思以来，社会发展的性质是怎样的呢？

在十九世纪七十年代，在工业革命已经开始的国家，如英国、德国和美国，公司组织及垄断企业已经开始成立。到了二十世纪初，这一发展臻于极盛。霍布孙(Hobson)、希法亭(Hilferding)等曾对这一发展作过科学的分析。列宁根据他们的著作作了政治的分析，写成他的《帝国主义是资本主义的最高阶段》，但 /事实/ 证明，其所述大多都不正确。

马克思关于工人阶级日趋贫困的理论，本是根据上面这些国家的社会现象所作的推论，但日后并未实现。不过正如塞东－华生(Hugh Seton-Watson)在他所著《从列宁到马林科夫》[fn::弗雷德里克•阿•普雷格出版公司，纽约1953年版。] 一书中所说，这种贫困现象，在东欧农业国家却大体无误。因此，马克思在西方的地位至多不过是一个历史学家和学者，而在东欧却等于一个新时代的先知。他的学说具有动人的力量， _仿佛一种新的宗教_ 。

根据现今法国作家莫洛亚(André Maurois)所著《英国史》的南斯拉夫版所述，为马克思和思格斯的学说提供的西欧的情形是这样的：

#+BEGIN_QUOTE
“当1844年恩格斯访问曼彻斯特的时候，他看到有三十五万工人聚居住潮湿污秽而摇摇欲坠的房屋中。他们呼吸着一种类似水与煤相混合的空气。在矿场中，他看到半裸的妇女，她们的生活有如最下等的拖车子的牲畜。儿童们整天在黑暗的隧道中过活，他们被雇担任开关原始式的通风设备，以及其他困难的工作。在花边工场中，剥削甚至及于四岁的儿童，其工作实际上等于并无报酬。”
#+END_QUOTE

恩格斯还活到能看见与此完全不同的英国的情形，但是，更重要的是他在俄国、巴尔干以及亚洲和非洲还见到比这更为可怕、更为贫困无望的现象。

技术的改进使西方国家无论在哪一方面都发生了广大而具体的变化。它促使垄断组织的形成，而且使世界被划分成先进国家和垄断组织的势力范围。这也就是第一次世界大战及十月革命的由来。

因为这些先进国家的生产迅速增加，并且取得了殖民地的资源和市场，所以工人阶级的物质地位大为不同。要求进行改革、改善物质生活的斗争，以及要求政府采用议会形式，成为比革命理论更实际有用的东西。所以在这些地方，革命就被视为无意义而不切实际了。

在尚未工业化的国家，尤其是在俄国，其情形完全不同。他们感到陷于一个两难的境地；倘若不起来实行工业化，那就无法再继续在历史舞台上积极活动，而成为先进国家与垄断组织的俘虏，结果趋于灭亡。但是本国的资本，与代表此资本的阶级及政党，又力量薄弱，不足以解决迅速工业化的问题。因此，在这些国家中，革命就成了必要，成了国家的重大需要。而只有一个阶级，即无产阶级，或代表这个阶级的革命政党，可以担任这个任务【如果俄罗斯不发生革命，还是继续温和的沙皇的改良之路会如何呢？革命的意义不过是杀掉一批人再换掉另外一批人，反而破坏了整个社会的游戏规则，这是需要几个世纪才能培养起来的！可见如果当初采用一种温和的非暴力改良道路，也许俄罗斯和今日的中国路将走的更加顺畅，至于那个所谓的垄断组织，其实就是宝洁公司的香皂质量更好更便宜罢了，不管是新起来一波人成了新的权贵还是老旧的权贵还是本土资本家等等等等，他们所做的一切不过是本土保护和让你们买更贵的质量更差的香皂，大概就是这个道理。其他没有任何改变，要发展，要在国际经济市场上立足，来时要靠大家多学习多发展技术，然后找到自己的擅长，自然就能赚国际货币了。】。

其原因是，这里有一个不变的规律，即每一人类社会及其所属的每一个人都想要增加生产，使之完善，但在他们努力的时候，却不免与其他团体及个人发生冲突，于是为了生存就彼此发生斗争。在生产日趋增加与扩张的时候，常遇到自然的和社会的阻碍，如个人的、政治的、法律的以及国际的习惯与关系等。由于必须克服这些阻碍，所以，社会——当时代表社会生产力量的某群人——必须消除、改变或毁灭存在于其内外的各种阻碍。阶级、政党、政治制度及政治观点都反映着运动和停滞这种连续不断的状态【这段话证明作者思想并未彻底蜕变，张口就是代表社会生产的某群人？下面又会说生产要依靠国家。说的好像社会生产只是某一小群人的事，然后说得好像生产经济活动必须要国家干预，作者经济学不太懂。】。

没有一个团体或国家故意让生产落后到使它足以威胁到生存。因为落后的意义便是灭亡。人决没有自甘灭亡的，他们要不惜一切牺牲以克服那些阻碍其经济生产与生存的困难。

环境、物质条件及知识的水平可以决定使生产发展和扩大的方法、力量和手段，从而也是左右其社会后果的决定性因素。无论如何，发展和扩大生产的需要，不管他们标榜何种思想旗号或社会力量，并不只凭个人，因为人们需要生存，社会和国家为了达到他们所求取的目的，就有必要寻求当时认为最适合的领袖与思想【这段话作者也是漏洞百出，其对于自由市场机制不太懂，所以一谈到提高生产就要国家政府来管。】。

革命的马克思主义就在垄断资本主义的时代，从工业发达的西方移植到工业落后的东方，如俄国与中国。这也就是社会主义运动正在东方和西方发展的时候。这一阶段的社会主义运动首先是统一和集中于第二国际，最后乃分裂为改良的社会民主党与革命的共产党，后来发生了俄国的革命，组织了第三国际【共产国际这个组织一直在分裂，正反映了它的从失败走向失败。】。

在那些没有其他方法可以实现工业化的国家，其所以发生共产主义革命，是有特殊的民族理由的。原来，早在马克思主义者出现于十九世纪末叶以前，革命运动在半封建的饿国已有半个世纪以上的历史。而且，又有国际的、经济的、政治的迫切而特殊的具体原因要求革命，基本原因——对工业化的迫切需要——在发生革命的所有各国，如俄国、中国和南斯拉夫等都是普遍存在的【要提高生产，先革命，什么逻辑？抢来的钱果然来的最快，这就是提高生产了吧。】。

在马克思以后，欧洲大多数的社会主义运动，不但是唯物的和马克思主义的，而且在思想上，具有相当程度的排它性，这可以说在历史上是必然的。反对它们的有旧社会一切势力的联合，如教会、学校、私有财产、政府，更重要的还有欧洲各国在面对欧洲大陆上不断发生的战争威胁下早就发展出来的巨大的权力机构【马克思主义就好像恐怖主义一样人人喊打】。

无论是谁，要想把世界作根本的改变，首先就必须对世界从根本上“正确无误”地加以解说【说起来更真的一样，还最世界完全正确无误的解读，哈哈，你是神吗？】。任何新的运动在思想上必然是排它的【新的思想必须排他，什么逻辑？】，尤其是在只有革命才能取得胜利的情况下。如果运动一旦成功，那么这种成功的事实更使这种思想和信念增强。虽然“冒险的”议会手段与罢工的成功，使改良主义的趋向在德国及其他国家的社会民主党中的势力增强了，但俄国的工人非经流血的清算，就不能使其地位有丝毫改善，所以他们无可奈何，只好进行武力革命，以免于绝望与饿死【其实就是类似封建社会的农民起来造反，非要扯什么理论和主义。】。

但东欧的其他国家如波兰、捷克斯洛伐克、匈牙利、罗马尼亚及保加利亚，它们并没有根据这一规则行事，至少是波、捷、匈三国。它们并未经过革命，共产主义制度乃是苏联军队强加于它们的【实际上是最粗暴的内政干涉】。它们甚至也并未迫切要求进行工业改革，至少是并未要求用共产党的方法，因为有些国家已经改革了。总之，在这些国家中，革命乃由外国刺刀与武力机关从外面及上面加在它们身上的。除了工业最为发达的捷克斯洛伐克以外，在其余几国中，共产主义运动的势力是微弱的。直到苏联在大战时期进行直接干涉及1948年2月发生的政变以前，捷克斯洛伐克的共产主义运动及类似左翼社会主义运动和议会社会主义运动。因为共产党在这些国家中势力微弱，所以共产主义的实质与形式乃不得不与苏联相同。苏联把它的制度加在它们身上，当地的共产党也欣然接受。它们的共产主义势力愈弱，它们就愈加要模仿（甚至包括形式）苏联“老大哥”的极权主义的俄式共产主义。

至于像共产主义运动势力较大的法国和意大利，因在工业方面要努力赶上其他工业发达的国家，于是就遭遇到社会上的困难问题。但是因为这些国家已经过民主和工业革命，他们的共产主义运动就与俄国、南斯拉夫及中国大不相同。所以，在法国和意大利没有革命的机会。因为他们生活在政治民主的环境中，即使共产党的领导人也不能完全除去对议会政治的幻想。于是对于革命的前途，他们只好多仰赖于国际共产主义运动和苏联的援助，而不能靠自己的革命势力。他们的党徒以为他们的领导人是为了克服贫困而奋斗，就天真地相信党所斗争的目标是更广大更真实的民主。

现代共产主义的思想是随现代工业的创始而发生的。在工业发展已达到其基本目标的国家中，共产主义便告死亡或被消灭了。共产主义只在工业不发展的国家得以发展滋长【同样工业发展起来的国家也将宣告共产主义的死亡。】。

共产主义在落后国家的历史任务已经决定了革命的道路与性质，并且必促其实现。


* 革命的性质
** 一
历史告诉我们，在发生共产主义革命的国家中，其他政党也都不满现状，最显著的例子是俄国，除共产党外，使共产主义革命成功的还有其他政党。
 
然而，只有共产党是既反对现状而又坚决一贯地支持工业化运动。实际上，这是从根本上摧毁既有的所有权关系。在这一方面，其他的政党没有如此激烈。没有一个政党“热心工业”到那种程度的。
 
为什么这些政党在它们的纲领中一定要具有社会主义的内容呢？其原因不那么明显。在帝俄的落后环境中，资本主义的私有财产制度不只显得不足以迅速完成工业化，而且事实上在阻挠工业化。俄国的资产阶级是在一个极端强有力的封建关系依然存在的领域中发展起来的，同时这个原料丰富、市场广大的国家一直是在其他比它先进的国家的控制之下。
 
由于历史条件的影响，工业革命在沙皇统治下的俄国不得不姗姗来迟。在欧洲国家中，俄国是唯一没有经过宗教革命和文艺复兴运动的国家。它同欧洲中世纪时的城市国家没有一处相似。落后，半封建，君主专制，政府集权，有些地方的无产者人数激增，俄国就是在这样的情况下被卷入近代资本主义漩涡，而成为世界各国大银行中心攫取其经济利益的目标。
 
列宁在他的《帝国主义是资本主义的最高阶段》一书中说，俄国大银行的资本有四分之三是外国资本家的。托洛茨基也在他的《俄国革命史》中强调这一点。他指出，外国资本家握有俄国工业资金的40%，在某些重要工业上的百分比甚至比这个数字还要高。就南斯拉夫来说，在南斯拉夫最重要的经济部门中，外国人有决定性的势力。这些事实的本身并不说明什么。但是，它们表明，外国资本家用他们的权力来阻止这些国家的进步，他们把这些地区当作他们所需要的原料和廉价劳力的供应地，结果使这些国家不会进步，甚至还开始衰落。
 
在这些国家中，凡是负有要发动革命这一历史任务的政党在对内政策上不得不反对资本主义，在对外政策上不得不反对帝国主义。
 
再就内部的情况说，本国资本是软弱无力的，并且大部分是外国资本的工具或附属物，因而，对工业革命真正有兴趣的并不是资产阶级，而是从日益贫困的农村中走出来的无产阶级。就像消除残酷的剥削是那些已经成为无产者的人们的生死大事一样，工业化运动是那些即将成为无产者的人们的生死大事。代表这两类人的运动必然是反资本主义的，那就是说，在观念上、口号上和诺言上必然是社会主义的。
 
除非革命的政党能控制国内一切资源，特别是那些因实行严厉的剥削和使用不人道的方法而遭群众痛恨的本国资本家的资源，否则，革命党就不能认真地计划实行工业革命。同时，革命党还得对国外资本家采取同样的对策。
 
其他政党不能采用类似的政纲。它们不是想恢复从前的旧制度，就是想保持既得利益，或者最多也不过是谋求逐步地和平发展。甚至那些反对资本主义的政党：如俄国的社会革命党，都想把社会拉回到古时农人的田园生活。甚至像俄国的孟什维克【布尔什维克？】这类社会主义的政党，也只不过是想用激烈的手段推倒自由资本主义发展的障碍。孟什维克党人的观点是，为了这到日后的社会主义，就必须先充分地发展资本主义。然而，事实上，问题不是这么一回事；在这些国家中，复古或者加速资本主义的发展都行不通。在特定的国内外条件限制下，两者都不能解决这些国家进一步发展的迫切问题，即工业革命问题。
 
只有既主张进行反对资本主义的革命又主张迅速推行工业化运动的政党才有成功的希望。此外，很明显，这个党必须确信社会主义。不过,由于这个政党必须在既有的一般条件下，以及在工人运动或社会主义运动中活动，所以在意识形态上，这样的一个政党必须凭借两点，即近代工业必定会产生而且是有用的，以及革命是不可避免的信条。这种观念已经存在，只须稍加修改就行了。这种观念就是马克思主义——它的革命的一面。于是，它与革命的马克思主义结合起来，或与欧洲的社会主义运动结合起亲，是再自然不过的事了。后来，随着革命的发展以及工业先进国家在组织上的变动，这个党又必须与欧洲社会主义的改良派分手。
 
革命和迅速的工业化的不可避免，曾造成巨大的牺牲和采用暴力手段，这就不只需要诺言，而且对人间天国到来的可能性要有信心。革命和工业化运动的信徒和其他人的行动一样，循着阻力最少的路线前进，他们常常离弃已确立的马克思主义和社会主义教条而另辟途径。可是，他们并不能完全摒弃马克思主义的教条。
 
资本主义和资本主义关系是适当的、而且在特定的时间内也是不可避免的形式与技术，社会可以通过它们表达其需要和愿望，以谋求生产改进与扩大。在英国，在十九世纪的前五十年中，资本主义使生产有了改进和扩大。正像英国的工业家为了扩大生产而不得不摧毁农民的利益一样，俄国的工业家或资产阶级就不得不成为工业革命的牺牲品。参与人和形式井不相同，但规律却完全一样。
 
不论是在英国或俄国，社会主义总是不可避免地被用作口号和誓言，被当作一种信念和高尚的理想，并且在事实上被作为一种特别的政府形式和所有权形式，这种形式将便利工业革命并且使生产作可能的改进与扩大。

** 二
所有历史上的革命都是在新的经济或社会关系已开始抬头、而旧有的政治制度已成为进一步发展的唯一障碍时才发生的。
 
所有这些革命者是要摧毁旧有的政治形式，并为旧社会中早已成熟的新的社会力量和关系开路。在某些革命中，革命者甚至要求得多点，例如，雅各宾党人在法国大革命时期中曾试图以武力建立新的经济和社会关系，但是他们不得不失败并且很快被消灭。
 
在从前所有的革命中，武力与暴力主要是作为后果、作为新的但早已得势的经济和社会力量与关系的工具而出现。即使在进行革命时，武力与暴力超出了适当的限度，然而最后，革命的力量总不得不被导向一个积极的并且可以达到的目标。在这种情况下，恐怖与专制也许在所难免，但只是暂时的现象。
 
一切所谓资产阶级革命，不论是由于下层的支持而取得成功，例如由群众参加的法国革命，或是像德固俾斯麦时代的来自上层的政变，都必然以政治民主告终。那是可以了解的事。那些革命者的任务主要是摧毁旧的专制政体，建立一种将能适合现有经济及其他需要的政治关系，特别是适合商品自由生产的需要。
 
当代共产主义革命完全是另一种不同的革命。它们的发生并不是因为新的或社会主义的关系在经济中早已存在，或者因为资本主义已经“过度发展”。恰恰相反，共产主义的发生正是因为资本主义不够发达，或者因为这个社会没能力使自己工业化。
 
在法国，在革命开始以前，资本主义早已存在于法国的经济领域内，社会关系上，甚至公众的良知中。这很难和俄国、中国或南斯拉夫等国的社会主义相比。
 
俄国革命的领袖们是明白这一事实的。当革命还在进行时，列宁曾于1918年3月7日在俄国共产党第七次代表大会上说：
 
“……资产阶级革命和社会主义革命的基本区别之一就在于：对于从封建制度中生长起来的资产阶级革命来说，还在旧制度内部，新的经济组织就逐渐形成起来，它逐渐改变着封建社会的一切方面。……任何资产阶级革命完成了这个任务，也就是完成了它所应做的一切：它加强资本主义的发展。
 
“社会主义革命却处在完全另外一种情况中。由于历史进程的曲折而不得不开始社会主义革命的那个国家越落后，它由旧资本主义关系过渡到社会主义关系就越困难。……
 
     “社会主义革命和资产阶级革命的区别就在于：在资产阶级革命时，现成的资本主义关系的形式已经具备了。而苏维埃政权，即无产阶级政权，却没有这种现成关系，有的仅是那些实际上包括一小部分工业上层而很少触及农业的最发展的资本主义形式。”【见《列宁全集》第27卷，人层出版社1961年版，第77-78页。——译者】
 
我引述了列宁的话，但我还可以引录任何一个共产主义革命领袖及其他许多作者的话来证实一项事实，即新社会中并无既定的关系存在，不过总有人必须来建立这种关系，而在这种情况下就必须由“苏维埃政权”来建立。如果新的“社会主义”关系已在共产主义革命趋向胜利的国家里有最充分的发展，那就无须环绕“建设社会主义”而作那么多的保证、论证和努力了。
 
这一事实导致我们发现一个再明显不过的矛盾。如果一个新社会所需要的条件还未充分具备，那末，是谁要革命的呢？再则，革命又怎么可能呢？新的社会关系既然在旧社会中尚未成形，革命又如何能维持下去呢？
 
过去从未有任何革命或政党把建立社会关系或新社会作为自己的任务。然而，这正是共产主义革命的首要目标。
 
共产主义革命的领袖们虽不比其他的革命领袖更熟知支配社会的规律，他们却发现，在有可能进行共产主义革命的国家中，实行工业化也是可能的，特别是当他们使社会的改选按照他们的意识形态上的假设进行时，更有此可能。革命在“不利的”条件下取得成功的经验证实了这一点，“社会主义建设”也证实了这一点。这就加强了他们的幻觉，以致他们自以为深知社会发展的规律。事实上，他们是先为一个新社会设计一幅蓝图，然后动手去建造，不对的地方就加以修改或废弃，务求一切尽量合乎他们的计划。
 
在进行共产主义革命的国家中，工业化作为一种不可避免而合理的社会需要，便和共产主义的完成工业化的方式结合起来了。
 
革命与工业化虽在平行的轨道上齐头并进，然而，不论是前者或后者都不能在一夜间完成。在革命成功后，必须有人肩负工业化的责任。在西方国家中，这一任务是由从专制的政治锁链中解放出来的资本主义经济力量担当的，但在发生共产主义革命的国家中并无类似的经济力量存在，所以只得由革命机构本身来担当，也即由新政权，由革命政党来担当。
 
在以前的革命中，在旧秩序被推翻后，革命的武力和暴力便成为经济上的一种障碍。在共产主义革命中，武力和暴力却是进一步发展甚至进步的一个条件。在以前的革命者看来，武力和暴力只是一种不可避免的弊害和达到目的的一种手段。可是，在共产党人的心目中，武力和暴力竟被提高到偶像和最后目标的崇高地位。在过去，构成一个新社会的阶级和力量早在革命发生前就已存在。而共产主义革命却是第一个不得不创造新社会和新的社会力量的革命。
 
正像西方国家的革命经过一番“偏差”与“撤退”后必然以民主告终一样，东方国家的革命则必然形成专制。在西方国家中，恐怖与暴力已变成无用和可笑的东西，甚至成为革命者和革命政党完成革命的障碍，而在东方国家，情形则恰恰相反。专制不只是由于工业化需要一段很长的时问而继续存在，而且，我们以后将看到，即使在工业化完成以后，它仍将长期存在。
 
** 三
在共产主义革命和以前的革命之间还有其他的基本差别以前的革命虽然在经济上和社会上已达到准备就绪的阶段，但如果没有有利条件，是不会爆发的。我们现在都知道一个革命爆发和成功所必需的一般条件。然而，除了这些一股条件之外，每次革命都还得有些特殊的条件才能使其计划和实行成为可能。
 
战争，或者说得更准确一些，整个国家组织的崩溃，对于过去的革命，至少对那些较大的革命是不需要的。然而现在，这却是共产主义革命胜利所必需的一个基本条件。对中国来说甚至是行之有效的，不错，中国的革命开始于日本侵略中国之前，但它经过整整十年的时间来继绩扩大实力，终于在战后取得了胜利。1936年的西班牙革命可能是一个例外，但由于它未有足够时间转变为一个纯粹的共产主义革命，因此未获成功。
 
共产主义革命或打碎国家机器之所以需要战争，必然是由于经济和社会条件不成熟。在一个制度土崩瓦解时，特别是当当时的纯治阶级和国家制度在战争中失利时，一个组织完善、训练有素的小团体必然能够取得政权。
 
因此，当十月革命发生时，俄国共产党只有八万名党员。而南斯拉夫共产党在1941年开始革命时只有一万名党员。为了夺取政权，至少必须有一部分人民的支持和积极的参与，但是，不论在哪一次革命中，领导革命并掌握权力的政党总是一些完全依靠非常有利条件的少数人。而且，在这个党的政权尚未稳固以前，它是不可能成为一个多数人的集团的。
 
要完成这样一种艰巨的工作——在不利的社会经济条件下摧毁旧秩序，建设一个新社会——只能吸引少数人，并且只有那些对它的可能性抱有狂热信心的人才会被吸引。
 
特有的条件和一个特殊的党是共产主义革命的两个基本特征。
 
任何革命的成功以及战争的胜利都要求一切力量的集中。根据马尔萨斯的说法，法国革命是第一次把“一个民族的一切资源——人民，食物，服装——在战争中都交给当局”的革命。可是，在共产主义的“不成熟的”革命中，集中的程度却超过法国的革命，不只一切物质资源，而且连一切智力资源在内都得交给党，而党的本身，作为一个组纤，又必须在政治上充分地集中权力。只有共产党由于在政治上团结一致，坚定地团结在中央的周围，并具有一致的思想意谶，才能实现这样的革命。
 
 一切力量和资源的集中以及革命政党的某种性质的团结，是任何成功的革命所必需的条件。对共产主义革命来说，这些条件甚至更加重要，因为共产党人在一开始就排斥其他独立的政治团体或政党，不让他党与之为友。同时，他们要求一切观点一致，包括实用的政治观点以及理论的、哲学的观点，甚至道德观点都得—致。俄国社会革命党左派的参加十月革命，以及其他政党的个人或团体的参加中国和南斯拉夫的革命的事实，非但没有否定而且反而证实这一理论：这些团体只是共产党的合作者，而且只是在斗争中进行一定限度的合作。革命后，这些与它合作的政党都得解散，不然就是自行解散而并入共产党。当社会革命党左翼想独立时，布尔什维克立刻将它击溃，而南斯拉夫和中国的支持革命的非共产党团体，也得放弃各自的政治活动。
 
以前的革命都不是单由一个政治团体来完成的。诚然，在进行革命的过程中，各个团体不免相互倾轧和破坏；不过，整个说来，革命并不只是一个团体的工作。在法国革命时期，雅各宾党人的独裁只维持一个很短的时期。从革命中出现的拿破仑的独裁，一方面表明雅各宾党人革命的结束，问时也表明资产阶级统治的开始。不论怎样，在以前的革命中，虽然有一个政党会居于举足轻重的地位，但其他政党绝非附庸。虽然有压制和解散的事，但这些事只能在短时期内强制执行。其他的政党并不能被摧毁，并且常常会东山再起。甚至被共产党人认为是他们的革命与国家先驱的巴黎公社，也是一个多党的革命。
 
在革命的某一个特定阶段中，可能由某一个党派扮演主要的甚至唯一的角色。不过，在以前的政党中，没有一个政党在意识形态上或在组织上集中到像共产党那样的程度。不谕是英国革命中的清教徒或法国革命中的雅各宾党人，在哲学上和意识形态上的观点也并不完全一致，尽管清教徒还是个宗教派别。从组织的观点看，雅各宾党只是俱乐部的一个联盟，清教徒甚至连联盟都说可不上。只有当代的共产主义革命强使政党在意识形态上和组织上一元化。
 
不论怎样，有一件事是确切无疑的：在以前的革命中，随着内战以及国外干预战事的结果，革命手段和革命政党的需要就消失了，这些手段和政党也不得不消逝。但在共产主义革命完成后，共产党人依然保持革命的手段和形式，并且他们的党立即在行政的集权上和意识形态的划一上达到最高的程度。
 
在革命时期，列宁在列举他的关于加入共产国际的条件时曾公然强调这一点：
 
“在目前激烈的国内战争时代，共产党必须按照高度集    中的方式组织起来，在党内实行像军事纪律那样的铁的纪    律，党的中央机关必须拥有广泛的权力，得到全体党员的普    遍信任，成为一个有权威的机构。只有这样，党才能覆行自己的义务。”【见《列宁全集》第31卷，人民出版社1960年版，第185页。——译者】
 
斯大林在《列宁主义基础》一书中又为列宁的话作了如下的补充：
 
“在争得专政以前的斗争条件下，党内纪律的问题就是这样。
 
“关于争得专政后的党内纪律也应该这样说，而且更应该这样说。”
【见《斯大林全集》 第6卷，人民出版杜1956年版，第159页。——译者】
 
在取得政权后，革命的气氛和警惕性，意识形态的继续保持统一，政治与意识形态的一元化，政治上以及其他方面的中央集权等现象都未终止。恰恰相反，这些现象甚至更加强烈。
 
在以前的革命中，手段的残暴、思想的统一以及权力的集中差不多总是与革命同时结束的。然而，由于在共产主义革命中，革命只是一个集团的专制极权当局的第一个行动，所以就很难预测这种权力的期限。
 
在以前的革命中，包括法国的恐怖统治时期在内，从表面上看，注意力总是放在消灭真正的反对上面，没有人去注意消灭未来可能的反对者：只有在中世纪的宗教战争时期，才有对某些社会团体或意识形态不同的团体加以清除和迫害的事。共产党人知道，不管是在理论上或实践上,他们是同其他阶级和意识形态对立的，因此，他们得对其他的阶级和具有其他意识形态的人加以迫害和清除；他们不只对实际存在的反对者并且还对未来可能的反对者作战、在波罗的海沿岸诸国中，一夜之间曾有数千人遭到清算，原因是查出他们以前曾持有其他的意识形态和政治观点。数千波兰官员在卡亭森林被屠杀也是类似性质的事件。在共产主义制度下，在革命早已过去以后，还和继续使用恐怖主义的压制手段。有时，这些手段变得更加完整，并且比革命时期中用得更广泛，如对富农的清算便是最好的例子。在革命后，意识形态的统一与不容忍是加强了，即使当肉体的迫害能够减少时，执政党还倾向于加强规定的意识形态——马克思列宁主义。
 
以前的革命，特别是所谓资产阶级革命，很重视在革命的恐怖停止后立即建立个人自由，甚至革命者还认为保证公民的合法地位甚为重要。司法独立是所有这些革命必有的最后结果。苏联革命已经四十年了，在共产主义制度下，司法独立的实现尚遥遥无期。以前历次革命的最后结果往往是更大的法律保障和更多的公民自由。共产主义革命是谈不上这一切的。
 
以前的革命和现在的共产主义革命还有另一个巨大的差别。以前的革命，特别是那些较大的革命，是工人阶纽斗争的产物，可是，革命的最后果实则落在智力上并且常常是在组织上领导革命成功的另一个阶级手中，在以资产阶级的名义进行的革命中，农民和贫苦大众的斗争果实在很大程度上被资产阶级所享有。在共产主义革命中，国内的群众也参加了革命，然而，革命的果实并未落入他们的手中，而是给了官僚集团。因为官僚集团正是使革命实现的党组织。在共产主义革命中，只有实现革命的革命运动没有被放弃。共产主义革命可能“吃掉自己的儿女”，可是并不是把它们全部吃光。
 
事实上，在一次共产主义革命完成时，在对未来路线持异议的各派系间，总不免使用无情而卑鄙的手段。
 
彼此的攻击总是围绕着教条，它们指责对方在“客观上”或“主观上”是反革命分子或国内外“资本主义”的代理人、不管这些异议在何种方式下解决，得胜的必然是最坚决而一贯地支持按照共产主义原则进行工业化的那一派，而共产主义原则也就是以党的彻底垄断、特别是由国家机构控制生产为基础，共产主义革命并不吃掉将来工业化所需要的那些儿女。被清除掉的往往是那些从文字上接受革命的观点与口号并天真地信它们将会实现的革命者，了解革命能在社会、政治和共产主义的基础上取得权力并以此作为推行未来工业改革的工具的那一派总是胜利的。
 
革命者及其盟友，特别是行使权力的集团，在革命后还依然存在，这种事实，只见于共产主义革命。在以前的革命中，类似的集团都没有做到这一点。共产主义革命是第一个为革命者带来好处的革命。革命者以及围绕他们而形成的官僚集团共享革命的果实。于是，这在革命者中以及在更广大的党的外围群众中便产生一种错觉，以为他们的革命是历史上第一个一直忠于它所标榜的口号的革命。
 
** 四
共产主义革命为它的真正目标所制造的幻想，比以前历次命所制造的幻想更加经久而广泛，因为共产主义革命以一种新的方式解决各种关系，并且带来一种新的所有权形式。以前的革命当然也不免带来或大或小的财产关系的变动。不过，那只是在一种私有财产制之下的所有权的更迭。而共产主义革命所带来的变动则不是这样，变动是彻底的、根本的，这是集体所有权代替了私人所有权。
 
当共产主义革命还在发展过程中时，它就已经在摧毁资本主义的、土地占有的和私人的所有权，也即利用外国劳动力的所有权。这立刻造成一种信念，以为革命所允诺的一个新的平等而公正的社会已经实现。同时，党或者在党控制下的国家权力机构在采取广泛的工业化措施。这也使群众更加以为丰衣足食的日子终于来临。专制与压迫是有的，但人们认为那只是暂时的现象，财产被充公的以前有势力的人们以及反革命分子的反抗一旦被消除，工业化一经完成，专制与压迫就会结束。
 
在工业化过程中，有几项根本的变化发生了。一个落后国家的工业化，特别是如果它没有得到援助和遭受外力的阻碍时，必然要求一切资源的集中。工业财产及土地的国有化，是集中财产于新政权手中的第一步。然而，它并不就此止步，而且也不能就此止步。
 
这种新创立的所有权不可避免地要与其他形式的所有权冲突。新的所有权又以强力加在那些不雇工或雇工不多的小有产者身上，如手工业者，工人，小商人和农民。在剥夺小有产者的所有权时，甚至并不是由于经济动机，即并不是为了提高生产率。
 
在工业化过程中，连那些不反对革命甚至对革命出过力的人们的财产也不免被政府没收。在形式上，国家是这些财产的主人，由国家来经管这些财产。私有财产制被废除了，或者降到次要的地位，但它的完全被消灭却完全要看新当政者的兴致。
 
共产党人及一部分群众认为这是阶级的彻底消灭，一个无阶级社会的实现。事实上，工业化和集体化实现以后，革命前的旧阶级的确是被消灭了。群众中依然存在着不满，这种不满是自发的和没有组织的，他们的不满既未终止，亦位减轻。共产党人依然以“阶级敌人”的“残余”和“影响”来自欺欺人。尽管如此，他们却以为用这些手段实现了长期梦想着的无阶级社会，至少对共产党人自己来说这种幻想是完整的。
 
每一次革命，甚至每一次战争，总会制造出一些幻想，并且是借一些根本不可能实现的理想来进行的。在进行斗争的时期，战斗员们把这些理想看成真像是若有其事；可是到革命结束时，理想往往就破灭了。在共产主义革命中并不如此，在武装战斗终止很久以后，参与共产主义革命的人和那些贫苦大众仍保持着他们的幻想。某些人，特别是共产党人，依然把他们的幻想保留在口号中，而对于压迫、专制、公开的没收财产，以及统治者享有特权等，则视若无睹。
 
虽然在开始发动共产主义革命时可能是仗着最理想的观念，号召神奇的英雄主义与巨大的努力。但它所播种的却是最辽阔最经久的幻想。
 
在国家的生命史上，革命是不可避免的。革命可能以专政告终，可是它也把国家带上以前走不通的道路。
 
共产主义革命不能实现任何一种标榜为革命的推动力量的理想。可是，共产主义革命却为欧亚两洲广阔的地区带来某种程度的工业文明。这样，事实上共产主义革命已为未来更自由的社会创造了物质基础。因此，共产主义革命虽带来最完备的专制制度，但它同时，也创造了废除专政的基础。就像十九世纪把近代工业引给西方一样，二十世纪将把近代工业带给东方。列宁的影子正以不同的方式笼罩在欧洲和亚洲的辽阔的土地上。在中国是专制形式，在印度和缅甸则是民主形式，不论怎．样，所有其余的亚洲国家及其他各国正无可避免地进入工业革命。俄国的革命是这个过程的先导。这一过程仍然是革命中不可估计的和具有历史重要性的事实。

** 五
共产主义革命可能看来大部分都历史上的骗局和偶然发生的事故。就某种意义来说，这是事实，其他任何革命都没有需要这么多的例外条件，也没有其他任何革命许诺得如此之多完成得如此之少。在共产党领袖的言论中都必然有煽惑与欺蒙之词，因为他们迫不得已而许诺一个最理想的社会，而且答应“废除一切剥削”。
 
然而，我们并不能说共产觉人欺骗了人民。这也就是说，他们并不是故意言行不符，所做的与所许诺的完全两样。事实很简单：他们根本不能完成他们狂热地信以为可能实现的事，甚至当他们被迫去执行一种违反革命前及革命中所作诺言的政策时，他们还不承认这一点。从共产党人的观点看来，这种承认无异于自认革命是不需要的。同时，这也无异于自认共产党人是多余的累赘。对他们来说，这类事都是承认不得的。
 
一场社会斗争所得到的最后结果永远不会如斗争推动者当初的理想。有些斗争取决于人的智力和行动所不能控制的一连串无限复杂的环境。要求超人的努力并要在社会上实行迅速而彻底的变化的革命尤其如此。这类革命必然得制造绝对的信心。坚信革命胜利后，人类繁荣和自由终将出现。法国革命是在常识性的口号下，在相信自由、平等、博爱终于要出现的情况下发动的。俄国的革命是在为创造一个无阶级社会的"纯科学"的世界观号召下进行的。如果革命者和一部分人民不信仰他们的理想目标，就不可能有任何革命出现。
 
共产党人对革命后所产生的各种可能性的幻想比一般附从的群众更为强烈。共产党人可能已经知道，事实上，他们也确实知道工业化的不可避免，不过，他们对于工业化所造成的社会后果和社会关系，只能猜测而已。
 
苏联和南斯拉夫官方的共产主义历史学家，把革命描写成好像完全是共产党领导人事先计划好的行动的结果。事实上只有革命本身和武装斗争是有意识地计划的，至于革命所采取的形式则完全是从突然发生的事件和直接行动中产生的。毫无疑问，列宁是历史上最伟大的革命家之一，甚至在俄国革命快爆发时，他都不能预见到革命何时发生，或以何种形式发生。l9l7年1月，即距“二月革希”爆发只一个月，距使列宁取得政权的“十月革命”爆发仅十个月，列宁在瑞士社会主义青年的一个集会上致词说：
 
“我们这些老年人，也许活不到未来这次革命的决战那个时候了。但是我认为，我能够满怀信心地表示这样的希望，那就是现在正在瑞士和全世界社会主义运动中出色地工作着的青年们，不仅会幸运地参加未来的无产阶级革命，而且会在这个革命中取得胜利。”【见《列宁全集》第23卷，人民出版杜1961年版，第259页。——译者】
 
怎么能说列宁或其他任何人能预见到长期而复杂的革命斗争所造成的社会后果呢？
 
尽管共产主义的理想本身并不真实，可是，共产党人却和以前的革命者不同，他们在创建可能办到的事物时是非常认真的。他们用唯一可能的办法去尝试——行使绝对的极权主义的权威。在共产主义革命胜利后，不只革命者仍据守政治舞台，并且就最实际的意义来说，他们还在建立一种与他扪的信念和诺言完全相反的社会关系，这样的革命是史无前例的。在稍后的工业的发展和改革时期，共产主义革命把革命者转化为新社会的创造者和主人。
 
马克思所作的具体预测已被证明为不准确。列宁也曾期待在独裁制度的帮助下，一个自由的或无阶级的社会将被创造出来，这当然更不准确。不过，使革命必然发生的需要已经实现了，也就是在现代技术的基础上推行工业改革这一点已经实现了。
 
** 六
用抽象的逻辑可以推出，当共产主义革命在不同的条件下以政府的强制力得到西方工业革命和资本主义所得到的同样东西时，共产主义革命无非是国家资本主义革命的一种形式。革命的胜利所创造的关系乃是国家资本主义的关系。当我们发现新政府还管理一切政治、劳工等及其他关系时，更使我们相信这一点。而更重要的是，新政权还负责分配国家总收入、利润以及实际已变为国家的财产的物资。
 
苏联以及其他的共产主义国家的各种关系是国家资本主义关系或社会主义关系或是其他关系呢?讨论这些问题是相当武断的。可是，这种讨论却具有基本意义。
 
尽管正如列宁所强调的，我们可以假定国家资本主义不过是“社会主义的前厅”，或者说，这是社会主义的第一个阶段，这依然丝毫不能让呻吟于共产主义专政下的人民稍感舒适，觉得日子容易挨一点。如果共产主义革命所带来的财产和社会关系的特性有了更为肯定而明确的说明，那末人民从这种关系中解放出来的希望就会变得更实际一些。如果人民不明白他们生存其中的社会关系的性质，或者说，如果人民找不出如何改变它们的方法，那末他们的斗争就不能有任何成功的希望。
 
不管共产主义革命的诺言和幻想如何，如果共产主义革命只是依国家资本主义关系行事的国家资本主义，那末工作人员所能采取的唯一合法而积极的行动，必然是改进工作并且减少国家行政当局的压力和不负责任的情形，共产党人在理谕上并不承认他们是在国家资本主义制度下工作，可是，他们的领袖却在以国家资本主义方式行事。他们不断地白吹自擂，夸口如何改进行政工作和领导“反官僚主义”的斗争。
 
再则，实际的关系并不是国家资本主义关系；这些关系并不提供从基本上改进国家行政系统的方法。
 
为了确定兴起于共产主义革命时期并在工业化和集体化的过程中终于建立了起来的各种关系的性质，我们必须进一步研究国家在共产主义制度中所扮演的角色及其活动方式。这里，我们所要指出的只是：在共产主义制度中，国家机器并不是真正决定社会关系和财产关系的工具，它只是保护这些关系的工具。实际上，每种事物都是在国家的名义下并通过国家的约束完成的。共产党，包括职业性的党的官僚在内，却不受约束并在背后操纵国家的—切行动。
 
正式使用、管理并控制国有化和社会化财产以及整个社会生活的，是一群官僚。官僚在社会中居于一种特殊的特权地位，掌握行政大权，控制国民收入和国家物资。社会关系类似国家资本主义。而且由于工业化的实现并非得力于资本家的帮助，而是得力于国家机器的帮助，就更显得如此。事实上，是这个特权阶级在推行工业化，国家机器不过是它的护身和工具。
 
所有权不过是享有利润和控制的权利。如果有人把阶级利益解释为这种权利，那么分析到最后，我们可以说共产主义国家正有一种新的所有权形式在兴起，或者说，正有一个新的统治剥削阶级在兴起。
 
实质上共产党人的行动无法与以往的任何统治阶级不同。他们相信他们正在建立起一个新的理想社会，他们用他们所能采取的方式为自己进行建设。他们的革命与他们的社会看来并非偶然，也非不自然，这只是某一个国家在发展过程的某一阶段中必然发生的事。因此，不管共产主义的暴政是如何广泛和不人道，在继续推行工业化的这个时期中，社会中的人民不得不忍受并且也能够忍受共产主义的暴政。再则，这种暴政已不再俨然是不可避免的事，而完全是为了保障一个新阶级的掠夺和特权。
 
与以前的革命相反，共产主义革命是以取消阶级为号召开始，但最后竟造成一个握有空前绝对权威的新阶级。其他的一切都不过是欺骗和错觉而已。


* 新阶级
** 一


在苏联和其他共产主义国家所发生的每一件事情，都与那  些领导人物（甚至列宁、斯大林、托洛茨基和布哈林等卓越的领导人物）所预料的不同。他们预料国家将迅速消灭，而民主将会加强。然而，发生的事恰恰相反。他们预料生活水平将迅速提高——事实上在这方面却很少变动。而在东欧卫星国家中甚至比过去还低。从一切事例看来，生活水平的提高并没有能与工业化的速度相称，工业化的速度要快得多。他们相信，城市和乡村的差别以及脑力劳动和体力劳动的差别将逐渐消失；可是，这差别却在增加。  共产党人对其他地区的顶测，包括对非共产主义世界发展的预测在内，也都未能突现。
 
他们最大的幻想是：在苏联实行工业化和集体化以及摧毁资本主义的所有权以后，将产生一个没有阶级的社会。在1936年新宪法颁布时，斯大林曾宣告“剥削阶级”已不再存在，资产阶级及古时传下来的其他阶级事实上是被消灭了，不过，一个历史上前所未闻的新阶级却形成了。
 
像过去的其他阶级一样，这个阶级会认为其权力的建立将使所有的人幸福和自由，他们作如此想法是可以了解的。这个新阶级与其他阶级的唯一差别是：它对它的幻想的迟迟不能实现用更粗暴的方式来处理。因此它肯定了它的权力比历史上以前的任何其他阶级更为完全，它的阶级幻想和偏见因而也比其他任何阶级更大。
 
这个新阶级，这一群官僚，说得更准确点，这一群政治官僚，不只具有前此一切阶级所共有的特质，还具有一些它独有的新的特质，虽然从本质上说，它与其他阶级开始时的情况类似，但它的起源仍有其独特的性质。
 
其他的阶级也是通过革命的途经而取得力量和权力的，它们曾摧毁途中所碰到的政治的、社会的以及其他方面的秩序。然而，几乎没有例外，这些阶级都是在新的经济类型已在旧社会中成形以后才取得权力的。在共产主义制度下的新阶级，其情况却完全相反。它取得政权并不是为了去完成一个新的经济秩序，而是为了建立一个它自己的经济秩序，因此，它必须建立其控制社会的权力。
 
在以往，某一阶级或某一阶级的某一部分人、或某一个政党的取得政权，都是它们的形成和发展的最后一件事。苏联的情况恰恰相反。新阶级是在它取得政权后才形成的。它的阶级意识不得不在它取得经济的和物质的权力之前发展，因为这个阶级并未在国家生活中生根。这个阶级是从一个理想的观点去看它自己在世界舞台上所扮演的角色的。它的各种实际可能性并未因此而稍减。尽管它有种种幻想，它却代表走向工业化的客观趋势，它的实际的倾向是从这个趋势产生的。理想世界的诺言增加了新阶级分子的信心，而且在群众中散播了幻想。同时，它还激励人们担任庞大的物质建设任务。
 
由于这个阶级未能在它取得政权前形成经济和社会生活的一部分，因而它只能在一种特殊形式的组织中产生，它因具有成员的意识形态与哲学观点一致的一种特殊的纪律而与众不同。为了克服弱点，就必须信念一致和有铁的纪律。
 
这个新阶级植根于一个布尔什维克式的特殊的党。列宁认为他的党是在人类的历史上没有先例的，他的这个见解是对的，尽管他没有想到这竟是一个新阶级的起源。
 
说得更精确一点，这个新阶级的创始人不是存在于整个布尔什维克式的党内，而是存在于那些甚至在它还未取得政权前即已构成核心的职业革命家中。1905年的革命失败后，列宁坚决认为只有职业革命家，即专以革命工作为职业的人们，才能建立一个布尔什维克式的新党，这并不是偶然的。甚至斯大林，这个新阶级的后来的创始人，也是一个这种职业革命家中的最典型人物，则更非由于偶然。这个新的统治阶级是从这些极少数的职业革命家中逐渐发展出来的。这些革命者早就构成革命的核心了。托洛茨基曾指出，革命前的职业革命家正是日后斯大林官僚集团的来源。但他没有觉察到，他们也正是一个所有者兼剥削者的新阶级的起源。
 
这并不是说新党与新阶级是合二而一的。然而，党却是那个阶级的核心和基础。要明确这个新阶级的范围并指明这个阶级的成员是非常困难的，或许是不可能的。也许我们可以说，这个阶级是由那些因垄断行政大权而享有种种特权和经济优先权的人们构成的。
 
由于社会中免不了有行政，于是，必要的行政功能就可能与寄生作用同时存在于同一个人身上。就像并非每个工匠或城市人都是资产阶级的成员一样，共产党人也并不是每一个都是这个新阶级的成员。
 
粗略地说，当这个新阶级愈来愈强、它的面貌愈来愈清楚时，党的作用就日益减退。新阶级的核心和基础是在党和党的领导阶层以及国家的政治机构中创造出来的。一度曾经是生气勃勃、组织严密和充满首创精神的党正在消失，而逐渐转变为这个新阶级的传统式的寡头统治，所以它不可避免地要吸收那些一心希望加入新阶级的人，压制那些具有任何理想的人。
 
党制造了这个阶级，但是，这个阶级靠党长成并利用党为其基础。这个阶级愈来愈强，而党却愈来愈弱；这是每一个执政的共产党无可逃避的命运。
 
假如他不从物质上关心生产，或者说假如它本身没有创造一个新阶级的潜力，那么没有一个党能够以道德上和意识形态上如此愚妄的方式行动，更谈不上还能长久执政。在第一个五年计划结束后，斯大林宣称："如果没有创立机构，我们或许已经失败！"他应该用"新阶级"一词来代替"机构"，要是这样，一切事情就更清楚了。
 
一个政党竟会是一个新阶级的起源，这似乎并不寻常。政党通常是在知识上和经济上已相当强而有力的阶级或阶层的产物。可是，只要我们了解俄国革命前的情况以及在其他一些国家中共产主义已胜过民主力量的实际情况，我们就会明白：这种类型的党是许多特殊机缘的产物，就这一点说，并没有什么不寻常，也并不偶然。尽管布尔什维克主义在俄国历史上有其渊源，但部分说来，布尔什维克主义只是俄国在19世纪末和20世纪初所遭遇的独特的国际关系的产物。那时候，俄国已不能再以一个君主专制国家生存于当代世界，同时，俄国的资本主义太弱，而且过分地依附于国外的利益，以致它不可能推动俄国的工业革命。所以这个革命只能由一个新的阶级来推行，或者通过改变社会的秩序来进行。然而，当时并没有这样的阶级。
 
在历史上，谁推动一个进程并不重要，重要的指示这个进程要有人来推行。俄国和其他国家之所以发生了共产主义革命，就是这个道理。革命创造了她所必需的力量、领袖、组织和观念。新阶级的出现一方面是基于客观原因，一方面也是出于党的领袖的愿望、机智和行动。
 
二
这个新阶级的社会根源出自无产阶级。正如贵族阶级之兴起于农民社会，以及资产阶级之兴起于商业工艺社会。当然也有例外，这全看国家的情况来决定，不过，经济不发达的国家的无产阶级，由于落后，就构成了这个新阶级兴起于原料。
 
关于为什么这个新阶级是以工人阶级的保护者的姿态出现这一点，还有别的原因。新阶级是反对资本主义的，因此，他当然依靠工人阶级。新阶级是靠无产阶级斗争以及无产阶级对社会主义、共产主义社会中将无残酷剥削的传统信仰来支持的。对这个新阶级来说，保证生产正常具有无根本的重要性，因此，它就永远不能和无产阶级失去联系。而最重要的原因是：没有工人阶级的帮助，他就不能完成工业化和巩固他的权利。而另一方面，工人阶级知道在工业的发展中，他们将从贫困与失望中被解救出来。经过一个长时期以后，这个新阶级利益、观念、信念和希望同一部分工人阶级和贫农的利益、观念、信念和希望相符而且结合在一起了。在历史上，这种结合曾发生于各种距离甚远的阶级之间。在反封建制度的斗争中，资产阶级不是曾代表农民吗？
 
这个新阶级之所以能够夺取政权，是工人阶级和贫苦大众努力的结果。这些人正是共产党，或者说新阶级必须依靠群众，而新阶级的利益同他们有最密切的联系。在新阶级未取得政权和确立其权威地位以前，两者的关系确是如此。在这以后，这个新阶级对无产阶级和贫民的兴趣只限于利用他们去发展生产和控制这些最勇猛和最难驾驭的社会力量。
 
这个新阶级以工人阶级的名义所建立的对整个社会的垄断，主要就是对工人阶级本身的垄断。首先是知识上的垄断，现对所谓的无产阶级先锋队，那是对整个无产阶级。是个新阶级所必须完成的最大的骗局，不过，它也表明，这个新阶级的权利和利益主要还是寄托在工业中。没有工业，这新阶级就不能巩固其地位和权威。
 
旧日工人阶级的儿女是这个新阶级最靠得住的成员。为主人供应最聪明最有天赋的代表本是奴隶不可避免的命运。在这种情况下，一个新的剥削和统治阶级就从被剥削的阶级中产生了。
 
三
当共产主义制度被拿来作批判性的分析时，我们发现，其基本特色在于官僚政治，有一个特殊的阶层来统治全体人民。一般说来都是这样。可是，更仔细地分析将表明，构成这个进行统治的官僚集团（或者，我的术语讲，这个新阶级）核心的只是官僚中的一个特殊阶层，他们并不是行政官员。实际上，那是一群党的官僚，或者说政治官僚。其他的官员实际上只是受这个新阶级控制的机件；这些机件可能笨拙而不灵活，但是无论怎样、任何社会主义社会中都免不了有它们存在。就社会学的理论说，我们是可以把各式官僚加以分类、但实际上它们之间实在难分彼此。师师部指使由于共产主义制度本质上就据有关两性，而且因为共产党人实际上控制着各种重要的行政任务。再则，如果这个政治官僚阶层把自己桌上的残羹施舍给其他类的官僚就难以享用他们的特权。
 
注意以上所说的政治官僚与那些随现代经济的每一集中制度（特别是那些促成集体所有制形式的集中制度，如垄断组织、公司和国有制）而兴起的官僚间的基本区别，是很重要的。在西方国家，资本主义垄断企业或国有化工业中的靠薪金过活的工作人员人数在不断地增加。杜宾在他的《行政工作中的人类关系》【普伦蒂斯-奈尔（prentice-hail）出版公司，纽约1951年版】（Human Relation in Administration）一书中说，经济部门的国家工作人员正在转变为社会的一个特殊阶层。
 
“……这些在一起工作的职员有生死同命的意识。他们分享同样的利益，特别是在圣城取决于资历而彼此间很少竞争的情况下。于是，内部的摩擦减少到了极低的限度，因而这种安排被认为对官僚政治是有积极作用的。然而，在这种情况下典型的发展出来的团体精神与非正式的组织每每导致这些支援维护他们自己的利益，而不协助顾客和选任的上司。”
 
这些公务人员同共产主义国家中的官僚有许多类似之处，特别是在团体精神方面，但他们并不完全一样。尽管在非共产主义国家中，国家的和其他方面的官僚形成一个特殊阶层，可是，他们并没有共产党人那样的权力。在非共产主义国家的官僚的上面通常有任选的政治主人和公司老板，而在共产党人之上却既无主人也无老板。非共产主义国家中的官僚这是现代资本主义经济中的一些官员，而共产党人却是另一种不同的新东西：一个新阶级.
 
要证实某一阶级是否是一个特殊的阶级，就在于他的所有权以及它与其他阶级的特殊关系做好这正和其他享有所有权的阶级中的情况一样。同样的话一个阶级可以从所有权所给予他的成员的物质的及其它方面的特权标志出来。
 
正如罗马法所规定的，财产构成物资的利用、享受和存储。而共产党的政治官僚就利用、享受并存储收归国有的财产。
 
如果我们假定，这个官僚集团或这个享有所有权的新阶级的成员的身份、是根据他们所使用的因所有权给予的特权　这里指的是收归国有物资　来确定的，那么这个新阶级和政治官僚的成员身份就由他们所得到物质上的收入和特权中反映出来，而他们所得到的物质上的享受和特权的社会上一般所应该给予他们的分量要多。实际上，这新阶级的所有权这一特权表现为由政治官僚分配国民收入、规定工资、指导经济发展方向、支配收归国有的及其他方面的财产一种专门到权利和党的垄断权。所以在一般人看来，共产主义国家的官僚很富有，而且不用做工的人。
 
由于许多原因，私人财产所有权已经证明对于这个新阶级的权威的树立是不利的。此外要改变国家经济，就必须毁灭私人所有权。这个新阶级是从集体所有权这一特殊的所有权形式取得其权力、特权、意识形态和行事习惯的，他们以国家和社会的名义来行使并分配这种所有权。
 
这个新阶级认为所有权导源于一种特定的社会关系。这便是垄断行政大权的人（他们构成一个狭隘、门户紧闭的阶层）与没有权利的生产群众（农民、工人和知识分子）间的关系。然而，这种关系并不发生效力，因为共产党官僚还有支配物质的全权。
 
垄断行政权的人和生产者之间的社会关系的任何基本变化，都不可避免地反映在所有权的关系上。在共产主义制度下，社会、政治关系同所有权制度（政府的极权和权利的垄断）被更加充分地融合在一起，这是其它任何一种制度都望尘莫及的。
 
剥夺共产党人的所有权，就等于把他们这个阶级消灭掉。强迫他们放弃他们的其他社会权利，使工人可以分享利润（由于罢工和议会行动的结果，资本家们已不得不同意这一点），那就等于是剥夺了共产党人对于财产、意识形态和政府的垄断权。这将是共产主义制度下民主和自由的开始，是共产主义的垄断主义和极权主义的告终。在发生这种变化之前，就不能表明共产主义制度在发生重要的和基本的变化，至少那些认真考虑社会进步问题的人是这样看的。
 
这个新阶级和新阶级成员所拥有的所有权方面的特权就是行政特权。这类特权从国家行政和经济企业的行政一直伸展到体育、慈善机构的行政。政治的、党的或所谓“总的领导”，是由这个阶级的核心执行的。领导地位就包含着特权。奥罗夫(Orlov)在他的《斯大林时代》（“Stalin au pouvoir”，1951年在巴黎出版）一书中称，苏联的一个工人在1935年的薪金平均一年是1,800卢布，而一个人造丝委员会秘书的薪金和津贴则每年高达45,000卢布，后来，虽然工人和党的工作人员的情况都有所变动，不过它的本质依然没有改变。其他的作者也得到相同的结论。工人和党的工作人虽的薪金有天渊之别，这不可能瞒过最近几年访问过苏联及其他共产主义国家的人。
 
其他的制度也有它们的职业政客、不论你认为他们是好是坏，他们必然存在。社会不能离开国家或政府而存在，因此，社会也不能离开那些为它奋斗的人而存在。
 
然而，其他制度中的职业政客与共产主义制度中的政客之间却有基本上的差别。就极端的例子说，其他制度中的政客利用政府为他们自己和他们的同僚取得特权，或者照顾某一个社会阶层的经济利益。共产主义制度下的情况则完全不同，在共产主义国家中，权力和政府同国家的几乎一切财物的使用、享受和支配是一回事。掌握权力的人就握有特权，并间接地掌握着财产。因此，在共产主义制度下，那些想牺牲别人而让自己过寄生虫生活的人，就是以权力或政治作为一种职业。
 
在革命前，共产党的党籍是表示一种牺牲，做一个职业革命家是一种无尚的光荣。而现在，党的权力已经巩固，党籍就表示属于一个特权阶级的人，而党的核心人物就是掌握全权的剥削者和主人。
 
共产主义革命和共产主义制度曾把它们真正的性质隐瞒了一段很长的时期。社会主义的术语，而更重要的是财产所有权的新的集体形式，曾掩饰了新阶级的出现。其实，所谓社会主义所有权不过是真正的政治官僚所有权的假面具。并且，起初这个官僚集团忙于完成工业化，而把它的阶级成分隐藏在假面具里。
 
四
现代共产主义的发展，以及这个新阶级的出现，从那些推动这两件事的人的性格以及他们所扮演的角色来看，是很明显的。
 
从马克思到赫鲁晓夫，共产党的领袖以及他们所用的方法都各不相同，而且在不断更易。马克思从未阻止别人发表他自己的观念。列宁容忍党内的自由讨论，并且没有想到党的集会，更不用说党的领袖，应该规定谁的意见“适当”或“不适当”。斯大林则废止一切形式的党内讨论，并且规定只有党中央，或者说他自己，有权就意识形态发表意见。其他的共产主义运动就不同。例如，马克思的国际工人协会（即所谓第一国际），并不是以马克思主义为意识形态，而是一个许多团体的联盟，只采纳大家所同意的决议案。列宁的党是使内部的革命道德和单一的思想结构同某种民主结合起来的先锋队。在斯大林的领导下，党变成了一群对意识形态没有兴趣的人，他们的思想全是从上级得来的，可是，他们却全心全意地一致维护那保证他们享有无可置疑的特权的制度。实际上，马克思并未创造一个党：列宁摧毁了包括社会党在内的所有其他的党，只留下了他自己的党。斯大林甚至把布尔什维克党降了一级，把党的核心转变为新阶级的核心，并把党转变为无人性的和没有生气的特权集团。
 
阶级的作用和社会中阶级斗争的作用本身虽然不是马克思发现的，但他创造了一套关于这类作用的学说，他还认为，人类大多数是由阶级身份分明的成员构成的，虽然在这一点上他只是在重述特伦斯( Terence)的禁欲派哲学：“我知道人类的一切事物。”列宁认为，人们都各有其观点，而不把人看作阶级身份分明的成员。而在斯大林看来，人不是听命的臣仆，就是敌人。马克思作为一个穷困的侨民死于伦敦，不过有学问的人看得起他，他在共产主义运动上也受重视，列宁是作为历史上最伟大的革命之一的领袖而逝世的，但同时他也是一个独裁者，那时人们已经开始把他捧成一个偶像，当斯大林逝世时，他已经把他自己变成一个神了。
 
这些人的性格上的转变不过是早已发生的转变的反映，并且正是共产主义运动灵魂的改变。
 
尽管列宁并未意识到，但组成新阶级这件事却是由他开始的。他根据布尔什维克路线建党，并且发展了关于党在建设新社会中的特殊作用和领导作用的理论。这不过是他从事的多方面的巨大工程的一个方面；这是出自他的行动而并非出白他的心愿的一面。这也是导致新阶级敬爱他的一面。
 
然而，这个新阶级真正的直接创始人却是斯大林。他是反应迅速而好弄粗俗幽默的人，受教育不多，也不善于词令。不过，他却是一个无情的教条主义者和伟大的行政家，他是一个格鲁吉亚人，他比谁都了解大俄罗斯的新权力将把这个国家带往何处。他以最野蛮的手段创造这个新阶级，甚至对这个新阶级本身也不惜牺牲。这个阶级把他放在最高的地位，而后来就不免屈从于他那不羁而残暴的性格。当新阶级正在建立它自己并攫取权力时，他是这个阶级的真正领袖。
 
这个新阶级诞生于共产党的革命斗争时期，发展于工业革命时期。没有革命，没有工业，这个阶级的地位就不会稳固，其权力就会受到限制。
 
当苏联在推行工业化时，斯大林开始采用差异相当可观的工资制，同时，又听任各种特权继续发展。他认为，如果不让这个新阶级在工业化过程中对物质发生兴趣，使他们得到若干财产，这个运动就不会有任何成就。  没有工业革命，这个新阶级将会发现难以保持其自身的地位，因为既没有历史原因，也没有物质资源来维持它的继续存在。
 
党员，或者说官僚集团的成员人数的增加是和这一点有密切关联的。1927年，即工业化开始的前夕，苏联共产党共有党员887，233人。到1934年第一次五年计划结束时，党员已增加到1.874，488人。这是显然与工业化有关系的一种现象：这个新阶级的前途及其成员的特权都在渐入佳境。而且，特权和新阶级比工业化发展得还要快，  虽然很难举出统计数字来证明这一点，不过，如果有人记得下—事实，那末这个结论就不证自明了，这个事实就是生活水平跟不上工业生产，而这个新阶级实际上即已攫夺了由于群众的牺牲和努力而得来的大部分经济果实和其他方面的果实。
 
新阶级建立的过程并不顺利，它遭遇到既存阶级以及那些无法使现实与其所奋斗的理想调和的革命者的激烈反对。在苏联，革命者最显着的反对在斯大林和托洛茨基之间的冲突可以看得最清楚。随着工业化的进展以及这个新阶级的政治权力和经济特权的增加，托洛茨基和斯大林的冲突，或者说，党内反对派和斯大林之间的冲突，以及共产党政权与农民之间的冲突则愈来愈紧张。
 
托洛茨基是一位卓越的演说家，优秀的作家，熟练的辩论家，是一个很有修养而极有智慧的人，他仅缺乏一项品质；现实感。当现实已强烈要求进行平凡的工作的时候，他还要做个革命家。他希望复兴革命党，因为它正在变得面目全非，正在转变为一个不顾伟大理想而只关注日常生活享受的新阶级。当新阶级早已结实地掌握大权并开始尝到特权的甜头时，他却指望那早已疲于战争、饥饿和死亡的群众有所行动。托洛茨基的火炬照亮了遥远的天空：但是他不能再在疲倦的人间燃起烽火。他锐利地注意到新现象的悲惨面，但他没有了解它们的意义。再则，他从来不曾是一个布尔什维克。这是他的弱点，也是他的德行。在以革命的名义攻击党的官僚集团时，他攻击了党的偶像和这个新阶级，尽管他并没有意识到后者的存在。
 
斯大林既不看得太前也不看得太后。他把自己放在这个正在诞生的新权力——新阶级、政治官僚和官僚主义——的顶峰，变成它的领袖和组织者。他并不传道，他只作决定。他也许诺光明的未来，不过，他所许诺的只是官僚们认为眼光所能见的真实可靠的前途，因为他们的生活在天天改善，他们的地位在日益巩固。他的话既不热烈也不渲染，不过，这个新阶级比较能了解这种现实的语言。托洛茨基希望把革命扩张到欧洲，斯大林并不反对这个主意，可是，这种冒险举动总不免使他为他的祖国俄罗斯担忧，特别是为巩固新制度和加强俄罗斯国家的权力和威望的方法担忧。托洛茨基是旧日革命的人物。斯大林则是今天的，因而也是明天的人物。
 
在斯大林的胜利中，托洛茨基见到反对革命的、类似让法国革命中热月党式的反动，实际上也就是对苏维埃政府的腐败和革命目标的反对。他了解斯大林的卑鄙手段，并对此深为难受。托洛茨基是第一个发现当代共产主义本质而企图挽救共产主义运动的人，虽然他并不自知。不过，他并没有能彻底认清其面貌。他以为这只是一时的现象，是官僚集团的积弊腐化了党和革命，因而他的理论是：来个“宫廷革命”把上层变更一下就可以解决。然而，当斯大林死后“宫庭革命”确已发生的时候，我们可以看到共产主义的本质并没有任何改变，因为其中有些东西是比较根深蒂固、寿命经久的。斯大林的苏维埃热月党式的革命不只导致一个比以往政府更专制的政府的建立，并且还导致一个新阶级的建立。这是那个激烈的外国革命的延绩。这个革命已经不可避免地产生，而且使新阶级得到了巩固。
 
就像托洛茨基那样，斯大林至少有同等的资格倚仗列宁以及革命的一切。因为斯大林本是列宁和十月革命的合法后裔，虽然他为人狡黠。
 
列宁这样的人物是史无前例的，以他的多才多能与坚忍不拔创造出人类历史上几个最伟大的革命之一。斯大林这样的人物也是史无前例的。他在权力和财产方面担负起巩固新阶级的巨大工作，这个新阶级是从世界上最大的国家之一和最伟大的革命之一中产生出来的。
 
在充满热情和思想的列宁的背后，站着迟钝而灰暗的约瑟夫?斯大林，他是新阶级以艰难、残暴和不顾道德的方式取得政权的象征。
 
在列宁和斯大林之后，发生了必然要发生的情况：即集体领导形式所表现的平庸状态。并且貌似诚恳、善良而缺乏智力的“人民的人”尼基塔?赫鲁晓夫也来了。这个新阶级不再需要它曾经一度需要过的革命家或教条主义者了，它只要赫鲁晓夫、马林科夫、布尔加宁、谢皮洛夫这类简单的人物就够了，他们的一言一语都代表普通人。新阶级本身已厌倦于教条式的清洗和训练性的会让。大家都想活得平静点。这个新阶级已十分巩固了，它现在必须设法保护自身，甚至防范其所拥戴的领袖。当这个阶级还是很弱的时候，当残酷的手段还必须用来对付阶级内部的异己分子时，斯大林依然能高踞其领导宝座。如今，这一切都不需要了。这个新阶段丝毫未放弃斯大林领导下所创造的一切，可是，它看来却在否定斯大林过去几年中的权威。不过，它并不是真正在否定斯大林的权威，它所反对的只是斯大林的手段，这种手段在赫鲁晓夫看来是伤害“好共产党员”的。
 
列宁的革命时代为斯大林时代所代替，在斯大林时代中，权威、所有权和工业化都加强了，以致这个新阶级能开始其非常渴望的和平而舒适的生活。列宁的革命的共产主义被代以斯大林的教条的共产主义，接着，又被代以非教条的共产主义，即所谓集体领导或一群寡头政治的执行者。
 
这是新阶级在苏联发展的三个阶段，也是俄罗斯共产主义（或其他任何形式的共产主义）发展的三个阶段。
 
南斯拉夫共产主义的命运在于这三个阶段都集于铁托一身，不过附带着民族的及个人的特性而已。铁托是一个伟大的革命家，但没有创造性思想，他已经得到个人的权力，但没有斯大林的猜疑和教条主义。像赫鲁晓夫一样，铁托是人民的一个代表，那就是说，是党的中间阶层的代表。南斯拉夫共产主义所走的路线——从革命成功，模仿斯大林主义，直到否定斯大林主义并寻求自己的形式——是能完全从铁托的性格中看出来的。南斯拉夫共产主义比其他各国的共产党都更能首尾一贯地保持共产主义的实质，直到目前为止，它还没有否定过任何对共产主义的实质有价值的形式。
 
不论是就实质或观念而言，这个新阶级发展的三个阶段——从列宁、斯大林到“集体领导”——并不是完全彼此脱节的。
 
列宁也是一个教条主义者，而斯大林也是一个革命家，就像集体领导在必要时也将诉诸教条主义和革命手段一样。再则，集体领导的非教条主义原则的应用也只限于这个新阶级的巨头们本身。另一方面，人民依然得受教条“教育”，或者说，受马克思列宁主义的教育，而且比过去还要彻底。由于教条主义的严酷性和排他性的束缚已经放松，经济地位已经巩固的新阶级，在未来行动上已可望有较大的伸缩性。
 
共产主义的英雄时代是过去了。共产主义伟大领袖的时代已经结束。现实人物的时代正在开始，新阶级已经建立。如今它在权力和财富方面正处于巅峰状态，不过，它缺少新观念。它再没有什么东西可以向人民宣扬了。所剩下来的事，只是它为它自身辩护而已。
 
五
我们所以要在这里肯定这一事实，指出当代共产主义所蕴含的不只是临时的独裁和专断的官僚政治，而且一个享有所有权和具有剥削性的新阶级已经产生，完全是因为过去有些反斯大林主义的共产主义者，包括托洛茨基和一些社会民主党人在内，曾把统治阶层描述为一种过渡的官僚主义现象，认为这是那个尚在婴儿时代的理想的无阶级社会所必须忍受的折磨，就像资产阶般社会在克伦威尔和拿破仑的专制下不得不受蹂躏一样。这两回事必须分清。
 
这个新阶级确是一个具有特殊成分和特殊权力的新阶级。不论根据哪一个关于阶级的科学定义，甚至根据马克思主义的定义，即依照生产上的特定地位，某些阶级较其他阶级低，我们总可以得到一个结论；在苏联及其他共产主义国家中，一个作为握有所有权的人和剥削者的新阶级已经存在。这个新阶级的最大特色是它的集体所有制。共产主义的理论家断言，并且有些人甚至相信，共产主义已经达到了集体所有制。
 
在早先的一切社会中曾存在过各式各样的集体所有制。所有古代东方的专制制度都是甚于国家或者说国王的财产高于一切这一点。在埃及，直到公元前十五世纪后，可耕土地才变成私有物。在上远时期以前，只有住宅及四周的附属建筑物才归私人所有。国家的土地由国家官吏管理，分别佃给农民耕种而后课收租税，渠道与设备以及一切重要工程都属国家所有。直到公元第一世纪埃及失去其独立为止，  国土内的一切都属国家所有。
 
这一事实有助于我们了解埃及的法老以及古代东方各国的专制帝王何以受到人民的膜拜。这种所有权也使我们了解，像庙宇、陵墓、皇帝的城堡，以及运河、道路和堡垒等类的巨大工程何以能够修建起来。
 
罗马把新征服的土地当作国家的土地，并拥有相当可观数目的奴隶。中世纪的教会也有集体财产。
 
直到股份有限公司组织出现时为止，资本主义本质上就是集体所有制的敌人。尽管资本主义无法抗拒集体所有制活动区域的扩张以及它所造成的新的侵凌，但它今后依然是集体所有制的敌人。
 
集体所有制并不是共产党人发明的，不过，他们却发明了这一制度的包罗万象的特性：比以前时期的一切集体所有制都包罗得多，甚至连法老的埃及都赶不上。共产党人的发明仅此而已。
 
这个新阶级的所有权及其特性是经过一段时期才形成的，在这个过程中，它也在经常改变。起先，国内只有少数人觉得需要把全国的一切经济力量都集中在一个政党手里，以便有利于推行工业改革。作为无产阶级先锋队．及“最开明的社会主义力量”的党要求这种经济权力的集中，但这只有通过所有权的转变才能办到。这种改变在事实上和形式上首先是大企业的国有化，然后轮到较小的企业。可是，如果没有社会的管理者和财产
 
的分配者的特殊身份，共产党人就不能把他们自己转变为一个新阶级，这个新阶级更不能形成并长期存在。物资逐渐被收归国有，但事实上由于他们有权使用、享受和支配这些物资，于是所有的国家财产就成了党内某一个明显的阶层以及环绕这个阶层的官僚的财产。
 
鉴于所有权对其权力的意义（以及所有权本身果实的意   义），这批党官僚自然就连小规模的生产单位也不能放松，而也将它们收归国有。由于它所持的是政治极权主义与经济垄断主义，这个新阶级不免觉得凡在它控制和管理以外的东西都是作战的对象，因此一定要把它们摧毁或征服。
 
在农业集体化前夕，尽管苏维埃政府当时并没有遭到在政治上和经济上都很涣散的农民的严重反对，斯大林就说：“谁战胜谁”的问题已经被提出来了。只要国内尚有其他的有产者存在，这个新阶级就会感到惴惴不安。它不能冒食物供应或农业原料遭到破坏的危险。这是共产党要向农民进攻的直按理由。然而，还有第二个理由，这是有关阶级的理由：在不稳定的情况下，农民可能危害这个阶极。因此，这个新阶级不得不使农民在经济上和行政上同时处于从属地位；通过集体农庄和拖拉机站而达到了控制农民的目的。但这就需要新阶级的成员在农村中有所增加。结果，官僚也布满了农村。
 
由于夺取了其他阶级的财产，特别是小业主的财产，而导致的生产萎缩和经济混乱，对这个新阶级是没有影响的。像历史上其他的各种有产者一样，对这个新阶级最重要的事是所有权的获得和巩固。这个新阶级可从新取得的财产获得利益，尽管国家因此而受到了损失。如果新阶级要稳掌政治权力和经济所有权，农民财产的集体化就不可避免，虽然在经济上并不合算。
 
我手头并无可靠的统计数字，但所有的证据都证实，目前苏联每亩土地的平均生产量并没有超过沙皇时代俄国的生产量，家畜的头数还赶不上革命前的数量。
 
在农业生产和家畜上的捐失是能够计算的，而在人力上，在被送入劳动营的千百万农民身上的捐失是不可计算的。农业集体化是一场骇人的毁灭性战争，简直像一件疯狂的举动，唯一的好处是从此这个新阶级的权威有了保障。
 
通过国有化、强迫合作化、重税以及价格的不平等种种方法，私人所有制被毁灭而转变为集体所有制。从心理、生活方式、以及党员物质地位等的改变上，也可以证实这个新阶级所有权的确立，这些改变是由他们在权力阶梯上所占有的位置决定的。他们有的是郊外别墅，华厦美居，精巧的家具及其他的设备。最高级的官僚，这个阶级的精华，还有专用的居住区和特设的疗养院。某些地区的党书记和秘密警察首领不仅成为最高的权威，而且享有最好的住宅、汽车以及类似的特权。以下各级官僚则按地位的高低，分享各有等差的特权。国家的预算、“礼物”、为国家及其代表的需要而兴建或重建的建筑等，都是使政治官僚们受惠的取之不尽的源泉。
 
只有当新阶级无法维持它所篡夺的所有权时，或这种所有权的代价太大，或者有政治性危险时，新阶级才不得不将所有权转让给其他阶层，或者制造出其他所有权形式。例如农业集体化在南斯拉夫被放弃了，这是因为农民抗拒集体化，而且因为集体化引起的生产逐步下降构成了共产丰义政权的潜在危机。然而，在这种种情况下，新阶级从未放弃它再度攫取所有权或重新实行集体化的权利。新阶级不能放弃这种权力，因为如果它放弃了这种权力，它就不再具有极权主义和垄断主义的性质了。单是官僚政治就不会如此顽固地坚持其目标。只有掌握新形式的所有权并沿此途径趋向新的生产形式的人，才会如此固执。
 
马克思早就预知，无产阶级在胜利后将会遭遇到从被推翻的阶级和它自己的官僚方面来的危险。当共产党人，特别是南斯拉夫的共产党人，批评斯大林的行政与官僚方式时，他们通常都援引马克思的先见。可是，当今发生于共产主义国家的一切与马克思很少有关联，当然更与此项先见无关。马克思曾想到寄生的官僚膨胀的危险，这也是出现于当今共产主义国家中的事实。但他从未想到，今日共产党人中的有力人物就是他所想到的官僚，他们在经管并支配物资时，为自己小集团的打算实有过于为整个官僚阶层的打算。在这种情况下，不论是批评这个新阶级中的各阶层的浪费奢华或者行政不良，共产党人总全把马克思作为一个很好的借口。
 
当今共产主义制度并不只是某种类型的政党，或从垄断性所有权及国家对经济作过分干预中产生出来的官僚集团。  最重要的是，当代共产主义最主要的一面，是这个所有者兼剥削者的新阶级。
 
六
尽管一个阶级的得势是有组织地进行的，而且还伴随着自觉的斗争，但没有一个阶级单是由自己的行动确立的。共产主义制度下的新阶级也是如此。
 
因为新阶级同经济和社会结构的关系微弱，并且因为它必然发源于一个政党中，所以这个新阶级就不得不尽可能建立其有组织的结构。最后，它又不得不从早年的教条中作有计划和有意识的撤退。因此，这个新阶级在组织上和阶级意识上比历史上任何阶级都高。
 
当然这种说法只是相对说来有它的真实性：意识和组织结构是必须就它与外在世界及其他阶级、权力和社会力量的关系联系起来看的。在历史上，没有任何阶级在保卫自己并控制其所掌握的一切时——集体和垄断性质的所有权与极权的行政权力——是如此团结和一心一意的。
 
而在另一方面，这个阶级也是最自欺的、最不自觉的。每一个资本家或封建地主都自觉他是属于某一个特定社会阶级的。他通常还相信他这个阶级是注定要使人类快乐的，并且相信，如果没有这个阶级，混乱和毁灭就会跟着来。这个新阶级的共产党员也相信，没有他的党，社会将要倒退和解体。不过，他并不认为他属于一个新的所有权阶级，因为他并不认为他自己是有产者，因而，也不承认他享受什么特权。他以为他只属于一个具有限定的观念、目的、态度和任务的团体。他所看到的就只是这些。他看不出他同时也属于一个特定的社会阶级：所有权阶级。
 
集体所有制的作用在于削弱阶级，同时，使这个阶级不感觉到它的阶级实质，并且，集体所有者中的每一个人都以为自己是独特地属于一个将废除社会各阶级的运动。
 
拿这个新阶级的其他特性与其他所有权阶级一比，我们就会发现他们之间有许多相似之处和不同之处。这个新阶级是贪婪的而不能满足的，就像资产阶级一样。不过，它并无资产阶级所具有的朴素和节俭的美德。新阶级的排斥异己正像贵族阶级一样，但没有贵族阶级的教养和骑士风格。
 
这个新阶级也有胜过其他阶级的优点。因为它的内部比较团结，所以它比较能够作较大的牺牲并取得辉煌成就。个人完全服从整体；至少，现有的理想要求他们这样做，甚至在向外自寻较好出路时也得服从整体。这个新阶级有足够力量去从事物质的及其他方面的冒险，那是其他阶级从不能办到的。由于它占有全国的物资，这个新阶级能够为它所标榜的目的作宗教性的奉献，并且指挥人民的全部力量来促使达到这些目标。
 
这个新的所有权并不就是政府，但它是由那个政府创造并得到那个政府的帮助的。财产的使用、享受和支配是党以及党的领袖们的特权。
 
党员们觉得，他们的特权是与权威和控制财产权一起来的。于是，野心勃勃，口是心非，奉承和嫉妒必然日见增加。追求地位和官僚集团的膨胀是共产主义的不治之症。因为共产党人已把他们自己转变为有产者，并且因为只有通过对党，对这个阶级，对“社会主义”表示“忠诚”，才能取得政治权力和经济特权，于是，野心勃勃就成为主要的生活方式之一，也是发展共产主义的主要手段之一。
 
在非共产主义制度中，追求地位和野心勃勃是身为官僚必有好处的标记．或者，那就表示有产者己变为寄生分子，因此财产的管理得交给雇员。在共产主义制度中，追求地位和野心勃勃所证明的事实是：那儿有一股不可抗拒的力量驱使官僚们争取所有权和特权，也就是争取物资和人的管理权。
 
在其他的掌握所有权的阶级中，阶级成员并不等于是某项特定财产的所有人。而在共产主义制度中，所有权既是集体的，其情形便不是如此。要在共产主义制度中成为一名有所有权的人或有集体所有权的人，只要他进入政治官僚的统治集团就够了。
 
在这个新阶级中，就像其他的阶级一样，经常有人跌下去，同时有人爬上来。在有私人所有权的阶级中，个人把财产留给他的子孙。在这个新阶级中，除了希望后人能向上爬以外，什么财产都传不下去，这个新阶级实际上是不断地从最底层和最广大的人民中建立起来的，而且它经常在变动。尽管在社会学理论上能指明谁属这个新阶级，但事实上却很难这样做：这个新阶级是渗入在人民中，渗入在其他低层阶级中的，它是经常在变的。
 
在理论上人人有机会爬到顶峰，就像每一个拿破仑的士兵都在他的背囊上带有一根将军的指挥棒一样。走向上进之路的唯一条件是对党和新阶级的忠诚和绝对效忠。新阶级底层的大门是敞开着的，但愈往上去则愈窄狭。想向上爬的人不只要有欲望，还需要有了解和发扬教条的能力，在对敌斗争中坚定不移，在党内斗争中要有无比的机灵与聪明，而且还得有巩固阶级的才能。许多人在这些方面力求有所表现，但被选中的只有极少数。虽则新阶级在某些方面对局外人的开放有过于其他阶级，但它的门禁比别的阶级更为森严。由于这个新阶级的最重要的特质之一是权威的独占，所以这种排他性因官僚体统的偏见而加强。
 
不论在何时何地，忠诚的人从来没有享有较在共产主义制度下更宽的出路。但是，爬到顶层的困难也是以共产主义制度为最甚，从来没有一个制度要竞争者作这样多的牺牲，需要有这样多的殉难者。一方面，共产主义显得宽大仁厚，而另一方面，共产主义则甚至对自己的党徒也会排斥和不容忍。
 
七
共产主义国家中有一个新的所有权阶级并不能解释共产主义国家的一切，不过，这是了解共产主义国家中，特别是苏联，定期发生的变化的最重要的关键。
 
这并不是说，为了确定在特定环境中所发生的变动的影响范围和意义，对于各别共产主义国家中以及整个共产主义制度所发生的每一种变动必须分开来研究。可是，要了解各个变动的影响与意义，必须尽可能把这个制度当作一个整体来研究。
 
指出当年发生于集体农庄的事将帮助我们了解苏联最近的变动。集体农庄的建立与苏维埃政府对它们的政策清清楚楚地说明了新阶级的剥削本质。
 
斯大林并不认为集体农庄是“合理的社会主义”所有制形式，赫鲁晓夫也如此。集体农庄的存在，正表示这个新阶级没有能把农村的管理权完全夺过来。通过集体农庄和强迫收购粮食的制度，新阶级已使农民处于从属地位，并且抢走了农民收入的大部分，不过，新阶级还未能全权控制土地。斯大林完全明白这，一点。在他死前，他曾在《苏联社会主义经济问题》一书中推测集体农庄应让变为国家财产，那就是说，官僚应该成为集体农庄的真正的所有者。尽管赫鲁晓夫批评斯大林滥行清洗，然而，他并不否定斯大林对于集体农庄财产权的意见。赫鲁晓夫上台后，派了三万名党的干部，它们大部分都任集体农庄的主席，这不过是追随斯大林政策的措施之一。
 
就像斯大林统治下的政权一样，赫鲁晓夫新政权在执行所谓自由化政策时，实际上就是在扩强这个新阶级的“社会主义的”所有权。经济权力的分散并不表示所有权的变动，只是给与新阶级的低级官僚阶层以较大的权利。  如果所谓自由化政策和经济权力的分散还有什么其他意义，那就是在政治权利上，至少有一部分人民可以对物资的处理发生一些作用。至少，人民将有权批评寡头政权的专断。但这就会引起一种新的政治运动的出现，虽然它不过是一种忠贞的反对派而已。然而，这一点现在甚至还没有人提起，就像还没有人提起党内民主一样。自由化和分权的有效范围只及于共产党员，首先是及于寡头集团，即这个新阶级的领袖们，其次才惠及较低的干部。这是适应变动中的环境而必然产生的新方法，是为了进步加强并巩固新阶级的独占所有权和极权的行政权。
 
在共产主义国家存在着一个新兴的、享有所有权的、垄断性的极权阶极，这一事实就导致如下的结论：凡是共产党的首脑所倡导的改变，首先是取决于新阶级的利益与愿望；像其他的社会集团一样，新阶级的一举一动，或守或攻，都带有增强其权力的目的。然而，这并不是说，这类变动对其余的人民就不是同样的重要。尽管这新阶级本身所主动要求的变化尚未在实质上改变共产主义，但这些变化的意义却不能低估。为了确定这些变化的范围和意识，我们必须对它们的实质有深入的认识。
 
像其他的政权一样，共产党的政权必须考虑到群众的心境和动向。由于共产党的排他性以及党内自由舆论的缺乏，这个政权就无法察觉群众的真正情况。然而，共产党高级领导人也深知他们的不满。尽管这个新阶级已把持了管理权，但它并不能免于遭受各种形式的反对。
 
一经取得政权，共产党就轻而易举地把资产阶级和大地主收拾掉。历史的发展对他们以及他们的财产不利，因而唤起群众反对他们也是容易的事。没收资产阶级和大地主的财产十分容易，可是当没收小规模的财产时，就有困难了。共产党人既在早先没收财产的过程中取得了权力，所以对于这一困难也是能克服的。于是社会关系很快就澄清了，旧的阶级和以往享有所有权的人都没有了，社会已“没有阶级”了，或者说正在走向“没有阶级”的社会，而且人们已经开始以新的方式生活了。
 
在这些情况下，要求恢复革命前的关系，如果不是可笑的，也是不现实的。维持旧关系的物质基础和社会基础已不复存在。共产党人把这类要求只当作是笑话而已。
 
这个新阶级对于人民要求某一特种自由最为敏感，对于要求一般自由或政治的自由则不然。它对于在现状之下和在“社会主义”的范围内要求思想自由与批评自由也特别敏感；当然对于恢复从前的社会关系和所有权关系的要求却充耳不闻。这种敏感是由这个阶级的特殊地位产生的。
 
这个新阶级本能地觉得，国家的物资事实上本是它的财产。甚至也觉得“社会主义的”、“社会的”、“国家的”财产这些名词不过是一般法律上的空洞字眼而已。这个新阶级还认为，其极权权威任何一方面的肢解都可能危及它的所有权。所以这个新阶级反对任何形式的自由，表面上是为了保持“社会主义的”所有权。对新阶级垄断财产管理权的批评引起了一种恐惧，它怕可能就此失去权力。这个新阶级对于这方面的批评和要求的敏感，由它们对新阶级统治与行使权力的态度揭露到什么程度而定。
 
这是一个重要的矛盾，财产在法律上被认为是社会的和国家的。但实际上却由一个小集团为了自己的利益而加以经管。名实不符的情况不断地造成模糊不清的、不正常的社会和经济关系。这也就是说，领导集团是言行不符的，他们的全部行动就在于巩固其财产所有权和政治地位而已。
 
如果不危及这个新阶级的地位，这个矛盾是不能解决的。其他的统治阶级和有产阶级也不能解决这种矛盾，除非以强力剥夺其独占的权力和所有权。如果整个一个社会有较高度的自由，统治阶级就会被迫以种种方式放弃其对所有权的独占。这句话倒过来说也是对的：当独占所有权成为不可能时，某种程度的自由也就必然会出现。
 
在共产主义制度下，政权和所有权几乎总是由同一集团掌握，不过，这个事实竟被法律的面具所隐蔽。在古典的资本主义下，尽管工人是被剥削者而资本家是剥削者，但在法律面前，工人和资本家是平等的。在共产主义制度下，在法律上说，物质方面的权利是人人平等的。形式上的所有者是国家。但在实质上，由于行政权的垄断，只有极狭小的行政者阶层享有所有权。
 
在共产主义制度下，对自由的任何真正要求，任何一种击中共产主义本质的要求，归根结蒂就在于要求物质和财产的关系符合法律的规定。
 
国家所生产的主要物资由社会经管要比由私人垄断或由个人私人所有者经管更为有效，因此国家的主要物资就应该交社会控制，并由通过自由选举产生的代表去行使控制权。基于这一观点所提出的要求必将迫使新阶级采取行动，不是对其他的势力让步，便是悍然丢掉假面具，承认其统治和剥削的特质。这个新阶级运用权威及行政特权而创造出来的所有权和剥削方式，是一种连这个阶级自己也不敢承认的体制。这个新阶级岂不是在强谓，它以整个国家的名义运用权威和行政职权都是为了保存国家财产吗？
 
这使得这个新阶级的法律地位不稳定，并且这也是新阶级最大的内在困难的来源。这一矛盾暴露了新阶级的言行不符：它一面许诺废弃社会差别，  —面却又必须不断地夺取国家工厂的产品并赐予其党徒以种种特权，来增加社会的差别。这个阶级虽然不得不大声宣扬其教条，说它正在完成历史使命：“一劳永逸”地把人类从不幸与灾难中解放出来，而在实际上则恰恰反其道而行。
 
这个新阶级的真正的所有权地位和其法律地位间的矛盾是最引起批评的基本原因。这个矛盾不只会招惹他人的批评，而也引致该阶级内部的不满，因为实际上真正享有特权的只是极少数几个人。当这种矛盾紧张时，不管统治阶级愿意与否，就有促使共产主义制度真正改变的可能性。这个矛盾太明显了，这一事实迫使新阶级不得不作一些改变，特别是像所谓自由化和权力分散一类的改变。
 
这个新阶级之所以肯被迫而对个别阶层作一些退让，其目的无非是遮盖这个矛盾并巩固其地位。由于这些让步依然无损于它的政权和所有权，新阶级所采取的措施，甚至包括那些含有民主色彩的措施在内，都显示其加强政治官僚治理权的倾向。共产主义制度已把民主措施转变为巩固统治阶级地位的积级手段。在古代的东方各国，奴隶制度不可避免地渗透到一切社会活动和社会成分中，连家庭也不能例外、同样地，在共产主义制度下，就治阶级的垄断主义和极权主义也深入社会生活的各个方面，尽管其政治首脑并无意如此。
 
南斯拉夫所实行的所谓工人管理和自治，是在进行反苏维埃帝国主义斗争期间想出来作为剥夺党垄断行政权的影响远大的民主措施，现在已日益成为党的工作的一部分了。所以要改变现有的制度几乎是不可能的，想通过这种类型的行政来创造一个新的民主制度是办不到的。此外，也无法把自由给予大多数人。工人管理并未能使生产者自享其生产的利益，在国家的层次上未分到，在地方企业单位层次上也未分到。这种形式的行政制度已日益成为保障这个政权的可靠形式。通过各种赋税及其他方法，这个政权甚至榨取了工人所认为应该分给他们的利润。留下给工人的只是桌上剩下的面包屑和幻想。如果没有普遍的自由，那末即使工人自行管理也是不能带来自由的。显然，在一个不自由的社会中，没有人能自由地决定任何事。当施予者好像是把自由当礼物送给工人时，最大的受益者还是施予者自己。
 
这并不是说这个新阶级不会对人民让步，尽管它只考虑自己的利益。工人管理或权力分散就是对群众的一种让步。不管它是如何垄断和如何极权，环境可以驱使这个新阶级在群众面前退却；当1948年南斯拉夫和苏联发生冲突时，南斯拉夫的领袖们被逼执行一些改革。尽管可以说这是一种退一步的做法，可是当他们见到自己的危机时，他们就着手改革。今日东欧国家也正在发生着类似的变革。
 
为了维护其政权，每当情势明显到使人民能看出这个新阶级正在把国家的财产当作自己的私有物时，这个统治阶级不得不从事改革。他们并不把这些改革的真相宣布，而是把这些改革说成“社会主义进一步发展”和“社会主义民丰”的一部分。当上述的矛盾大白时，改革的基础就奠定了。从历史的观点看，尽管这个新阶级一直在逃避事实，但它总是经常地被迫保卫其政权和所有权。它必须经常地证明，它是如何成功地创造着一个幸福人民的社会，人人都享有平等权利，并且已经废除了一切形式的剥削。这个新阶级不免经常地陷入内部矛盾的深渊：因为不管其历史根源如何，它总不能使它的所有权合法；同时，它又不能放弃所有权而毁灭自身。因此，它总是被迫假借抽象而不真实的目的来为它日渐增长的权威辩护。
 
这是历史上前所未有的对人民控制得最全面的一个阶级。正因为如此，这是一个最缺乏真知灼见的阶级，  它的观点是假的，靠不住的。当新阶级力量充沛、大权在握时，它必然对它自己的作用以及它周围人民的作用作不真实的估价。
 
在工业化完成后，这个新阶级除了加强其暴力统治并洗劫农民外，就无事可为了。它不再创造了。它的精神传统已被黑暗所替代。
 
虽然这个新阶级完成了革命中最伟大的一次胜利，但其统治方式却是人类历史上最可耻的篇章。后人将赞叹这个阶级所完成的宏伟的冒险，同时，也将为它在完成其冒脸事业时所用的手段而感到羞耻。
 
当这个新阶级退出历史舞台时——这一天是必然要到来的——人类对于它的逝去将比对以往其他阶级的逝去更少有惋惜之感。除开利己的东西外，使一切都窒息而死，因此它就必然会使自己遭到失败和可耻的毁灭。

第四章  党的国家
一
尽管共产主义的权力机构导致世界上最巧妙的暴虐统治和最残酷的剥削，但它或许可以说是最简单的权力机构。它之所以简单，是由于整个政治、经济及意识形态活动都以共产党一个党做骨干。整个国家的公共生活是停滞或前进，是倒退或转向，完全由党的会议决定。
 
在共产主义制度下，人民可以迅速地领悟到，他们许可做什么，不许可做什么。法律和条例对他们并没有根本的重要性。有关政府和人民间的关系的实际和不成文的规则反而重要。不管法律怎么说，每一个人都知道，政府是在党委员会和秘密警察手中。虽然并没有明文规定党的“指导作用”，但党的权威则及于一切组织和地区。没有一条法律曾规定秘密警察有权控制人民，但是，警察握有一切大权。没有一条法律规定司法官和检察官应该受秘密警察和党委员会的控制，但他们事实上是受控制的。绝大多数人民都知道这一事实。任何人都知道，什么能够做，什么不能够做，以及某些事由谁决定，另一些事又由谁决定。人民只是适应环境和实际情况一切重要事务唯党会议或由党控制下的机构的马首是瞻。
 
对于社会组织和社会机构的指挥都是用以下的简单方法：共产党员构成一个党组，这个党组在一切问题上都听命于授权的政治会议。这是理论上如此，实际上是照下列方式进行的：当管理社会机构或社会组织的人在党内也有地位时，在许多较小的事务处理上，他就可以独断独行。共产党人已熟悉党的制度以及党所创造出来的关系,他们已习惯于裁夺事务的重要与不重要，只有在特别重要的事务上他们才诉诸党的会议。党组的存在只是备而不用，重要的事由党决定，选出政府或某些组织的管理机构的选举人的意见完全不重要。
 
当共产党准备从事革命时，共产主义的极权主义和新阶级就早已生根了,共产党人执行和维持权威的方法也发源于革命时代。在政府机关和社会组织中起“指导作用”的就是从前的党小组，只是后来它已经扩大，发展和健全了起来。党在“社会主义建设”中所负的第二个“指导作用”就是关于党在工人阶级中的“先锋作用”这个陈旧的理论，所不同的只是这一理论对当时社会的意义与目前有所不同。在共产党人夺得政权前，这一理论是号召人们参加革命并建立革命机关所必需的；现在却成了这个新阶级作极权统治的借口。甲起源于乙，但两者却不相同。革命和革命的形式是不可避免的，而对于迫切向往工业与经济进步的人说，甚至是需要的。
 
在革命时期形成的这个新阶级的极权暴政和控制，如今已变成了驱使全民流血流汗的桎梏。特别的革命形式已转变为反革命的形式。党小组也是如此。
 
共产党人用以控制杜会机构的基本方法有二。第一是党组，这是原则上和理论上的主要方法。第二是政府机构中的某些职务只许由党员担任，这是实际上常用的方法。这些职务包括警察，特别是秘密警察人员，还有外交官员和军官，特别是负责情报并作政治活动的人员等，这些职务在任何制度的政府中都极为重要，但在共产主义国家的政府中却尤其重要。早先，在司法机构中，只有最高的位置才由共产党人担任，因为司法机构从属于党和警察机构，通常待遇都很低，所以对共产党人没有吸引力。可是，目前的趋势却是司法行政人员的职位被视为只有党员才许充任的一种特权，他们的特权也在增加。因此，今后对司法部门的控制如不完全解除，至少也会放松；因为他们已可放心，司法部门将根据党的意志或“社会主义精神”行事。
 
只有在共产主义国家中才把若干专门的和非专门的职位保留给党员。共产主义国家的政府虽然是一个阶级机构，实质上就是党的政府；共产主义国家的军队就是党的军队，而国家也就是党的国家。更确切地说：共产党人有意把军队和国家当作他们的专用工具。
 
只有党员才能任警察、军官、外交官及类似的重要职位，或者只有党员才能真正行使权威，这是共产主义国家特有的不成文法，于是一种特殊的享有特权的官僚集团被制造出来了，政府和行政机构也因此而单纯化了，这样，党组便扩大了，并且或多或少地包罗了上述各项工作，结果，既然这些工作已成为党的活动的主要领域，党组也就消失了。
 
在共产主义制度下，政府机构和党组织之间并没有基本的差别，党和秘密警察的关系便是例证。在他们的日常活动中，党和警察紧密地混在一起，两者的差别只在于所分配的工作不同。
 
整个政府结构都是以这种方式组成的。政治职位完全保留给党员。甚至在非政治性的政府机构中，共产党人也占有当权地位或者负有监督之责。党中央召集一次会议或者发表一纸文告就足以推动整个国家和社会机构。如果有任何地方发生困难，党和警察就会很迅速地纠正“错误”。
 
二
共产党的主要特质已经讨论过了。此外，还有一些其他色有助于对共产主义国家本质的了解。
 
共产党所以有其独特的性质并不只是因为它是革命的，中央集权的，遵守军纪的，以及其他确定的目标，或有什么别的特性。其他政党也有类似的特色，虽然共产党的特色要比它们强烈些。
 
然而，唯有共产党要求其党员必须具有“意识形态的统一”或在世界观和社会发展的观点方面具有一致的看法。这只是限于有资格出席高级会议的党员，至于低级干部，则只需在执行上级的命令时对统-的意识观点尽口头传达的义务。然而，趋势却是要下级干部调整理论水平，以符合领导人物的思想。
 
列宁并不认为党员都应持完全相同的观点。而事实上，他却驳斥和反对一切看来不是“马克思的”或“党的”观点；那就是说，凡是不能以列宁原先所设想的方式强化党的观点都在被驳斥之列。但是，他对付党内反对派的态度和斯大林不同，因为列宁并不杀害他的下属，而“仅仅”压服他们。在他当权时，党内言论自由和选举自由是存在的。至高无上的权力当时还没有确立。
 
斯大林在要求全体党员具有作为共同基础的政治上的统一以外，还强迫要求全体党员在意识形态上一致（包括强迫的哲学思想及其他思想）。实际上这是斯大林对于列宁有关党的学说的贡献。早在斯大林的青年时代，他已形成强迫意识形态一致的观念：在他当政时，划一性是所有共产党的不成文的必要条件，并且一直到现在还是如此。
 
南斯拉夫的领袖过去和现在都是抱着同样的观点。他们依然受苏维埃“集体领导”和其他各国共产党会议的影响。这种坚决不肯放弃党的强迫思想统一，正说明根本变化还没有发生，而是证实了在今日的“集体领导”下，自由讨论根本不可能，或者说只能限于极其有限的范围内。
 
在党内强迫实行一致的意义何在？它将导向何处？
 
强迫一致的政治后果是严重的。任何政党的权力都是在领袖和高级党代表会议下中，共产党尤其如此。意识形态的一致既作为是一种必需条件，特别是在中央集权和党纪严如军纪的共产党中，就必然会以党中央的权力控制党员的思想。尽管在列宁时代，意识统一的达成是通过党的高级领导人的会议，但斯大林却要由他自己规定。如今，斯大林死后的“集体领导”满足干使新的社会观念不可能产生。这样，马克思主义就变成了一种专由党的领导人来解释的理论。今天已经没有其他类型的马克思主义或共产主义，其他类型的发展几乎是不可能的了。
 
意识形态统一的社会影响是悲惨的；列宁的独裁是严峻的，而斯大林的独裁却形成极权。取消党内一切意识形态的斗争，无异是社会上一切自由的终结，因为只有通过党，社会各个阶层的意见才得以表达。不容其他思想的存在并且武断地假定马克思主义独有的科学性，就是党的领导垄断意识形态的开始，并终于发展为对整个社会思想的垄断。
 
党内意识形态的一致，使得共产主义制度内以及社会本身以内都不能产生独立的运动。一切行动都依靠党，因为党对社会的控制是全面的,在党内连丝毫自由也没有。
 
像共产主义制度中的其他一切现象一样，意识形态的一致并非突然出现，而是逐渐发展起来的，而且在党内各宗派争权期中达到最高峰。在二十年代中期斯大林上台的时候，便开始公开要求托洛茨基摒弃党规定以外的一切观念，这根本不是偶然的。
 
党内意识形态的一致是个人独裁的精神基础，没有意识形态的一致，个人独裁是不可想象的。意识形态的一致造成并加强个人独裁，反过来，个人独裁又造成并加强意识形态的一致。这是可以了解的，观念的垄断，或意识形态的强迫一致，只是个人独裁的补充条件和理论上的假面具。尽管个人独裁和意识形态的一致早在当代共产主义或布尔什维主义发端时已经显著，但现在，它们是和共产主义的整个权力牢固地建立在一起的，因此在共产主义灭亡前，不论作为将来的趋势或一般作为现行的形式，它们将永远不会被废弃。
 
对于领导人的意识形态分歧的压制，还使不同的派别和趋向消灭了，从而也毁灭了共产兑党内的全部民主。于是，共产主义中的“元首”原则的时代开始了，理论家只限于党内当权的人，不问它们有无足够的智力。
 
党内意识形态一致的延续是保持个人独裁或像今日苏联少数寡头独裁（数人暂时合作或保持权力平衡）的明确标志。在其他的党派中，我们也发现有要求党内意识形态一致的倾向，在早期的社会主义政党中，这种倾向尤为显着，然而，这毕竟只是这些政党中的一种倾向，但在共产主义政党中，意识形态的一致已变为强迫性。党员不只必须是一个马克思主义者，而且要采纳领导上所要求的和规定的某种类型的马克思主义。马克思主义已从一种自由的革命意识形态一变而为规定的教条。就像古代东方的专制制度一样，最高权威解释并规定教条，而帝王就是教条的主要宣扬者。
 
共产党的强迫意识形态一致虽已经过各种阶段和形式，但依然是布尔什维克党或共产主义政党最根本的特质。
 
假如这些政党并不同时又是新阶级的发端，假如它们并没有一定的历史角色去扮演，那末强迫的意识形态的统—也不会在它们当中存在。除了共产党的官僚集团外，在近代历史上，没有一个阶级或政党曾达到意识形态的完全一致。在以前，也没有一个阶级或政党的任务几乎完全是靠政治的和行政的手段来改变社会的一切。为了完成这样的任务，就必须完全而狂热地相信自己意识形态的正确与高贵。这样的任务也必然求助于残暴的手段以清除其他的意识形态与社会团体，也必然要求垄断社会的意识形态，并使统治阶级绝对团结一致。为了这个理由，共产党就需要超常的意识形态的统一。
 
意识形态的统一一旦建立，其为害之烈犹如偏见。共产党员所接受的教育是：意识形态的统一或由上级规定意识形态是神圣中的神圣，而党内的宗派主义是最大的罪恶。
 
如果不同其他社会主义团体妥协，就不能完全控制社会。同样，如果党内不妥协，就不可能达成意识形态的统一。这两者差不多同时发生：在极权主义信徒的心目中，它们是“客观地”一致的，殊不知前者的获得是这个新阶级与它的反对势力妥协的结果，而后者的达成是统治阶级内部妥协的结果。事实上，斯大林明白，托洛茨基、布哈林、季诺维也夫等人并不是外国的间谍和“社会主义祖国”的卖国贼。可是，他们与他的意见的不一致显然延误了极权控制的建立，所以他必须把他们摧毁掉。他在党内的罪恶是他把“客观的不友善”——党内思想意识上和政治上的分歧——转化为团体与个人的主观罪行，给他们加上他们并未犯的罪名。
 
三
但这是任何共产主义制度必然要走的道路。建立极权控制或意识形态统一的方法可能不如斯大林严厉，但在本质上总是一样的。甚至，像在捷克斯洛伐克和匈牙利这些国家中，它们的工业化并不是建立极权控制的那种形式和条件，但共产党官僚仍不免被迫在这些落后国家中建立同样形式的权威。正像在苏联所建立的那样。这并不单单是由于苏联把这些国家当附庸国而将这些形式强加在它们的头上，而且也是由于共产主义政党及其意识形态的本质使它们不得不这样做。党对社会的控制，政府、政府机构和党的三位一体，党员发表意见的权利取决于它在特权阶级中所握的实权和所任的职位，这些都是任何共产党官僚集团当权时必有的根本特质。
 
党是共产主义国家和政府的主要力量。党是一切的动力。党把新阶级、政府、所有权和思想意识在它的内部统一起来。
 
因此，在共产主义制度下，军事独裁是不可能的，尽管看来苏联已经发生过军事阴谋。军事独裁将不能控制人民生活的全面，甚至不能暂时说服整个国家需要作例外的努力和牺牲自我。这些事只能由党来完成，并且也只能由坚信这样广阔理想的共产党来完成，这种广阔的理想使党员及其拥护者觉得专制是必需的，是国家和社会组织最高的形式。
 
从自由的角度来看，在共产主义制度下出现军事独裁就是一大进步。这将标志党的极权控制或党的寡头政治的结束。然而，就理论上说，军事独裁只有在军事上遭到失败或不寻常的政治危险发生时才可能出现。即使在这种情况下，它必先以党独裁的形式出现，不然，它就得借党做幌子而掩饰军事独裁的真面目，但是，这势必导致整个制度的改变。
 
在共产主义制度下，共产党寡头政治的极权独裁并不是一时政治关系的产物，而是一个长期而复杂的社会演变的结果。极权独裁的改变并不是同一制度下政府形式的改变，而是制度本身的改变，或者是这个制度改变的开始。这种独裁就是这个制度本身，就是这个制度的肉体和灵魂，也是这个制度的本质。
 
共产主义国家的政府很快就变为党的领导人的小圈子。所谓无产阶级专政早就变为一句空口号。造成情况的过程是随着种种因素的必然性和不可控制性而发展的，并且关于党是无产阶极先锋队这一论点只是加强了这种过程。
 
达并不是说，在夺取政权的斗争时期，党不是工人群众的领导者，也不是说当时党不曾为工人阶级的利益斗争。不过，在当时，党所扮演的角色和所从事的斗争只是党在夺取政权的过程中的各个阶段和形式。尽管党的斗争帮助了工人阶级，但它也加强了党和未来的当权者以及胚胎中的新阶级的势力，党在取得政权后，就立即控制所有权力并将一切财物抓在手中，扬言自己代表工人阶级和劳动人民的利益。除了在革命战争时期的一个极短的阶段以外，无产阶级并没有分享权益，它在这方面所扮，演的角色并不比其他阶级重要。
 
这并不是说无产阶级，或其中的某些阶层，对维护共产党的政权没有暂时的兴趣。农民也曾支持那些扬言有意通过工业化把他们从无望的灾难中拯救出来的人。
 
虽然工人阶级的个别阶层可能临时支持党，但政府不是他们的，而他们在政府中所占的地位对整个社会进步的过程和社会关系并不重要。在共产主义制度下，政府从未采取任何措施来帮助劳动人民，特别是工人阶级，取得其权力和权利。这也是必然会产生的情况。
 
工人阶级和劳动群众并不行使政权，但党却以他们的名义在行使政权。在任何政党中，包括最民主的政党在内，领导人所扮演的角色都非常重要，以致党的权威就变为领导人的权威。所谓“无产阶级专政”就是最有利的环境的的开始，在这种环境下，无产阶级专政就变为党的专政，而且终于不可避免地演化为领导人的专政，在这种形式的极权政府中，无产阶级专政只是一种为寡头政治的某些执政者辩护的理论上的辩护词，最多也不过是他们意识形态的假面县。
 
马克思所设想的无产阶级专政是为了无产阶级的利益，指的是在无产阶级范围内的民主；那就是说，一个政府之内有许多社会主义党派参加。马克思的结论所依据的历史上唯一的无产阶级专政，即187l 年出现的巴黎公社，便是几个党派的联合政府，而马克思主义的党在其中既不是最小的也不是最重要的。但直接由无产阶级本身行使政权的无产阶级专政是个不折不扣的乌托邦，因为没有一个政府能不要政治组织而活动。列宁把无产阶级专政当作他自己一个党的权威。斯大林把无产阶级专政当作他个人的权威，也就是当作他个人对党、对国家的专政。自从这位共产主义皇帝逝世以后，他的继承人便交了好运，他们通过“集体领导”分享了权威。总之，共产主义的无产阶级专政如果不是一个乌托邦的理想，那就必然是为党的领导核心保留下来的一项特权。
 
列宁以为俄罗斯的苏维埃，即马克思的“最后发现”，就是无 产阶级专政。在起初由于苏紲埃政府的革命自发性，以及群众的参加革命，苏维埃政府看来似乎就是无产阶级专政。托洛茨基也曾相信苏维埃政府是一种当代的政治形式，正像在反对专制王朝的斗争中诞生的议会一样。然而，这都是错觉。苏维埃政府是从革命机构一变而为适宜于这个新阶级或共产党的极权独裁的一种形式。
 
列宁的民主集中制（包括党和政府的民主集中制）的情况也是这样的。当党内还容忍公开的不同意见时，党员依然可以觉得集中制有可取之处，尽管这并不是一种非常民主的集中制。当极权的权威被制造出来时，集中制就消失了，取而代之的是赤裸裸的寡头专政。
 
我们可以由此得出一个结论：在共产主义制度下，把寡头独裁变为个人独裁是一种长期的趋势。意识形态的一致，党最高领袖间的不可避免的斗争，以及整个制度的需要，都是造成个人独裁趋向的因素。坐上最高权力交椅的领导人和他的帮手们，便是当时最能表明并保护这个新阶级利益的人物。
 
在其他的历史条件下也有强烈的个人独裁倾向。例如，当正在大力推行工业化时，或国家在作战时，所有的力量都必须听命于一个见解和一个意志，不过，共产主义对个人独裁却有其独特的、单纯的理由：权威是共产主义和每一个真正共产主义者的基本目的和手段。共产党人对权力的贪婪是难以满足的而且是不可抗拒的。权力斗争的胜利无异于至上的光荣，失败就是莫大的耻辱。
 
共产党领袖也必然趋向于好大喜功，由于人类的弱点，以及当权者希望被认作有权势的风云人物的内在需要，好大喜功就成为他们不可抵抗的诱惑。
 
争地位、浮夸和酷爱权力是不能避免的，腐化也是不可避免的。这不是一般政府官员的腐化间题，因为这种腐化现象也可能比共产党执政之前的国家中所发生的腐化现象更少些。这是由一党专政并垄断一切特权所造成的一种特殊的腐化。“照顾自己人”，分派肥缺，或者任意分配各种特权是不可避免的。政府、党和国家的三位一体并在实际上掌握全国财产的事实，使共产党的国家自行腐败，而且必然会产生特权与寄生作用。
 
—位南斯拉夫的共产党员曾把一个普通共产党人的生活环境写得生动如画：“实际上我已被撕为三份：我看见有些人的汽车比我的汽车好，然而，在我看来，他们对党和社会主义的贡献并不比我多，我再从上往下看那些没有汽车的人，他们的确连一辆汽车都没有挣到。于是，我觉得我是幸运的，因为我毕竟还有一辆属于所有的汽车。”
 
显然他不是—名真正的共产党人，他属于这样—类的人；他之所以成为一个共产党员，是因为自己是一个理想主义者，后来他失望了。他就试图以一般的官僚生涯中所可能得到的东西去满足他自己。真正的共产党人却是狂热者和贪得无厌的抓权者的混合体。只有这种类型的人才是一个真证的共产党员。其他的党员不是理想主义者就是个人主义者。
 
由于共产主义制度是以行政工作为基础的，所以它必然是一种具有严格层次组织的官僚政治。在共产主义制度中，在政治领袖和会议的周围有许多排他性的集团。所以有政策的决定都成为这些集团之间的争吵，在这些集团内，笼络勾结之事层出不穷。最高的集团通常是最亲密的。国家大事都是在亲密交谈的晚餐中，狩猎中，以及两三个人的交谈中决定的。党的会议、政府的会议及若干集会的召开并无其他用途，只是通过它们把那些决定宣布，公诸于世。召开会议的目的只是用来确认在亲密的厨房中早已烹调好的食物。
 
共产党人对于国家政府有一种拜物的关系，就好像国家是他们的私人财产一样。同样的人，同样的团体在党内都很亲密、熟悉，可是，一旦身为国家代表，立刻就变得大模大样、神气十足了。
 
这个君主政体毫不开明。这位君主本身，这位独裁者，并不觉得他自己是个君主或独裁者。当斯大林被称为独裁者时，他就认为是无稽之误。他觉得他是党的集体意志的代表。就某种程度说，他是对的，因为历史上或许从来没有一个人曾经有过像他那么大的个人权力。像共产党的其他独裁者一样，他意识到如果放弃党的意识形态基础，放弃新阶级的独占主义，放叶国家财富的所有权或寡头政治的极权政权，结果必然将使自己倒台。诚然，斯大林从来考虑过作这类放弃。因为他是这个制度的创造者和最高代表。可是，他还得依靠这个经他通过行政权一手创造出来的制度，或依靠党的寡头政治的意见。他既不能做不利于他们的事，也不能越过他们而任意行使权威。
 
事实上，在共产主义制度中，没有一个人是独立的，党的高级人士不是独立的，它的领袖也不是独立的。他们都得相互依赖，并且得极力避免与他们的环境。当时流行的思想，控制权以及利益分离。
 
那末，谈共产主义制度下的无产阶级专政还能有什么意义呢？
 
四
共产党关于国家的理论首先是由列宁详细拟订、后来又经斯大林及其他人补充的，这一理论主张党官僚的极权独裁。这个理论的基本要素有二：（一）关于国家的理论；（二）关于国家消亡的理论。这两个要素是相互关联的，并且足以代表这一整个理论。列宁关于国家的理论几乎完全见于他的著作《国家与革命》中，那是他在十月革命前夕躲避临时政府时写的。像列宁其他方面的表现一样，这个理论倾向于马克思主义学说的革命面。在讨论国家的时候：列宁特别利用1905年俄国革命的经验，把革命这一面大加发挥而至于极端。就历史的观点来看，作为革命的一种思想武器，列宁的这个文件的意义要比作为根据其思想而建立的新权威的发展基础重要得多。
 
列宁把国家贬为力量，或者说得更准确一些，国家只不过是一个阶级为压迫其他阶级而使用的暴力机构。为了以最有力的方式表示国家的性质，列宁指出：“国家是一根棍子”。
 
列宁也见到国家的其他功能。不过，他也在这些功能中见到他所认为的国家必不可少的任务——一个阶级用暴力对付其他阶级。
 
事实上，列宁要求摧毁旧国家机器的学说根本不科学。但这个从历史观点看极有意义的列宁关于国家的理论，使以后一切典型的共产主义理论都找到了根据。基于当前情况的需要，党就创造一般原则，冒充科学的结论与学说，宣称半真半假的东西为真理。武力和暴力是所有国家权威的基本特色，国家机构总是为某个社会和政治力量所利用，在武装冲突时尤其如此，这些都是不可否认的事实。然而，经验表明，国家机器对于社会或国家之所以必要，还有另一个原因，那就是为了发展和联合社会的各种职能。共产主义的理论和列宁的理论都忽视了这一面。
 
在很久以前，历史上曾经有没有国家和权力机构的公社。但那不是社会，那只是一种从半野兽时代过渡到人类社会生活时代的方式。即使这些最原始的公社也有某些形式的权威。随着社会生活形式的日益复杂，要试图证明对国家的需要将在未来消失，未免是天真的想法。列宁是支持马克思的，马克思同意无政府主义者在这一点上的看法。列宁期待并试图建立一个无国家的社会。这里且不去讨论列宁立论的前提是否站得住，我们必须记住，他设想这个无政府社会就是他的无阶级社会。根据这个说法，这个社会将没有阶级和阶级斗争，没有人压迫别人和剥削别人，而且已经不再需要国家了。在这以前，“最民主的”国家就是“无产阶级专政”，因为它“消灭”阶级，并且因此而使它自己本身逐渐成为不需要。因此，凡是加强无产阶级专政或导致阶级“消灭”的一切都是正当的，进步的，合理的。在共产党人控制不到的地区，他们是为最民主的措施辩护的人。因为这对他们的斗争有利，在那些他们打算取得政权的地区，他们就变为一切民主制度的敌人，指责那些民主措施属“资产阶级”类型，他们一般把民主荒唐地划分为“资产阶级”民主和“社会主义”民主；事实上，区分民主的唯一正当而公平的标准应当视自由分量的多寡或自由的普遍性如何而定。
 
在列宁主义的或共产主义的关于国家的整个学说中，无论从科学的观点或实际的观点来看，  是有许多漏洞的。经验已经证明，结果是完全与列宁所想象的相反。阶级并没有在“无产阶级专政”下消失，而“无产阶级专政”也没有开始衰亡。实际上，共产党人极权权威的建立以及旧社会各阶级的消灭只是让人看来好像所有的阶级都消灭了。然而，国家权力的增长，或者说得更准确一些，即用以推行暴政的官僚政治的成长并未因无产阶级专政而停止。相反地，它的权力是增加了。这个理论得设法予以补救；斯大林曾说，在苏维埃国家“消亡”以前，它还得担当起更高的“教育”任务。如果我们只就共产党关于国家的理论的本质来说，尤其是就其理论的实践的本质来说，即认为国家主要的或者唯一的职能只是施行武力和强力，那末，我们可以说根据斯大林的说法，警察制度所担当的正是这种高级的或“教育的”任务。当然，我们能了解，这只是一个恶意的解释。但在斯大林的这一说法中，我们却见到共产党人另一个半真半假的理论；斯大林根本不知道如何解释一个明显的事实，即为什么在已经“建立起来的社会主义社会”中，国家机器仍在继续成长。因此他拿国家的职能之一，即教育的职能，当作国家的主要职能。他不能使用暴虐，因为苏联已经没有敌对阶级存在。
 
南斯拉夫的领袖们关于“自治”的理论也属同样情况。在与斯大林发生冲突时，他们不得不“纠正”斯大林的“偏差”，并且作一些企图促使国家不久后就会开始“消亡”的措施。但这并不妨碍斯大林或南斯拉夫领袖们继续推动并加强国家在武力方面的职能，对共产党的领袖们来说，武力是国家最重要的职能，它是他们关于国家的理论基础。
 
斯大林关于国家如何一面愈来愈强，一面却逐渐消亡的见解，也即关于国家的职能何以不断扩张，并把越来越多的公民吸入其中的见解，是非常有趣的。斯大林鉴于国家机器的作用不断扩大（尽管国家机器已经“开始”转变为一个“完全没有阶级”的共产主义社会），就认为到了所有的公民者都能升到国家的水平并管理国家事务的时候，国家就将消亡。而且，列宁还说过，总有一天，“甚至连家庭主妇也将管理政府”。正如我们所看见的，类似斯大林的理论也流行于南斯拉夫。但共产党关于国家的理论，即在他们的“社会主义”实现后，各种阶级将“消失”，国家将“消亡”，同党的官僚政治的极权权威这一现实之间的裂痕，是这些理论和斯大林的理论都不能弥补的。
 
五
不论是在理论上还是实践上，共产主义最重要的问题是国家的问题，由于在共产主义制度内部有这样一个明显的矛盾，这个问题就成为各种困难的恒久根源。
 
共产主义政权是政府和人民间一种潜在的内战形式。国家不只是一种暴政的工具，社会和国家机器的执行部门一直在不断地、积极地反对党的寡头政治，而寡头政府总想用赤裸裸的实力压服这些反对。实际上，共产党人并不能使国家完全依靠实力存在，他们也不能使社会完全屈膝。不过，他们能够控制实力机关，那就是说，控制警察和党，再用警察和党控制整个国家机器及其功能。国家机关及其职能对于党和警察或个别政治官员的“悖理行为”的反对，实际上就是进入了国家机器的社会的反对。这是由于社会的客观愿望和需要受到了压抑和损害的显示出来的一种不满。
 
在共产主义制度下，国家与国家的职能并没有退缩成一个压迫机构，它们也不同于压迫机构、作为一个国家生活和社会生活的组织，国家是屈从于那些压迫机构的。共产主义不能解决这种不调和现象，其原因是：由于共产主义本身的极权专制性质，它就不可避免地要与不同的和相反的社会趋向冲突，那些趋向甚至通过国家的社会职能表现出来。
 
由于这一矛盾，以及共产党人经常而不可避免地需要把国家主要当作一种武力的工具，所以共产主义国家就不能成为一个法治国家，即其司法独立不受政府的干预，法律能有实际效力。整个共产主义制度是反对这样的法治国家的。即使共产党的领导人希望建立一个法治国家，他们也不可能在不损及他们的极权权威下达到这一目的。
 
司法独立和法治必将导致一个反对派的出现。例如，在共产主义制度下，并没有一条关于反对言论自由和结社权利的法律。共产主义制度下的法律是保障公民的一切权利的，并且也是以司法独立这个原则为基础的。但实际上根本没有这回事。
 
在共产主义政权下，自由权是正式被承认的，但自由权的运用有一个先决条件：它必须是在有利于“社会主义”制度时，或在支持他们的统治时，才能使用，而代表社会主义的利益的，是共产党的领袖。这种违反法律规定的措施必然会造成警察和党的机构使用异常严厉和残酷的手段：共产党人一方面要保护法律的形式，而同时又得确保他们的极权权威。
 
就大部分情况而论，在共产主义制度下，立法权是不能和行政权分开的。列宁认为这是一个完善的解决办法。南斯拉夫的领导人也坚持这一点。在一党专政的制度下，这是政府专制和万能的根源之一。
 
同样，警察权实际也不能同司法权分开。捕人者也就是审判并执行处罚者。这个圈子是很紧的：行政机构，立法机构，调查机构，审判机构和惩罚机构是数位一体的，也是同一机构。
 
为什么共产党人的专政不得不如此地尽量利用法律？为什么他们得躲在法律的背后？
 
对外作政治宣傅是原因之一。另一个重要原因是共产党政权必须保障并确定它所依存的新阶级的权利，以便维持其自身的存在。法律总是根据这个新阶级或党的需要和利益制订的。表面上，法律是为全体公民制定的，但是，实际上，公民享受法定权利是有条件的，即只有在他们不是“社会主义的敌人”时才能享受。结果，共产党人经常担心，有一天他们可能被迫执行他们所订的法律。所以他们总要留下一个漏洞或例外，以便他们能够逃避他们的法律。
 
例如，南斯拉夫的立法机构就谨守一个原则：除非一个人的行动恰恰如法律所规定的犯罪行为，他就不得被判有罪。但是大多数的政治审判都是以所谓“敌意的宣傅”为理由，虽然对这一观念故意不下定义，只留给审判官和秘密警察去自行解释。
 
由于这些原因，共产主义政权下的政治审判大多数是事先安排好的。法院的任务只是证明当权者需要证明的罪行；或者说，法院的任务只是为被告的“敌对活动”的政治性判决披上一件法律的外衣。
 
在用这种方法进行的这些审判中，被告的供辞是最重要的。他必须自己承认他是一个敌人。于是，前提便肯定了。可能就．没有多少证据，因此就必须用被告的坦白书来作证据。
 
南斯拉夫的政治审判只不过是莫斯科方面政治审判的袖珍版。所谓莫斯科的审判就是共产主义制度下司法和法律滑稽戏的最可笑最血腥的例子。其他的绝大多数审判，就行为和惩罚而论，也都是属于类似性质的把戏。
 
政治性的审判是怎样处理的呢？   
 
首先，根据党的工作人员的意见，党的警察便确定某人是目前的“敌人”；如果没有其他理由，他的见解以及和密友的谈话就算是罪嫌，至少地方当局认为如此。第二步是准备对敌人作合法的清除。通常这是通过两种途径进行的。其一是派挑拨分子故意煽动受害人“发牢骚”，参加不合法的组织或者作类似性质的行动；其二是利用“密探”出面作证，依据警力的希望，提出控告受害人的证据。在共产主义政权下，绝大多数非法组织是秘密警察为了诱惑反对分子加入而建立的，以便将反对者置于一种警察可以向其实行清算的地位。共产党政府并不阻止“令人厌恶的”公民违法犯罪；而且事实上诱惑他们这样做。
 
斯大林通常并不假手法院，而是广泛地行使酷刑，即令不用酷刑而假手法院，其审判的本质是一样的：共产党清算他们的反对者，并不是因为那些人犯了罪，而因为他们是反对者。从法律的观点说，大多数被惩罚的政治犯是无辜的，尽管他们是这个政权的反对派，从共产党人的观点来看，尽管这些反对者被判罪并没有法律根据，但他们是按照“适当的法律程序”被判罪和受到处罚的。
 
当公民自发地反对共产党政权的措施时，共产党当局便擅自处理他们，根本不管宪法和法律的条规。共产党政权对于群众的反对所采取的残暴、不人道与不合法的行动，是近代史上空前未有的。在波兹南所采取的行动是最有名的，但不是最残暴的。占领国和殖民国家虽然都是征服者，占领军当局也极少采取这样严酷的行动，尽管也采用非常法令和紧急措施来完成它们的行动，但很少采取这样残暴的措施。共产党的执政者竟在他们“自己”的国家用践踏他们自己的法律的办法来完成他们的行动。
 
甚至在非政治性的事务上，司法和立法当局也难免受专政者的干预。这个极权阶级及其成员不可能不干预司法和立法机构的业务。这是每天都在发生的事。
 
1955年3月23日贝尔格莱德的《政治报》上有一篇文章，对于南斯拉夫法院的真正任务和地位提供了一个最适当的说明（尽管南斯拉夫的法治程度一直较其他共产主义国家为高）：
 
“在以检察官布拉纳?吉夫列摩维克为主席的历时两日的年会上，讨论关于经济方面的犯罪活动问题时，各共和国的检察官、伏哲伏迪纳的检察官以及贝尔格莱德的检察官们都曾宣称，为了使经济方面和一切政治组织中的反对犯罪活动的斗争取得完全胜利，就必须使司法机关和经济自治单位以及一切政治组织进行合作……
 
检察官们认为，社会上对于消除这种罪犯的反应还不够热烈。
 
检察官们都同意，社会反应必须更积极。根据检察官们的想法，更严厉的处罚和更严厉的执行处罚的方法只是应该采取的措施的一部分。……
 
会议所引用的例子证实，有些在政治领域中失败的敌人现在已渗入经济领域。因此，经济领域的犯罪问题并不只是一个法律问题，而且也是一个政治问题，这就需要所有政府机构和社会组织的合作。……
 
在总结这些讨论时，联邦检察官布拉纳?吉夫列摩维克强调因南斯拉夫已实行分权而产生的条件下的法治意义，并且指出，我们的最高领袖们对于个别经济罪犯的严厉处分是合理的。”
 
显然，检察官们已经决定，法院将根据“最高领袖们”的意旨来审问和判刑。这样还有什么法院和法治可言呢？
 
在共产主义制度下，法律理论是根据环境和寡头政治的需要而改变的。维辛斯基主张判罪要根据“最大可靠性”，即根据政治的分析和需要，但这个原则已经被摒弃了。在政府和司法及立法的关系改变之前，即使采取更人道、更科学的原则，实质上也不会有任何变更。定期性的“法制”运动和赫鲁晓夫所吹嘘的党“现在”对警察和司法机构控制的成功，仅仅反映出统治阶级在日益需要法律安全方面的形式的改变。它们并不表明统治阶级对于社会、国家、法院或法律所持立场的改变。
六
共产主义的法律制度不能脱离形式主义，也不能在审判、选举以及类似事件上摆脱党组织和警察的决定性影响。愈往上去，法治就愈变成装饰品，而政府在司法、选举等事件上所起的作用就愈重要。
 
共产主义国家的选举之空洞和铺张浪费是尽人皆知的事；如果我的记忆无误，艾德礼曾风趣地称它们是“只有一只马出场的赛马”，在我看来，还有些话应该补充：既然选举对政治关系并没有影响，那末共产党人为什么非实行选举不可呢？为什么非要像议会选举那样进行如此费钱而空洞的勾当呢？
 
宣传和外交政策的需要又是理由之一。还有一个理由是：如果一切不通过合法程序建立起来，任何政府都无法存在，共产党政府也不例外。在当前情况下，是由人民选出的代表来使政府合法的。人民必须正式批准共产党人所做的一切。
 
此外，在共产主义国家中所以有代议制度的存在，还有一个  更深刻更重要的理由。党的高级官僚，或者新阶级的政治核心有必要批准其最高机关政府所采取的措施。共产党政府能够不管一般舆论，但不能不理党的舆论和共产主义的舆论。因此，尽管选举对共产党人没有什么意义，但党的最高集团对于议员的选择是慎重其事的。在选择时得考虑到—切条件，如个人在运动中和社会中的服务成绩，所担当的任务，所能发挥的功能，以及所代表的职业等。从党内的观点看：选举领导人物非常重要：领导人物分配着他们所视为党在议会中的最重要权力。这样一求，领导上就有了以党、阶级和人民名义行动时所需要的合法地位。
 
共产党曾试图让两个或两个以上的共产党人去争议会里的一个席位，但并没有取得建设性结果。有些例子证明，南斯拉夫曾作此尝试，不过，领导上断定这种企图是造成“分裂”的。最近听说在东欧国家有好些共产党候选人争取同一职位的事。这可能是让两个或两个以上的候选人争一个位置，但很少可能作有系统的进行。这将是前进了一步，并且甚至可能是共产主义制度走向民主的转捩点，然而，在我看来，这距这些措施的实践还有一段漫长的路程，并且东欧国家的发展应该先循南斯拉夫的“工人管理”制度所走的路线，而不应该向只作一些相应的变化的政治民主方面走。专制核心如今依然大权在握，他们明白，放弃传统的党内统一将是非常危脸的。党内的任何自由不仅会危及领袖们的权威，而且会危及极权主义本身。
 
共产主义国家的议会没有权利对任何重要的事情作出决定。议员们都是预先选定的，这样的当选使他们深有受宠之感，所以，即令他们想有所争议，他们也没有权力或勇气去做。此外，由于他们当选并非决定于选民，代表们并不觉得他们对选民负有责任。共产主义国家的议会完全应该被称为议员们组成的“庙堂”。他们的权利与任务是一次又一次地一致通过早就由后台为他们决定好的议案。共产主义制度下的政府是不需要其他类型的议会的，的确，可能还会有人非难其他类型的议会是多余的而且花钱太多。
 
七
共产主义国家是靠武力和暴力建成的，并且经常和人民发生矛盾，所以，纵或没有外在的理由，它也必然是黩武的。对于武力，特别是军事实力的崇拜，是没有任何国家能赶得上共产主义国家那么厉害的。黩武主义是新阶级内在的基本需要，这是使这个新阶级存在、有实力并享有特权的各种力量之一。
 
基于经常压力的存在，共产主义国家在基本上，甚至必要时要绝对地成为一个暴力机构。因此它一开始就已经是一个官僚政治的国家。由于一面有少数当权者的专制主义的维持，一面又有各种法令和规章的帮助，所以共产主义国家所控有的权力大过其他任何国家组织。共产主义国家一经建立，立即就充满了各种各样的法律和条规，多到甚至连法官和律师都搅不清楚。尽管有些条例并无好处，但政府对任何事都要订出详细的规定。基于意识形态上的理由，共产主义的立法者常常颁布各种法令，但并不考虑到它们的实际环境和实际可能性。他们成天浸沉在可以不受批评或反对的合法而抽象的“社会主义”公式中，把生活约束在条文里，大会则机械地通过这些条文。
 
然而，当问题涉及寡头政治的需要以及领导人的工作方法时，共产党政府也就不讲官样文章了。甚至在极例外的情况下，国家和党的领导人不喜欢受法规的约束。制定政策以及做出政治决定的大权既握在他们的手中，因此就不能忍受拖延或太严格的程序的约束。领导人在对有关整个经济问题及所有其他事件作决定时，除开那些不重要的、象征性的、形式的问题外，是不受过分严格的限制的。最严格的官僚主义与政治上的中央集权主义的创造者，既不是一般的官僚，也不是受法令的约束。例如，不论就任何一方面说，斯大林都不是一名官僚。在许多共产党领导人的办公室中，普遍存在着混乱和拖拉作风。
 
然而，这种情况并没有阻止他们暂时地站在“反官僚主义”的立场上，那就是说，反对行政工作中的拖拉和舞弊。他们今天正在反对斯大林式的官僚统治。可是，他们并无意消除盛行于经济的和国家的政治机构内部的真正的、根本的官僚作风。
 
在这种“反官僚主义斗争”中，共产党的领导人常常援引列宁的话。可是，对列宁作仔细研究之后，情况表明，他并未预见新制度将走向官僚政治。列宁同部分地从沙皇政府沿袭下来的官僚作风作斗争时，指出大部分困难是由于“没有一个机构是由甄选的共产党员或苏维埃党校出身的人组成的”。在斯大林统治下，旧官员全被清除了，遗缺都由“甄选的”共产党员补上了，尽管如此，官僚主义仍在滋长。甚至在像南斯拉夫这种国家中，官僚作风的行政要弱得多，但它的本质，政治官僚的垄断以及因此而产生的关系，并没有废弃。纵或有一天作为行政方法的官僚主义被废止了，但作为一种政治—社会头关的官僚主义将继续存在。
 
共产主义国家或政府正在努力做到使个人，民族，甚至国家的代表都完全非个人化，政府一心想把整个国家变为公务人员的国家。政府一心想直接或间接地管理并控制工资、房屋甚至知识活动。共产党人并不用是否公务人员这一点来区分人民，因为他们认为所有的人都是公务人员，他们只根据他们所得的薪水和享受的特权来分辨等级。通过集体化措施，甚至连农民也逐渐变为整个官僚社会的一员了。
 
然而，这只是外表的看法。在共产主义制度内，社会集团是尖锐地划分开来的。尽管有达许多差别和冲突，但总的说来，共产主义社会比其他社会较为统一。整个共产主义制度的弱点在于它的强迫态度和关系，以及组成这一社会的相互冲突的因素。可是，各个部分彼此间是相互依赖的，就像一架巨大的机器。
 
就像在一个绝对专制的王朝统治下一样，在共产主义政府纯洁下，也即在一个共产主义国家，人的个性的发展只是一个抽象的理想。在专制王朝时代，当重商主义者强求政府施行重商经济时，帝王本身——如俄国的卡特琳女王——就认为政府有责任重新对人民进行教育。共产党的领导人也这样做和这样想。可是，在专制王朝时代，政府只是想把当时既有的各种观念变为政府所持之观念的附属品。而如今，在共产主义制度下，政府本身既是所有人又是思想家。这并不是说，在共产主义制度下，人的个性已经按照一个全能的恶魔术师的意志而消失，或已变成一个在廓大而无情的国家机器中转动的一个笨重而无人味的齿输。人的个性生来就兼有集体性和个体性，它是不可摧毁的，即在共产主义制度下也是如此。当然，在这个制度下，人的个性所受到的压抑比其他社会更甚，因而它不得不以一种不同的方式表现。
 
个性的领域只是处理日常琐事的领域。当这些日常生活上的小事和愿望与垄断人民的物质生活及知识生活的共产主义制度堡垒冲突时，即使是这个小小的领域也不自由、不安全了。在共产主义制度中，不安全便是个人的生活方式。政府给他一个生活的机会，但有一个条件，即他必须顺服。一个人的个性在他所想要的和他实际所有的这两者之间被撕破了。就像在其他的制度下一样，人们易于承认集体利益和服从集体利益，不过他也会反对集体中的那些篡位的代表。在共产主义制度下，大多数人是不反对社会主义的，他们只反对达到社会主义的方法，这就证明共产党人并没有在发展任何一种真正的社会主义。个人所反对的是那些是为寡头政治的利益而设的各种限制，但他们并不反对为整个社会利益而设的限制。
 
没有在这些制度下生活过的人一时很难了解：人类，特别是如此高傲而英勇的各民族，何以会放弃自己的思想和行动自由到这种程度？对于这种情况最准确的、虽然不是最完全的解答，就是由于暴政的严酷性和全面性。不过，在这种局面的骨子里，还有更深的理由。
 
一个理由是历史上的; 共产主义国家的人民是在经济变革的不可抗拒的潮流中被迫忍受自由的丧失的。另一个理由是知识和道德方面的。由于工业化已成为整个国家生死关头的事，社会主义或共产主义既作为工业化的理想代表，就变成了理想与希望，而在共产党人及一部分人民当中，共产主义几乎被视为神圣。在那些不属于旧社会阶级的人民的心目中，有计划、有组织的反党反政府的行动，不啻是犯了背叛祖国和最高理想的罪行。
 
共产主义国家中所以没有有组织的抵抗的最重要理由，在于共产主义国家的包揽—切和极权主义。它的权力已渗入社会和个人的所有毛孔，它深入了科学家的视界，诗人的灵感，甚至情人的梦境。如果起而反抗，就不仅会以一名绝望的个人而死，而且会被社会辱骂和遗弃。在共产党政府铁腕下是既没有空气也没有阳光的。
 
反抗集团的来源主要不外两种，一是来自旧阶级,一是来自原来的共产主义自身，但对于他们的自由所遭受的侵犯，两者都找不到抗击的途径和手段。第一个集团在后退，第二个集团则进行着无目标、无思想的革命活动，并与当权者作教条上的诡辩。因此，发现新的道路的条件尚未成熟。
 
同时,人民本能地不信任新的道路并且抵抗每一种步骤和细节。如今，这种抵抗已成为对共产党政政权的最大的、真正的威胁。共产党的寡头已不再知道群众的思虑和感觉了。在深邃而黑暗的不满之海中，共产党政权已深感不安。
 
虽然像共产党独裁政权这样成功地压制它的反对者是史无前例的，但它所激发的不满之深广也是空前未有的。看来良知被压缩得愈紧，建立一个组织的机会愈少，不满也就愈大。
 
共产主义的极权主义导致普遍的不满，在这种不满中，除了失望和愤恨外，所有的不同意见都逐渐消灭了。因日常生活琐事而引起的亿万人民的不满，就是一种自发的反抗，共产党人对这种自发的反抗形式还无法压服。在德苏战争时期就曾证实这一点，，当德军开始攻击苏联时，俄国人似乎丝毫不想抵抗。然而，不久以后，发现希特勒的意图是毁灭俄国，并且要把斯拉夫人及苏维埃其他各族人民变为“统治民族”的非人的奴隶。于是，从人民心底深处涌起了对祖国传统的、不可征服的热爱。在整个战争中，斯大林既不对人民提及苏椎埃政府，也不提及社会主义；他只提一样东西——祖国。不管斯大林的社会主义如何，为祖国而死总是值得的。
八
共产党政权已经成功地解决了被它推翻的制度所不能解决的许多问题。它们也成功地解决了在它们当权前一直存在的民族问题。然而，它们还未能完全解决民族资产阶级的冲突。这个问题已以一个崭新而且更严重的形式在共产党政权中再度出现。
 
通过一个高度发展的官僚政治，民族统治正在苏联建立。可是，存南斯拉夫，由于各族官僚间的摩擦，争执正方兴未艾。不管是苏联的情况也好、南斯拉夫的情况也好，两者都不关心旧式的民族冲突。共产主义者不是民族主义者；对他们来说，坚持民族主义不过是一种形式，就像他们坚持其他的形式一样。只是借此加强其权力。为了达到这个目的，他们甚至可以不时地像狂热的沙文主义者那样行动。斯大林是一个格鲁古亚人，不过，当事实和宣传需要时，他会成为一个狂热的大俄罗斯主义者。甚至赫鲁晓夫都承认，斯大林的错误之一，是将整个整个的民族加以消灭这一可怕的事实。斯大林及其党羽利用俄罗斯民族这个最大民族的民族偏见，仿佛它是由霍屯督人组成的一样。不管是什么东西，只要可以利用，共产党的领导人总要加以利用，例如，他们宣传各民族官僚机构间权利平等，这在他们说来，实际上就算是要求各民族间的权利平等。
 
然而，在共产党民族官僚机构间的冲突的基础中，并没有民族情感和民族利益。冲突完全是出于别的动机：这是在自己的行政范围内谁坐第一把交椅之争。为自己的民族共和国的权力和声誉而进行的斗争同为加强个人权力之争相差不远。共产主义国家中的民族共和国只不过是以不同语言为基础的行政区划，此外并无其他意义。尽管他们未曾受过应该站在语言基础上还是站在民族基础上的训练，共产主义民族共和国的官僚们总是站在他们行政单位立场上的热忱的地方民族主义者。在南斯拉夫的某些纯行政性的单位中（如地方议会），其沙文主义比各民族共和国政府中的沙文主义更为严重。
 
在共产党人中，既可以碰到眼光肤浅的官僚沙文主义，也可以见到民族意识的衰微，甚至在同一个民族中都是如此，这完全由机会和需要来决定。
 
共产党人所操的语言与其本国人民所用的话言不同。尽管字句相同，但其表达方式、意义及涵义等却完全有他们自己的一套。
 
虽然他们对其他制度抱绝不容忍的态度并在自己的制度中抱地方主义态度，但当他们的利益需要时，共产党人也可以成为狂热的国际主义者。曾经具有各自不同的形式和色彩，自己的历史和希望的各个民族，在这个无所不能、无所不知而且基本上在民族方面无所属的寡头政权面前显得黯然失色，软弱无力。在激励和唤醒各民族方面，共产党人并未获得成功；就这一意义而言，他们在解决民族问题方面也失败了。谁能知道目前乌克兰的作家和政治人物的情况？那个面积像法国一样大并且一度是俄国最进步的民族的乌克兰民族的现状如何？你一定会觉得：只有浑浑噩噩的乌合群众才能依然生活于这个无人性的压迫机器之下。
 
然而，事实并不如此。
 
就像人的个性一样，各种社会阶级和思想依然存在，民族也依然存在，它们在发挥作用，它们在作反专制主义的斗争，并且保持着显着的特色，使它们不被毁灭。如果说它们的良知和灵魂被窒息了，但它们并未破碎。虽然它们是被压制了，但它们并未屈服。目前推动它们的力量比旧的或资产阶级的民族主义更强大，它们有一个不可摧毁的意志，它们要使自己当主人，并且通过它们本身的自由发展，要永远同共产主义世界以外的人类保持日益密切的友好关系。

第五章  经济上的教条主义
一
共产主义经济的发展，并不是共产主义政权本身从革命的专政到反动的专制政治这一发展的基础，而是这一发展的反映。这一发展是通过斗争与争论而形成的，它表明在初期所必需的政府对经济的干涉如何逐渐变成统治的官僚集团图谋私利的极重要的手段。最初，国家攫取所有的生产资料，以便控制一切投资来加速工业化。后来，经济进一步的发展，终于主要是为了统治阶级的利益。
 
其它类型的财产所有者，其行动方式并无根本不同：他们也总是追求某种私人利益；但这个新阶级与其它类型的财产所有者的区别，在于前者多少掌握着国家全部资源，并以一种周密及有组织的方式发展其经济势力。一个周密的统一制度，诸如政治及经济上的种种机构，也为其它阶级所利用。但因为财产所有者既为数众多、财产之形式也各种各样，而且彼此间互相冲突，因而在共产主义经济以前的一切经济中，至少在正常或和平情况下，仍保持自发性及竞争性。
 
即使共产主义经济未能有效地抑制自发性，但与其它制度对照起来，它却不断地坚持应实现自发精神。
 
这一做法有其理论根据。共产党领袖们。深信他们懂得经济规律，并能以科学的准确性来管理生产。其实，他们唯一所能懂得的，只是如何攫取对经济的控制权。他们攫取经济控制权的这套本事，正如他们在革命中获致胜利，已在他们的脑子里产生一种错觉，认为他们之所以获致成功，是由于他们非凡的科学才能。
 
由于深信其理论的正确，因而他们管理经济大多依照这套理论。因此共产党必先将一项措施说成与马克思的某一观念相符合，然后才付诸实行，这真是大笑话。在南斯拉夫，官方曾宣称它的计划是依照马克思的理论来推行的；但马克思既非一计划者，也非一计划专家。事实上他们并无一事是依照马克思的意思行事的。虽然，自称一切计划都按照马克思理论，其目的无非使人民在意识上得到满足，并用来说明暴政及经济统制是为着“理想的”目的和根据“科学的”发现。
 
经济上的教条主义，是共产主义制度中不可分割的一部份。可是硬将经济按入教条主义的模型，却并非共产主义经济制度显着的特点，因为在这种经济制度中，领袖们在“适应”理论方面掌握主动权，当他们觉得于其本身有利时，往往也可以背弃理论。
 
除由于加速工业化的历史性需要的动机外，共产党的官僚们已被迫建立一种经济制度，来保证其本身权势之持续，以建设一个无阶般社会和废除剥削为口实，它已建立起一套严密的经济制度，而其财产的形式有利于党的统治与袭断。最初，共产党人为了客观的理由，必须采取“集体化”形式。  目前，他们继续加强这一形式，并未考虑这一做法是否有利于国家经济及进一步的工业化，而只为其本身的利益，为共产党阶级本身的目的。最初，他们管理并控制整个经济，是为了所谓理想的目标；但后来，他们却完全为了保持绝对控制与统治的目的。这是共产主义经济制度中所以采取这种广泛而硬性的政治措施的真正原因。
 
1956年，铁托在一次访问谈话中，承认西方各国经济制度中有“社会主义的成份”，但他认为这些成份并非“有周密计划地”导入西方经济。这一说法道出共产党的全部观念：正因为在他们国家的经济中“社会主义”是“有周密计划地”——由有组织的强迫行动——建立起来的，所以共产党必须维持其残暴的统治方法，及其对财产所有权的垄断。
 
对于经济及社会发展中这种“周密的计划性”给予重大的、甚至是决定性的意义，这表现出共产党经济政策的强制性及自私性，否则，坚持这种周密的计划性有什么必要呢？
 
除了他们认为合于社会主义的所有权的形式外，共产党强烈反对一切所有权的形式，这最能说明他们具有夺取及维持政权的不可抑制的欲望。但是，当这种激烈的态度有损于其切身利益时，他们也会放弃或改变，因此，他们对于其所提出的理论往往无法自圆其说。如在南斯拉夫，共产党起初建立集体农场以及后来解散集体农场都是在“不会有错误的马克思主义”及“社会主义”的名目下进行的。今天在这个问题上南共又在实行第三条混乱的中间路线。类似的实例在所有共产党国家中都有。无论如何，除了他们本身的所有权外，废除各种形式的私人所有权则是他们不变的目标。
 
每一种政治制度均表现经济力量并企图管理经济力量。共产党人对于生产虽然不能达到全部的控制，但他们的控制力，已达到使生产继续服从其意识形态及政治目标的程度。关于这一点，共产主义是与所有其它政治制度不问的。
 
二
共产党常以全体所有制一词来解释生产者的特别地位，并且更重要的是他们常以思想在经济中之超越地位来解释生产者的特别地位。
 
苏联在革命成功后，其人成就业自由立即被剥夺。但这一政权的急需工业化，使这种自由未能完全被剥夺。就业自由的完全被剥夺，只是在工业革命成功，新阶级建立后才发生。1940年，通过一项法令，禁止就业自由，并规定对擅离职守者予以惩处。在这一时期及第二次世界大战以后，一种奴隶劳动制度（即劳动营）开始发展。况且，劳动营的劳动与工厂间的劳动之间几乎毫无差别。
 
劳动营与各种“自顾的”工作活动只不过是最坏的、最极端的强迫劳动的形式。在其他制度中，这种情形可能是暂时性现象，但在共产主义下的强迫劳动，却保持一种永久性的形态在其它共产党国家中，强迫劳动虽不采取相同形式，也未曾发展到苏联那样程度，但这些国家里都没有完全的就业自由。
 
在共产主义制度中，强迫劳动是垄断全部或几乎全部国家财产所有权的结果。工人发觉自己处于不仅要出卖劳动力的境地，而且必须在其不能控制的条件下出卖劳动力，因为他们无法找寻另一较好的雇主。全国只有—个雇主即国家。工人除接受这一雇主的条件外，已无选挥的余地。早期资本主义最坏及最有害的因素，从工人立场而言，就是劳动市埸，已被新阶级对劳动力所有权的垄断所代替。这种情形并未使工人更为自由。
 
共产主义制度下的工人不同于古代那种奴隶，甚至在强迫劳动营里的工人，也与古代奴隶不同：  古代的奴隶，在理论及实际上，都被视为物件。甚至古代最伟大的思想家亚里斯多德也相信人们生而为自由人或奴隶。他虽相信对奴隶应予人道待遇，并主张改革奴隶制度，但他仍把奴隶看作生产工具。在现代技术制度中，不可能以这种方式来对待工人，因为只有一个受过教育并对工作有兴趣的工人才能做要求他做的工作。共产主义制度下的强迫劳动，与古代及历史后期的奴隶制度大不相同。它是所有权及政治关系发展的结果，并不是（或者只是在极小的程度上是）生产技术水平提高的结果。
 
由于现代的技术要求一个工人享有充分自由，  因而它与强迫劳动，或所有权的垄断及共产主义的政治极权主义根本上极不相容。在共产主义之下，工人在表面上是自由的，但实际上他使用自由的可能性极为有限。对自由的正式限制虽非共产主义固有的恃性，但却是共产主义下所发生的一种现象。关于工作及劳动力本身，这种情形尤其明显。
 
在一个一切财物均被一集团垄断的社会中，劳动力是不可能获得自由的。劳动力间接成为这个集团的财产——纵然不完全如此，因为工人究竟是一个人，他本身也用掉他的部份劳动力。就抽象意义言，劳动力作为一整体，是整个社会产生中的一个要素。新统治阶级既具有物质上及政治上之垄断权，就能将此项因素使用到与其它全国性的物资及生产要素几乎相同的程度，并作同样的对待，而不顾及人的因素。
 
把劳动力看作生产中的一个因素，于是各企业中的工作条件，或工资与利润间的关系，就不被官僚集团所关心。工资及工作条件是依照抽象的劳动力观点决定的，或依照个人的资格，很少或者根本不顾及各企业或各工业部门实际的生产成果。这只是一般的规律；根据不同情况及需要，也有例外。但这一制度必然导致实际生产者（即工人）对其工作缺乏兴趣。并且也造成质量的低劣，实际生产率的降低与技术进步的停滞，以及工厂的腐败。共产党人只知争取个别工人方面生产率的提高，而简直不注意于整个劳动力的生产率。
 
在这种制度下，鼓励工人的种种努力是经常不可缺少的手段。官僚集团提出各种奖金及补贴，以消除工人缺乏工作兴趣的现象。但只要共产党人不改变其制度的本身，并继续维持对一  切所有权及政府的垄断，他们便无法鼓励个别工人工作的热忱，  更谈不到刺激整个劳动力。
 
在南斯拉夫，已煞费苦心实施许多办法将利润拨一部份给工人；在东欧其它国家也正在作此打算。但官僚集团很快地就以遏制通货膨胀、并将金钱作明智投资为辞，将“超额的利润”保留在手内。留下给工人的部份微乎其微，只是一种象征性的数额以及一种建议的“权利”，建议如何通过党和工会组织（就是通过官僚集团）进行投资。工人们既无罢工权利，又无权决定谁享有什么，因而不可能有很多机会来分享利润中的应得部分。这已是显然的，所有这些权利是与各项政治自由相互交纤在一起的。它们与其它权利分开了，便无法获得。
 
在这种制度下，自由工会组织决不可能存在。像1954年在东德和l956年在波兹南因工人不满而爆发的罢工，都是极难得发生的事情。
 
共产党对于压制罢工运动的解释是：“工人阶级”已经当家做主，并通过国家掌握生产资料，因此，如果工人举行罢工，那就等于对自己罢工。这种天真的解释是根据下列的事实：在共产主义制度之下，财产已不为个人所有，而是如大家所知道的，被巧妙地曲解为财产所有者是集体的与表面上无法单独辨认的。
 
最重要的，在共产主义制度下，因为只有一个所有者掌握着所有财产及全部劳动力，因而罢工是不可能发生的。没有全体工人的参加，对这一个所有者很难采取任何有效的行动。某一企业或某些企业的罢工——假定在极权专制制度之下如此事件完全有可能发生的话——也不可能真正威胁这一所有者。因其财产并非由这些个别企业构成，而是包括全部生产机器。在几个个别企业中的损失，并不足以使这一所有者受到创伤，因为生产者或整个社会势必要补偿这些损失的。因此，对共产党人来说，罢工与其说是经济问题，不如说是政治问题。
 
个别的罢工就其可能的结果来说，几乎是不可能与无望的。同时总罢工的发生，缺乏适当的政治条件，而它们只有在特殊情形下才能发生。每当个别的罢工发生时，它们常会转变为总罢工，并且具有浓烈的政治色彩。此外，共产党政权不断地分化离间工人阶级，其手段是：把那些“教育”工人阶级，“提高其思想意识”，并指导其日常生活的人，从工人队伍中提拔出来并授予官职。 
 
工会组织与其他职业团体，由于其目的与作用，只能视为单一的所有者与当政的寡头政体的附属物。因此，它们的“主要”目的是为“建设社会主义”或增加生产。此外，它们的其他作用是在工人中传播种种错觉及培养使工人驯服的情绪。这些组织只起一种重要的作用——提高工人阶级的文化水平。
 
共产主义制度下的工人组织，实在是一种特殊形态的“行会”或“黄色”组织。此处所以用“一种特殊形态”一词，因为它们的雇主是政府，同时又是主要意识形态的代表人。 在其它制度中，这两个因素通常彼此割裂，因而工人纵不能倚赖一方面，至少也可利用双方之间的分歧与矛盾。
 
工人阶级是共产党政权主要的关切对象，这绝不是偶然的；那不是为了理想主义或人道主义的理由，而仅仅因为这是个生产和新阶级的兴起与存在都要依靠它的阶级。
 
三
在共产主义制度中，虽无自由就业与自由的工人组织，但对工人的剥削也有其限度。对此种限度的研究需要更深入及具体的分析。我们在这里所探讨的只是它的最重要的方面。
 
除政治上的限制——对工人不满的恐惧，及对易引起变化的其它考虑——之外，对工人的剥削尚有许多经常性的限制：剥削的形式程度如果使这一制度付出过高代价时，则迟早必须予以废弃。
 
因此，根据苏联1956年4月25日的一项命令，把惩处工人迟到或离职的规定都废除了。同时许多工人从劳动营中获释；在这些获释的工人中，不可能区别出哪些是政治犯，哪些是由于政权需要劳动力而被关进劳动营的。此项命令虽未能使劳动力全部解放，因为许多限制仍旧存在，但这一行动，确是斯大林死后最重要的进展。
 
强迫性的奴隶劳动给共产党政权带来许多政治上的困难，而且当进步的技术传入苏联以后，这更变得代价过高。一个奴隶劳工不论你供给他的食物是多么少，但若将监督与管理机构的一切费用计算在内，其成本仍然要超过其所能生产的价值因此，其劳动力已变成毫无意义且无法继续下去。现代的生产，在其它方面，也限制着剥削。机器不能由精疲力竭的强迫性的劳工予以有效率的运转；而且适当的健康与文化条件已成为不可缺少的先决条件。
 
在共产主义制度中，这种对剥削的限制与对劳动力自由的限制同时并存。这些自由是由所有权及政府的性质所决定。除非所有权及政府发生变化，劳动力不可能获得自由，而必须继续遭到温和的或严厉的经济上及行政上的压力。
 
由于生产上的需要，一个共产党政权规定了劳动的条件及劳动力的地位。他们采取多方面和无所不包的社会措施：如规定工时、假期、保险、教育、女工及童工劳动等等。但许多这些措施多半是虚有其名；还有许多甚至含有渐进的损害性在一个共产主义制度下，约束劳工各种关系及保持生产上的秩序和安定是一不可变的趋势。这个独一无二的集体所有者负责解决全面劳动力问题。它在任何方面都不能容忍“无政府状态”，在劳动力方面尤其如此。它必须管理劳动力，正如它必须管理生产中其它各方面一样。
 
共产党大吹大擂，说在共产主义制度下已充分就业，但这种夸口并不能掩盖只要人们细加观察便可看出的伤痕。一切资财，一旦为一个集团所控制，则这些资财，如人力的需要，就必然成为其计划的主要部份。政治需要在计划上既占重要地位，这样必然造成一种结果,即为了保持若干工业部门的存在，必须使其它部门付出代价。这样，计划便掩盖了真正的失业。一旦经济的各个部门能获得较自由的活动，或共产党政权不必为维持和加强某一工业部门而牺牲另一部门时，失业现象便会重现。而且和世界市场维持更为广泛的联系也会引起这种趋势。
 
因此，充分就业并非共产党“社会主义”的结果，而是以命令推行经济政策的结果；归根结底，充分就业是不协调与生产无效率的结果，它并不能表现共产主义经济制度的力量，而只能暴露其弱点。南斯拉夫在其生产效率没有达到满意程度前，一直缺乏劳工。自从其生产效率提高后，失业随即出现。如果南斯拉夫的生产效率达到最高峰，失业情形或将更加严重。
 
在共产主义的经济制度中，充分就业掩饰了失业现象。普遍的贫困掩饰着部份的失业，正如其若干经济部门的长足进步掩饰了其它部门的落后一样。
 
而且，这种垄断的所有权及政府，可以防止经济的崩溃，但却无力防止慢性的危机，新阶级的自私自利，经济制度之受意识形态支配的性质，使它不可能维持一个健全而和谐的制度。
 
四
马克思并非第一个想象未来社会的经济必须建立于计划的基础上的人，但他却是第—个（或是首倡者之一）认为现代的经济不可避免地趋向计划化的人，因为除社会的理由外，现代经济必须建立在科学技术的基础上。垄断经济是首先根据庞大的全国性及国际性规模而计划的经济。今天，计划经济已成为一普遍现象，也是大多数政府经济政策之一项要素，虽然在工业发达的国家与工业落后的国家中，其性质并不相同。当生产达到了先进阶段，社会的、国际的及其它条件，均面临相似趋势时，计划经济即成为必需。计划经济与任何人的理论均无多大关系，与马克思那些理论的关系更少，因为那些理论都建立在一个较低水平的社会关系及经济关系之上。
 
当苏联成为第一个着手执行全国性计划的国家时，身为马克思主义者的领袖们就将这项计划与马克思主义联系在一起，其实马克思的学说不只成为俄国革命的理想基础，而且还成为苏联领袖们后来所采取的各项措施的护身符。
 
为苏联计划经济而找寻的一切历史的及特殊的理由，是与好些理论相关联的。但因社会的基础与共产主义运动的过去关系，却以马克思的理论最为接近，也最易接受。
 
共产党的计划经济，在开始时虽极借助于马克思，但有其更深厚的意识形态上及物质上的背景。当一种经济制度已经或即将变为只有一个唯一的所有者时，如果不实行计划经济，将如何来管理其经济？如果不实行计划经济，它们又如何能进行巨额的投资，以实现其工业化的目的？必先有某事物之需要，然后它才能变成一种理想。共产党的计划经济就是这样由需要而来的理想。计划经济是用来发展那些足以巩固政权的经济部门。这是一般的规律，可是每一个共产党国家都有例外，尤其是那些不受莫斯科控制的国家更是如此。
 
由于不可能长期将生产中某一部门的进展与其它部门分开，因此，为了加强政权地位，发展整个国民经济自然极为重要。在每一共产主义制度中，计划的重点往往集中那些些对维持政权的稳定有决定性的重要经济部门。这些部门也就是那些能提高官僚集团的地位、权势及特权的部门。这些部门并且能加强这一政权与其它国家的关系，而使其工业化能达到更高的程度。到目前为止，这些部门大多是重工业及军事工业，但这并不是说，这种情形在每个国家里永远不变。近来原子能，特别是在苏联，已开始在计划中占首要地位，我认为这种情形的发生，出于军事上，外交上及政治上的考虑，要比其它考虑来得大。
 
任何事物都从属于这些目标。结果，许多经济部门显着落后，且工作缺乏效率；各种脱节与困难必然产生；而生产成本的高昂与慢性的通货膨胀更是普遍现象。据菲力浦(Andre-Philipe) 1956年10月1日在美国《新领袖》周刊上的报道：苏联对重工业的投资，已由1954年占总投资53.3%增加到1955年的60%。虽然在苏联每人平均收入的增加额中，每年从重工业方面只获得7.4%，其中只有6.4%是由于产量的增加，但苏联每年投入工业的资金占其国民净收入21%，其中大部分投于重工业。
 
在这种情形下，不难了解新的所有者为什么对于生活水平最不关切，尽管马克思本人也认为人是生产中最重要的因素。据与英国工党有密切关系的克兰克肖的报道：在苏联，每月收入在六百卢布以下的人，必须为生存作殊死的斗争，而据《纽约时报》苏联问题专家史华兹的估计，苏联有将近八百万工人，每月收入在三百卢布以下，代表英工党左翼观点的《论坛报》曾对这方面加以评论，认为这是苏联大批妇女在粗重工作中就业的原因，而与男女平等无关。最近苏联增加30%的工资，已用在这些低工资阶层。
 
这是苏联方面的情况。至于其它共产党国家的情形也大同小异，甚至像捷克斯洛伐克那样技术高度发达的国家，也是如此。过去南斯拉夫曾经是农产品的输出国，现在已变成为输入国。根据官方的统计，  南斯拉夫的蓝领与白领工作人员的生活水平竟低于第二次大战以前，当时南斯拉夫还是一个落后的资本本主义国家。
 
共产党以政治阶级利益为目的的计划经济，与其极权的独裁政治是相辅相成的。为着意识形态上的理由，共产党人对某些经济部门进行大量的投资。所有计划都环绕这些部门进行。这就导致经济上深刻的变动，从资本家及大地主手中接收来的土地建立的国营农场，其收入竟不足偿补由变动造成的损失，结果这种变动造成的损失主要反需利用低工资及用强迫收购谷物制度等榨取农民的方式来偿补。
 
有人会这样说：假如苏联不实施这种计划，不集中发展重工业，那便会赤手空拳地参加第二次世界大战而在希特勒侵略下很容易被征服和受奴役。这种就法虽属不错，但也只有某种限度的正确性。因为大炮与坦克并非一个国家唯一的力量。如果斯大林过去在对外政策上没有帝国主义目的，在对内政策上没有推行暴政的企图，那末强国集团自不会使苏联单独对付侵略者。
 
很明显，从意识形态的角度去说明计划经济与经济发展，发展战争工业并不是必要的。将此付诸实施是出于权力的掌握者需要在国内外保持独立地位；至于防御的需要，虽为一国所不可缺，只是一种附属性的需要而已。俄国如果推行不同的计划，保持与国外市场更为密切的联系，也照样可获得相同数量的军备。可是对国外市场倚赖较多，则需要一个不同的对外政策。在当前情形下，全世界利益是息息相关的，而战争也是总体性的，在发动战争时，牛油与大炮几乎是同等重要。这种情形甚至在苏联业已获得证实。由美国输入的粮食，对战争的胜利，其重要性儿与战争物资相同。
 
在农业方面，情形也是如此。在当前情况下，进步的农业也就是工业化。但进步的农业并不保证一个共产党政权不倚顿外界。它在国内将使这一政权依赖农民，即令农民是自由合作社的社员。因此，尽管集体农庄的生产极低，而在经济计划中，钢铁却占有优先地位。这由于政治权力之策划必优先于经济的发展。
 
苏维埃或共产党的计划是一种特殊类型的计划。它既非生产技术发展的结果，也非“社会主义”创始者的意识发展的结果。相反地，它是一种特殊形式的政府及所有权发展的结果。今天，技术及其它因素正在影响这种类型的计划，但这些其它因素从未停止其对这种类型计划发展的影响。这一点极值得注意，因为这是了解这一类型计划的性质，以及了解共产主义经济能力之性质的主要关键。
 
这种经济与计划能达成不同的结果。由于集中一切手段来这成某一特殊目的，因而使权力的行使者能对某些经济部门作高速度的发展。苏联在某些部门已获致的成就是世界任何地方至今所未达到的。但是，从全面的经济观点着眼，当我们考虑到其它部门的落后情况时，就看出这种突出的成就显然并不合理。
 
诚然，一度落后的俄国，就其若干最重要的经济部门而论，在世界产量方面已跃居第二位，  且成为世界上最强大的大陆国 家。一个强大的工人阶级，一个广大的技术知识阶层，以及为生产消费品所需的物资均已创造出来。独裁政治既并未因此受到多大削弱，也没有理由相信其生活水平不可能随其国家经济力量的增长而改善。
 
计划只是所有权及政治上种种考虑的一种工具，而所有权和这些考虑使计划不能丝毫削弱政治上的独裁，也不可能提高生活水平。在一个唯一的集团的完全垄断下，经济上的计划与政治上的计划都以扩大其国内及全世界的权势与利益为目的，因而继续阻碍生活水平的改善与经济的和谐发展。自由的缺乏，无疑地是这种停滞现象之所以发生的最后及最重要的原因。在共产主义制度，自由已成为重要的经济问题，同时也是一般性的问题。
 
五
共产党的计划经济掩盖着其本身内在的一种特殊类型的无政府状态。尽管共产党的经济是计划的，它可能是人类社会史中一种最浪费的经济制度。这种说法似乎很奇怪，尤其是想到其若干个别经济部门与整个经济相对的迅速发展时，更令人觉得这一说法言过其实。但这一说法却有其确切的根据。
 
一个垄断性的集团，纵然不由其狭隘的所有权及意识形态的观点考虑任何事物，包括经济在内，也无法避免惊人的大量浪费。这样一种集团，如何能够有效而节约地管理一个复杂万分的现代化经济？这一种经济，不论计划拟得如何周密，天天总是出现内部和外部种种互相冲突的趋势。既缺乏任何形式的批评，甚至没有任何形式的重要的建议，那就不可避免地要导致浪费与停滞。
 
由于此种政治的及经济的万能主义，即使是最好的意图，也无法避免浪费的行为。这些浪费使整个经济要付出多少代价，并无人加以注意。由于迷信的共产党对农民的恐惧及其对于重工业不合理的投资，而使农业陷于停滞，这对一个农业国家是多么大的损失？将资金投放在无效率的工业要付出多少代价？一个迟滞的运输系统所付代价又如何？因工资过低而致工人“偷懒”与怠工，其代价又是多少？产品质量低劣又付多少代价？所有这些代价均无人计算，也无法计算。
 
共产党领袖们处理事情的方式往往与他们自己的教条相反，那就是说，只从个人的观点出发。他们管理经济的情形也是如此。但经济是最不容忍武断行事的一个领域。即使他们希望做好，共产党的领袖们也不能顾及整个经济的利益。为了政治上的理由，统治集团常常决定什么是，“最为必需”，“最关重要”，或什么是一个运动中“具有决定性”的。任何事情都不能阻止它推行某项工作，因为这一个集团并不害怕失掉权势或财产。
 
当某些事情停止进展已很明显，或当大量浪费成为显着事实时，共产党的领袖们也不时进行批评或自我批评，并总结出经验。赫鲁晓夫曾批评斯大林的农业政策。铁托批评过自己的政权投资过多，并浪费了很多的钱。奥哈布也曾批评自己“有条件的”忽视了生活水平。但其本质依然未变。同样的人运用同样的方法继续同样的制度，直至罪行及“违法行为”昭彰为止。但损失一经发生即不能弥补，因而政权及党对于这些损失是不负任何责任的。他们曾“注意”这些错误，这些错误也应予“纠正”。于是一切又再从头干起！
 
从未看到哪个共产党领袖，因非生产性的耗费或惊人的浪费而受到处分。但许多领袖却因为“意识形态上的偏差”而遭免职。
 
在共产主义制度中，盗窃与侵吞公款是不可避免的。躯使人们盗窃“国家财产”的原因并不只是由于穷困，而事实上是由于这些财产似乎不属于任何人。—切有价值的东西都变成无价值，因而创造一种有利于盗窃与浪费的气氛。1954年，仅南斯拉夫一国即发现两万件以上的盗窃“社会主义财产”的案件。共产党的领袖们，在处理国家财产时，就像是他们自己的财产；而同时他们在浪费这些财产时又像是属于别人的。这就是共产主义制度下所有权与政府的性质。
 
最大的浪费还是那些无形的浪费。这就是人力的浪费。千百万人民在无兴趣的情况下从事迟缓而不出活的工作，加上那些被认为非社会主义的一切工作之停止进行，这些都属于可计算而不可见的巨大浪费，而这种浪费从没有一个共产党政权能够避免。即使他们是亚当斯密“劳动创造价值”学说的信徒（这一理论其后为马克思所采取），但这些权力的掌握者，对劳动及人力的使用却极少注意，认为它们不值一文，随时可以由其它事物来代替。
 
共产党对“资本主义复辟”的恐惧，以及对由其狭隘的阶级“意识的”动机所造成的经济后果的恐惧，已浪费了国家巨大的财富并阻碍财富的发展。由于国家并不能维持或发展全部工业，因而全部工业已遭受摧毁：只有那些属于国家的工业才被认为是“社会主义”的工业。
 
像这样的政策，一个国家究能推行多远和多久？起初共产主义虽然必需工业化，但随着工业化的进一步发展，就会使共产主义的政府及所有权的形式成为多余的，这一时刻即将来到。
 
由于共产主义经济的孤立性质，浪费非常惊人。每一个共产主义经济制度基本上只是一种自足性经济，其所以要达成自足的理由是由于它的政府及所有权的性质。
 
没有一个共产党国家曾经使其对外贸易超过传统商品交换的范围；甚至南斯拉夫，由于与莫斯科的冲突而必须与非共产党国家保持更广泛的合作，也未能超过传统易货的范围。与其它国家合作进行大规模的有计划生产尚未办到。
 
在共产党的计划经济中，尤其极少顾及世界市场或其它国家的生产。由于这一原因，及由于意识形态上的动机及其它动机，共产党政府极少顾及自然条件对生产的影响。他们时常建设许多工厂而无足够的原料供应，他们几乎从不注意世界的物价及生产水平。他们所制造的若干产品，其成本往往数倍于其它国家。同样地对于那些在生产力上可以超过世界的平均水平，或生产成本可以低干世界平均水平的工业部门，他们也未加注意。对一切新工业都加以发展，即使世界市场已充斥他们将制造的这类产品。为达成这种寡头专政的“独立”，这些代价都要由劳动人民来支付。
 
这是所有共产党政权共同问题之一。另一问题是“居领导地位的社会主义国家”——苏联——进行一种无意识的竞争，以期超越世界上最高度发达的国家。这一竞争要付出多少代价？并导致什么后果？
 
在某些经济部门中，苏联或能超越最先进国家。由于无限制浪费人力,由于低微的工资，及忽略其它工业部门的发展，这一点也许能做到。但在经济上是否合理，那是另一问题。
 
这样的计划本身就具有侵略性。苏联决定将钢铁及原油的生产放在第一位，而不惜降低生活水平，非共产主义世界对于这一事实不知有何看法？如果他们继续从事重工业竞争而只能进行极小额的贸易，则所谓“共处”与“爱好和平的合作”还有什么意义？如果共产丰义的经济发展成为自足性经济，并且主要是为意识形态上的理由向世界渗透，则合作还有什么意义？
 
这种浪费国内和世界的人力与财富的经济计划及经济关系，除从共产主义寡头政治的观点出发外，无论从任何角度观察，均属不合理。技术的进步与主要需要的变化，使经济中某一部门在某一时期显得重要，而在另一时期则其它部门又显得重要；无论就某些国家成就全世界来说，都是如此。如果从现在算起的五十年中，钢铁及石油丧失其今日所占的重要性，将会发生什么结果？共产党的领袖们，对于这一问题及其它许多问题，都不加考虑。
 
将共产主义经济，尤其是苏联经济，与世界其它国家联系起来，并使这些经济向世界渗透的种种努力，实在是远落于这些经济制度的实际技术能力及其它能力之后。在目前阶段，这些经济制度可以与世界其它地区进行比实际上已实现的合作大得多的合作。共产党国家之所以不能利用其能力与外界进行合作，而拼命为了意识形态理由及其它理由向外界渗透，追究其根源是在于共产党对经济的垄断以及他们必须维持本身权力。
 
列宁曾说，政治就是一种“集中的经济”，这话说得很对。但在共产主义制度下，情形完全相反，经济已成为集中的政治；即政治在经济中起几乎决定性的作用。
 
斯大林曾将苏联市场与世界市场隔离，而建立一个“世界社会主义”市场。苏联的领袖们，至今仍效忠于此项计划，这可能成为世界紧张及世界性浪费现象的主要原因。
 
所有权的垄断与生产方法的陈旧——不论是属于哪个国家或哪种形式——均与世界经济的需要相矛盾，  自由与所有权的对立已成为一世界性问题。
 
在落后的共产党国家中，废除私人或资本主义的所有权，使经济获得迅速发展——也许不是平稳的发展。这些国家已成为不平凡的新兴强国，由自大与狂妄的阶级尝着权威与所有权的果实。但这种发展并不能解决与十九世纪正统的社会主义有关  的任何问题，甚至也无法解决与列宁有关的问题，更不能保证在  不发生国内困难与动乱的情形下促使经济进展。
 
尽管共产党将权力集中在一个人的手中并在经济上也有迅速的，也许是不平衡的成就，但自从它获得全面胜利的时候起，共产主义经济制度即已暴露出很深的裂缝与弱点。虽然它还没有达到权力的最高峰，但已陷入困难局面。它的前途越来越不稳定；为着生存，共产主义经济制度必须在国内外从事激烈的斗争。

第六章  对思想的专制统治
一
虽然共产党人在取得政权时，他们对思想所施行的专制统治简直精密得如医生临床工作一样，但在共产主义的哲学里，寻找对思想专制统治的根据，也只能找到一部分。共产主义的唯物论，也许比同时代的任何世界观，都要具有更多的排它性。它把它的信徒们推向一种处境，使他们简直不可能采取任何其他的观点。假如不把这种观点同特殊形式的政府及所有权等联系起来看，则共产主义对于人类思想的可怕的摧毁及压制方法，还是不能仅由共产主义的唯物论本身就可以解释得通的。
 
任何一种意识形态或意见都企图把它自己说为唯一正确而完满的理论。人类思想的本性就是这样。
 
马克思与恩格斯理论与众不同之点，并非由于他们所提出的理论的本身，而却是由于他们运用这些理论时所用的方法。他们不承认同时代人们思想里的任何科学及进步的社会主义的价值，常常一古脑儿称之为“资产阶级的科学”；这样一来，一切认真的讨论和研究都被他们预先阻止了。
 
马克思与恩格斯有一种特别狭隘及排它的观点，从这里，共产主义后来可以抽出为它意识形态上不容异说的内容。这个观点就是：一位科学家、思想家或艺术家的政治观点，与他们作为思想家或艺术家的真实的或科学的价值，这两者之间具有不可分性。所以，假如一个人被发现属于政治上的一个敌对阵营的话，那末，他的一切其他方面的目标或工作就都应该加以反对或抹煞。
 
马克思与恩格斯的这种立场，仅能部分地解释为这是由于财产所有者以及权力掌握者剧烈反对的结果，而这种反对是在所谓“共产主义的幽灵”一出现时就激动起来的。
 
马克思与恩格斯的排他性还有另外一些东西造成并使其加强的，而这些东西是植根在他们的学识中的：他们自信已探研了各种哲学的奥秘，因此他们以为假定有谁要达到任何有意义的结论，而不以他们的世界观为基础的话，那简直是不可能的并且，由于当时的科学气氛，又由于当时社会主义运动的需要，马克思与恩格斯都渐渐以为，凡对于他们自己不重要或对于他们的运动不重要的东西，甚至在客观意义上说，也都不重要了，那就是说，凡与运动不发生关系的东西一律不重要。
 
结果，马克思、恩格斯两人进行本身的工作，并不了解同时代的许多最重要的思想，也轻视他们同一个运动内部所有与他们相反的意见。所以马克思和恩格斯的著作里没有提到过当时非常著名的哲学家叔本华，也没有提到像泰囚(Taine)这样著名的美学家。对于当时著名的作家与艺术家也没有提及。甚至于也没有说到那些追逐马克思和恩格斯所属的意识形态及社会潮流的人们。马克思、恩格斯对付他们在社会主义运动里反对者的办法完全是凭凶暴与不容异说。这对于蒲鲁东的社会学来说也许是不重要的；但对于社会主义及社会斗争的发展来说，特别在法国，却是非常重要的。同样的情形也可适用到巴枯宁。马克思在他的《哲学的贫困》一书里，除了把蒲鲁东的意见一笔抹煞外，他又轻蔑地说了好多的题外语。他同恩格斯两人以同样方法对付德国的社会主义者拉萨尔以及他们自己运动内部的其他反对派。
 
可是，在另一方面，他们却也很仔细地注意到他们那个时代的许多有意义的知识界的现象。他们接受达尔文的学说。他们特别了解过去的许多潮流——古代的及文艺复兴时代的——因为欧洲的文化就是从这里面发展出来的。在社会学方面，他们借用了英国政治经济学派的理论（亚当?斯密与李嘉图）；哲学方面，借重了古典的德国哲学（康德、黑格尔）；而在社会理论方面，则借重于法国的社会主义，或由法国大革命后所发生的潮流。上述潮流都是些伟大的科学、知识以及社会潮流，它们造成了欧洲以及世界其他地区民主与进步的气候。
 
在共产主义的发展上，显然有它的逻辑及一贯性。马克思比列宁科学一点，客观一点；而列宁主要的是一个伟大的革命家，他是在俄国沙皇的专制制度，半殖民地的俄国资本主义，以及全世界的垄断主义者的势力范围的纷争等环境中成长的。
 
靠着马克思，列宁对人说教：就全部历史说来，唯物主义是一贯进步的，而唯心主义则是反动的。这样说不仅是片面与错误的，而且它又把马克思的排它性加强起来。如此说教也是由于对历史哲学的知识不够。在1909年，当列宁写那本《唯物主义与经验批判主义》的时候，他并不十分熟悉任何伟大的哲学家，不论是古典的或现代的。而为了要战胜一切反对派，他们的观点阻碍了他的党的发展，于是列宁就拒绝了一切与马克思主义观点不合的东西。在他看来，凡不合于原始马克思主义的东两就都是错误的，毫无价值的。但必须承认，在这方面，他的著作可以说是合乎逻辑而又有说服力的教条主义的出色典型。
 
既然相信唯物主义永远是属于革命的及破坏性的社会运动的一种意识形态，于是列宁就得出了片面的结论；那就是说，唯物主义通常都是进步的——甚至在研究方面以及在人类思想的发展方面都是如此——而唯心主义则是反动的。列宁把形式和  方法同内容以及同科学发现都混为一谈。事实上只要一个人在他的思想上是唯心主义者，就已经足够使列宁把他的真价值以及他的发现的价值完全抹煞。所以，列宁把他政治上的不容异说实际上扩展到全部人类思想史的范围了。
 
欢迎十月革命的英国哲学家罗素，于1920年已准确地道出了列宁主义或共产主义的教条主义之真谛：
 
“然而，对于布尔什维主义的另一方面，我根本上持着    不同意见。布尔什维什主义不仅是一种政治上的主义；它实在也是一种宗教，具有细致繁琐的教条以及使人感悟的经典。当列宁要证明一些理论的时候，如果可能，他总是引用马克思和恩格斯的原着。一个成熟的共产主义者，他不仅相信土地及资本应该共有，而且它们的产品应尽可能地平均分配。他是抱住了一大堆有意弄成的教条式的信仰——例如哲学的唯物论——而自得其乐的人，这些信仰也许是对的，可是，就科学尺度来说，却不能确实证明它们是对的。对于客观上可疑的事情采取一种不惜一战的确信，实在是一种旧习惯，世界自从文艺复兴以来，已逐渐摆脱这种习惯，而走向建设性的以及有成果的怀疑主义的气质，而这个气质也构成科学的境界。我相信这种科学境界对于全人类是无限的重要。假如说，一个更为公平的经济制度，须先封闭了人类自由思考，而且把他们重行投入中世纪知识牢狱的深渊，方可达到的话，那末，我就认为这代价未免太高了。自然不可否认，在某一个短暂的时期之内，教条式的信仰有利于斗争。”【引自《布尔什维主义：实践与理论（ Bolshevism：  Practice  and Theo-ry），纽约，哈考特．勃雷思与霍威(Harcourt，Brace & Howe)出版公司出版．】
 
罗素所说的还是在列宁的时代。
 
到了斯大林却更进了—步，他“发展”了列宁的理论，可是他缺乏列宁的学识，也没有列宁深刻。经过—番仔细研究之后，可得到一个结论：原来斯大林，这个被赫鲁晓夫认为是当代“最优秀的马克思主义者”的人，却没有念过马克思主义最重要的著作《资本论》。他是一个讲求实际的人，再加上他持有极端的教条主义，他甚至于不需要再看一看马克思的经济研究著作，就可以建筑起斯大林牌的“社会主义”了，斯大林也不深知任何哲学家。他对于黑格尔的态度，好像他对付一个“废物”一样，硬说“普鲁士专制主义是对法国大革命的反动”的说法是黑格尔提倡的。
 
可是，斯大林却熟读列宁的著作。斯大林借助于列宁之处更大于列宁之借助于马克思。斯大林只对于政治史方面，特别是俄国的政治史，具有相当的知识，而且他的记忆力非常好。除了这些知识以外，斯大林为了扮演他那个角色，实在也不需什么更多的东西了。凡与他的需要及观点不合的，他可以一律宣布为“敌对的”，而且加以禁止。
 
这三个人——马克思、列宁、斯大林——不管是在性格方面，或在表达的方式上，都形成了强烈的对照。除了是一个革命家之外，马克思还有几分纯科学家的味道。他的作风是动人的，奇异的，豪放的，而且具有一种胜人一筹的机智。列宁呢，就简直好像是革命的化身。他的作风是热情奔放的，锋利的，而且前后一贯。斯大林则以为他的力量来自对于人类一切欲望的满足，而且以为他自己的思想就是人类思想的最高表现。他的作风平淡，单调，不过他那过分简单化的逻辑以及教条主义，对于遵奉马克思列宁主义的人以及普通人，却具有说服力。它里面也含有教会神父们著作中的简单明了的风格；但斯大林这种作风并不是他青年时代宗教生活的结果，而实在是在原始情况下，或是教条化的共产主义者的环境所产生的表现方法。
 
至于斯大林的信徒们不独缺乏斯大林本人那种粗鲁的内在凝集力，而且也缺乏他那种武断的权力与信心。虽然这些人在任何方面都是一个常人，但他们具有极强烈的现实感。既然因为他们完全为官僚政治的现实所缚，而不能产生任何新的制度与观念，那末他们唯一的本领就是窒息任何新事物的创造，或使之变为不可能。
 
这些情形就是共产主义的意识形态在其教条性及排他性方面的发展经过。而所谓“马克思主义的进一步发展”不过是导致一个新阶级及其控制权的巩固，这一控制权不只是受制于一个意识形态，甚而还受制于某一个人或寡头集团的思想。这样一来，结果就引起一般知识之衰落，以及该意识形态本身的贫乏。与这同时，对于其他观念，甚至对于人类思想本身的不能容忍的程度，也已增加。所以，该意识形态之进步，以及它的构成真理的因素，已因其信徒们实际力量的增大而相应地衰退。
 
因为愈来愈片面而排它，当代的共产主义更其不停地制造许多片面的话法，而且竭力企图为之辩护。一眼看上去，好像它的许多观念，个别的说，似乎都对。可是，其中充满谎言，不可救药。片面的东西被夸大而弄到歪曲真相的程度；而且，其中谎言的口气愈肯定、愈动人，它也就愈能加强它的领袖们对于社会的垄断,因而也就是加强他们对于共产主义理论本身的垄断。
 
二
把马克思主义当作一个放之四海皆准的法则这个基本论点是所有共产党人都不得不采取的立场，这就必然要在实际上引起在一切知识活动领域里的专制。
 
假使原子的运行是不依照黑格尔—马克思主义者的斗争规律，或不依照所谓矛盾的统一规律，而发展为较高的形式，可怜的物埋学家能有什么办法？假如宇宙的运行根本不理共产主义的辩证观，那末，天文学家又能有什么办法？假如一切植物不依照李森科—斯大林关于在“社会主义”社会里，阶级之间应该和谐及合作的理论生长，那末，生物学家又有什么办法？这些科学家们因为不能率直扯谎，他们就必须准备因他们的“邪说”的后果而受难。如果理想使他们的发现被接受，就必须使他们那些发现完全“符合”于马克思列宁主义的公式。所以科学家们经常陷于进退两难的境地，因为不知道他们的观念与发现，是否会妨害到官方的教条。因此，连对于科学，科学家们也就只好采取了机会主义及妥协的办法。
 
其他各种知识分子的遭遇也正相同。在许多方面，当代的共产主义都令人想起那些中世纪时宗教教派的排它性。有一位名叫杜契奇(Jovan nucic)的塞尔维亚诗人，在他那本《忧患与安祥》(Tuge i vedrine)里，曾经论到加尔文教派，它所谈的似乎可与共产党国家内知识分子的处境联系起来：
 
“……加尔文，这个法学家兼教条主义者，凡是他在火葬埸上没有焚化的东西，他也要使它在日内瓦人民的灵魂 里扎根。在这些人的家庭里，他引进了宗教的灾难及神圣的遁世观念，所以甚至到现在，那里也还充满着阴气森森及黑暗，他硬教人对于一切欢乐与快乐都仇恨，而且又用命令谴责诗歌和音乐。而作为一个政治家以及主宰一个共和国的暴君，他又铸造了铁一样的法律，像镣铐一样，套在全国人生活的头上，甚至管理到家庭的感情。在宗教改革运动所培养的人物中，加尔文也许是那些革命人物中最冷酷无情的人，而他所传授的圣经则是生活里最令人灰心的经文……加尔文决不是一个新的基督教使徒，他们愿望恢复基督教教义的原始的纯洁，朴素，以及柔和，宛如基督教刚从拿撒勒的天空傅播出来时的情形。原来加尔文这人却是一个亚利安的苦行僧，当他把自己和当时的政权断绝关系的时候，他也同时把自己与其所奉行的教条的一个基本原则——爱——完全断绝关系了。他另创一种人，这些人是诚恳而充满了道德，但同时却又充满了对于生活的怀恨，对于幸福的怀疑。世上没有比这更严厉的宗教，比他更可怕的先知了。加尔文使日内瓦的人民都麻木不仁，永远不可能享受任何快乐。世界上从来没有人们像这样，宗教为他们带来了如此多的灾难与悲惨。加尔文是一个卓越的宗教作家，其对于法文纯洁性的重要也就如同马丁路德之对于德文净化的重要一样，马丁路德是将圣经译成德文的人。不过，他也是一个神权政冶的创始人，而这个神权政治同罗马敌皇的王朝一样像一个独裁政治。当他宣布着他在解放人们精神人格的时候，实际上，他却在把人的世俗人格降低到最黑暗的奴役状态。他使人迷乱，而且也没有以任何方式为生活带来光明。他改变了很多的东西，但一无所成，毫无贡献。差不多在加尔文之后的三百年，也在日内瓦，法国文学家斯登达尔注意到那里的青年男女们的谈话，只谈及‘这位大牧师’及其最后一次讲道，同时，这些人如何对于加尔文的那些说教背诵如流。”
 
除此之外，当代的共产主义也包含着英国克伦威尔统治下的那些清教徒们的教条式的排它因素，以及法国雅各宾党人所表现的政治上不容异说的因素。但是，共产主义与它们之间有着许多重要不同点。清教徒绝对相信圣经，而共产党人则相信    学。共产党人的权力，比之雅各宾党人的权力，更完全得多还有，在彼此能力上也有许多的不同；向来没有一个宗教或独裁政治，能够希望获得像共产主义的制度那样的全面的无所不包的权力。
 
共产党的领袖们都相信他们已在走向创造绝对幸福的路途上，而且一个理想的社会也和他们的权力增长成比例地成长。有人讲过一句笑话，共产党领袖们已经创造了一个共产主义社会了——但只是为了他们自己。事实上，这些共产党领袖们确也把他们本身与全社会以及全社会的许多愿望都当作一体。专制主义总把自己和对于人类绝对幸福的信念打成一片，虽然它不过是无所不包，无所不在的暴政而已。
 
时代的进步已经把共产党政权掌握者变为“人的意识”的吹捧者。而在“社会主义建设”的过程中，他们对于“人的意识”的关怀随着他们权力的增加而增加起来了。
 
南斯拉夫也没有能绕过上述的演化情形。南斯拉夫有些领袖们，在革命的时期里，也曾经强调过“我们人民的高度意识”；这只是当“我们人民”或他们中间的一些人，积极拥护这些领袖们时，他们才这样说的。不过，依照南斯拉夫领袖们的说法，现在上述人民的“社会主义”意识却非常低；因而，必须等待民主政治的到来，才能把它提高起来。南斯拉夫领袖们曾公开地说及这一事实，“当社会主义意识长成的时候”，他们也就准备赐给民主，他们所信任的这种意识是可以通过工业化的途径自动达到的。在那个情形未到来之前，这些主张把民主一点一滴分批施舍给人民的理论家，其实际上所行的却是完全和民主相反，他们主张，为了未来幸福和自由着想，他们有权去阻止任何与他们不相同的其他观念或意识的存在，即使是最轻微的表现也不许可。
 
至于苏联的领袖们，只有在开始的时候，他们还不得不被迫东闪西让地允许“将来”给人民以民主。但目前他们却干干脆脆地说，这种自由在苏联已经创立了，当然，甚至他们也感到自由已在他们下面发生作用。他们不停地“提高”人民的意识，他们劝人民“生产”，他们把马克思主义的公式以及干燥无味的领袖们的政治观念，不断地填塞到人们的脑中。更糟的是，他们还不停地强迫人民承认他们对于社会主义的忠诚，并承认他们相信他们领袖们所作的一切允诺都永远不会错而且是切实的。
 
一个生活在共产主义制度下的公民，经常受到他良心痛苦的压迫，唯恐自己违反了什么禁律。他总是战战兢兢，因而他必须处处表示他不是社会主义的一个敌人，就好像在中世纪时，一个人必须时时表示出他对于教会的忠诚一样。
 
学校制度以及一切社会的与知识的活动都是促成着这种类型行为的。一个人从生到死都一直在执政党关怀之下，关怀他的意识，也关怀他的良知。新闻记者，理论家，雇佣的作家，特设的学校，批准的官方见解，以及无数的物质手段都被动员起来，被运用起来，以“提高社会主义”。说到最后，所有报纸都是官办的；无线电及其同类的东西，也都如此。
 
不过，这一切手段所收获的效果并不大。在任何情况下。效果与所花费的力量及方法都不相称，只有新阶级算是例外，不管怎样，他们总是信以为有效果的。它们已使一切与官方不同的意识都不可能表现出来，且在与相反意见斗争方面也收获相当的效果。
 
纵使在共产主义统治下，人们也还在思想，因为任何人也无法停止不想。而且他们所想的与官方所规定的想法不相同。他们的思想有两面——一面是为他们自己本身的；另一面是对公众的，对官方的。
 
甚至在共产主义制度之下，人们也还没有被千篇一律的宣传愚弄得他们不可能得到真理，得到新观念。仅就知识领域而论，寡头政治执政者的一切计划所引起的结果，是生产少，而停滞、贫污、腐化的现象多。
 
这些寡头与救主，这些以保护者自居，不让人类思想流入“罪恶的思想”或“反社会主义路线”的人物，这些贪购廉价然而却是仅有的一点消费品的不顾天良的人物——这些坚持死硬、不变的古旧观念的人物——已使他们人民的求知动力受阻并陷于冻结了。他们想出了一句最反人道的口号——“根绝人的意识”——而且他们就依照这句话去做，好像他们是在清除树根与璓草，而不是在对付人类的思想。不过，恰恰因为他们窒息了他人的意识，削弱了人类的智慧，使得人们鼓不起勇气，立不起志愿，以致后来连他们自己也变得衰老了，脑中空洞无思想，而且完全缺乏那种由无私的思考所激发的求知热情。这就弄到像一个戏院没有观众；那些演员就只好自演自唱，自己狂欢。他们的思想如同他们吃饭一样的机械：他们的脑子所以思想是应付最基本的需要。这就是今天那些共产主义说教者们的情形。他们是警察，同时也是一切传达人类思想工具——如报纸，电影，无线电，电视，书籍，以及其他同类的东西——的所有人，而且他们又是一切维持人类生活物质——如食物，以及避风雨的屋子——的所有人。
 
这么说来，难道没有理由把当代的共产主义和宗敌的教派相比吗？
 
三
虽然如此，所有共产党国家，也还是完成了若干技术上的进步，纵使这些进步是一种特殊进步，而且也只见于某些特殊时期。
 
工业化既是那样的迅速，自然要产生一大批技术知识分子：这个知识分子阶层，即使在质的方面并不特别高，可是它却可以吸收许多人才，并且也可激发发明的智慧。所以，帮助某些经济部部门加速工业化的理由，也可作为一个刺激发明的力量。在军事技术方面，无论在第二次大战中或自第二次大战以来，苏联并不落后；而苏联在原子能的发展上也没有远落在美国之后。虽然官僚制度使它难于采取革新措施，但工业技术却到底也进步了，有的时候，许多发明物要搁置在国家机关的仓库里数年之久。而生产组织的漠不关心又时常把发明力更进一步窒息了。
 
因为共产党的领袖们都是些实际人物，所以他们立刻和技师们及科学家们合作起来，而不再过多主义他们“资产阶极”的观点，这些领袖们看得很清楚，没有技术知识界的合作，工业化就不可能完成，并且这个知识界本身也不可能变为危险分子。也就和在其他方面一样，共产党人关于这个知识界也有一套过分简单化、然而却大致有一半对的理论：其他阶级对于为它服务的专家们向来都付给薪金。那末，为什么“无产阶级”或这个新阶级，不可以也这样做呢？根据这种论点，他们立即就发展一种工资制度。
 
尽管他们有技术上的进步，事实上在苏维埃政府之下，并没有获得任何伟大的现代科学发明，仅就这一点而论，苏联还可能不及沙皇时代的俄国，那时候，虽然在技术上极为落后，但确有许多划时代的科学发现。
 
即使技术上的原因使科学发明非常困难，可是这个困难最主要的理由还是社会性的。这个新阶级非常注意，务必使它对于意识形态的垄断不致受到危害。而每一个伟大的科学发明是那个发明者思想上先有一个改变了的世界观的结果。一个新的观念往往对于已经被采取的官方哲学并不合适。在共产主义制度下，每一个科学家都必须悬崖勒马，以免他的理论不符合于规定的需要的教条而被宣布为“异端”。
 
同时，使发明工作变得更为困难的是迫使人们相信官方的见解，即马克思主义或辩证唯物论，是一切科学、知识以及其他活动的领域里一个最有效的方法。在苏联，从来没有一个著名的科学家没有碰到过政治上的麻烦。这有很多的原因，但有一种原因是因为与官方的路线相对立。在南斯拉夫，这类事发生较少；而相反地，却有许多例子证明对于那些“忠诚”的、然而低劣的科学家们有偏爱。
 
共产主义制度刺激了技术上的进步，但也妨碍了每一伟大的研究活动，由于思虑的不受干扰是研究活动的必需条件。听起来这些话也许有点矛盾，但事实确是如此。
 
虽然共产主义制度相对地阻碍科学的发展，但它们却绝对地阻碍任何知识的进步及发现。这个制度以一个派别哲学的排它性为根据，显然是反哲学的。在这个制度里面，从来没有产生过，也不可能产生出一个思想家，特别是一个社会思想家——这里不把那些专权的人物算在思想家内，虽则他们一般说来也是“主要的哲学家”和“提高”人的意识的大师。在共产主义中，一个新的思想，或一个新的哲学及社会学说，必须要循着间接的途径表达出来，通常是经过文学或某些艺术部门的途径。为了要能在世界上露面并开始生存下去，任何新的思想必须第一步先把自己隐藏起来。
 
在所有科学部门和所有思想之中，社会科学以及对于许多社会问题的考虑往往遭遇最坏的命运；它们很难生存下去。只要它是个社会问题，它的每一部分都必须依照马克思及列宁的理论，或依照领袖们所垄断的理论来解说。
 
历史，特别是关于它自己——即共产主义的——这个时期的历史，是不实在的。史实的随意删略与假造，不独是被允许的，而且也是普遍现象。
 
人民的知识遗产也被没收了。这些堑断者的举动好像在表示着，一切历史之所以发生，只是要让他们这些人自己出现在世界之上。他们以自己的类型及形式来衡量过去以及过去的每一件事，而且他们又用一个划一的尺度把所有的人类及各种现象都分为“进步的”与“反动的”两大类。就在这种方式下，他们竖立了纪念碑。他们抬高了侏儒，毁掉了伟大人物，特别是与他们同时代的伟大人物。
 
他们所用的“唯一科学”方法对他们自己确是非常适宜的，因为这个方法可以保护并为他们对于科学与社会的包办控制辫护。
   
四
同样的事情也发生在艺术方面。在这里，对于已经确定的形式和平庸的观点越来越偏爱，这是可以了解的：  因为没有任何艺术不具有它的思想，或不具有对于意识的相当影响。可是统治者的先决条件却是对于一切思想的垄断，塑造意识。在艺术上，共产党人是传统主义者，大部分因为他们需要继绩垄断人民的思想，但也因为他们的无知及偏见。他们之中有些人，在现代艺术上，也容忍某种民主的自由，不过这却仅仅是他们承认对于现代艺术的不懂，所以认为必须容忍一点。列宁当时对于未来派诗人马雅可夫斯基就是抱着这样的感觉。
 
虽然如此，可是那些落后的民族，在共产主义制度下，除了技术的复兴之外，却也能体验到一种文化复兴。文化虽然大部分以宣传的形式出现，但人们接触文化的机会总可可以较多。新阶级本身也对文化传播很注意，因为工业化提出需要质量更高的作品以及需要扩大求知的机会。于是学校以及职业性的艺术机构就都发展得非常快，有时甚至超过了实际需要及可能。所以，艺术上的进步是不可否认的。
 
一次革命以后，在统治阶级还没有建立完全的垄断之前，许多有意义的艺术品通常却已经创造出来了。在二十世纪三十年代以前的苏联就是这种情形；当前的南斯拉夫也是如此。这情形好像是革命把蛰伏着的天才唤醒了起来，纵使那个由革命所产生的专制主义对艺术的窒息已愈来愈强。
 
窒息艺术的基本方法有两种：一是对于艺术的知识与理想主义方面的反对，一是阻止艺术形式的改革。
 
苏联在斯大林时代，事情已经发展到这种地步，就是除了斯大林自己所喜欢的以外，其他的一切艺术表现形式都被禁止。同时，斯大林的鉴赏力并不很高明，他耳朵听不大清楚，他又偏爱八音节和亚历山大式的诗歌。杜次溪( Deutscher)说过，斯大林的文体变成了全国的文体。在艺术形式上采用官定观点，与采用其他官定思想一样，都是无所选择的。
 
不过，虽在共产主义制度下，也并非永远如此的，而且也并非不可避免必须这样做。苏联在1925年曾经通过了一项决议案，其中这样说：“在文学形式的领域内，以整个党来说，决不只致力于一种目标”。可是党并不因此放弃所谓“意识形态的帮助”，就是说，党不放弃它对于艺术家们的意识形态及政治上的控制。这就是在艺术领域里，共产主义所达到的最大限度的民主了。南斯拉夫领袖们今天的处境也相同。1953年以后，开始舍弃民主形式、实施官僚制度的时候，那些最原始与最反动的因素就得到了鼓励；对于“小资产阶级”知识分子的疯狂迫害开始了，它的公开目的就是在于控制一切艺术的形式，转瞬之间，整个的知识界都一变而为反现政权了。因此，政府不得不退后一步，通过卡德尔的一次演说，宣布党并不规定艺术形式的本身，可是它不能允讨“反社会主义意识形态的违禁品”出现，那就是说，当局不允许它认为“反社会主义义”的观点出现。布尔什维克党曾经在1925年采取过同样的立场。这就构成了南斯拉夫政府对于艺术所定的“民主”限度。但在南斯拉夫领袖们中，大多数人的内心态度却并没有因此有所变更。在私底下，他们仍然认为整个知识界及艺术界并“不可靠”，有“小资产阶级”意识，或用较温和的话来说，就是“意识形态的混乱”。南斯拉夫最大的报纸（《政治报》）1954年5月25日曾经引用过铁托的一句“令人难忘”的话：“一本好的教课书比一本小说有价值得多”。接着发现了有周期性的狂热攻击，不断地攻击艺术里所谓“颓废”，“破坏性的观念”，以及“敌对的观点”等等。
 
与苏联文化不同，南斯拉夫文化至少已经隐盖了，而不是摧毁了关于艺术形式上许多不满及激烈的意见。这在苏联文化里从来就没有可能。南斯拉夫文化的上面只是吊着一把剑，但在苏联，这把剑却早已刺进了文化的心脏。
 
相对的自由形式是存在的，因为共产党人只能间歇地加以镇压，不过这种自由不可能完全使一个富于创造性的人自由。艺术必定通过形式本身来表现新的观念，纵使表现的方法是间接的。在共产主义制度下，虽然艺术可以享有最大的自由，但在它所被允许的自由形式，与政府对于一切观念的强迫控制之间，却存在着无法解决的矛盾。这种矛盾常常要暴露出来，有时出现在对“违禁品”观念的攻击中，有时出现在艺术家的作品里，因为它们被迫用某些特殊的形式。它之所以暴露，主要的是因为政府的无限垄断主义愿望以及艺术家们难以抗拒的创作愿望之间存在着冲突。实际上，这也是存在于科学的创造性与共产党教条主义之间的冲突；不过现在它被转移到艺术的园地里来了。
 
任何新的思想或观念，都要先在内容方面检查一番，批准或不批准，然后再装到一个无害的框子里去。正如对其他的冲突一样，共产党的领袖们对于这个冲突也无法解决。不过，如我们所已经看到过的，他们却可以时时自己脱身出来，通常是以艺术创作的真自由作为牺牲。在共产主义制度里，由于这个矛盾，以致不可能发展出真的艺术作品，也不可能发展出艺术理论。
 
一件艺术品，在它本质上，通常就是对于某一特种情势或对某一特种关系的批评。因此，在共产主义制度下，任何艺术的创作，如想以实际题材为基础，那简直是不可能的。只有对于某一特种情势的称颂，或对于现制度反对者的批评，是被允许的。在这些条件下，艺术是不会有什么价值的。
 
在南斯拉夫，许多官员及若干艺术家都在埋怨，为什么南斯拉夫没有任何足以表现“我们的社会主义现实”的艺术作品。可是另一方面，在苏联却创作出无数的艺术作品，它们都是以实际题材为基础的；不过，这些作品却并不如实地反映真像，所以它们没有什么价值而很快地为群众所唾弃，过后甚至也为官方所批评。
 
南斯拉夫与苏联所用的方法虽不同，但最后的结果则完全一样。
 
五
在所有的共产党国家中现在都流行着所谓“社会主义现实主义”论。
 
可是在南斯拉夫，这个理论已被粉碎，现在仅有最反动的教条主义者仍在坚持着它。在这里，也如在许多其他方面一样，政权本身是有力量阻止任何不同意的学说发展的，但它却没有力量把自己的观点强加于人。其他东欧国家的情形也可以说是一样。
 
“社会主义现实主义”甚至不是一个完全的理论体系。高尔基是首先用这个名词的人，也许是由自己的现实方法所激发起来的。他的观点是说，在不成熟的当代“社会主义”情形下，艺术必须以新的或社会主义观念为灵感，而且必须尽可能地忠实的描写现实。这是它原始的意义。后来，愈来愈多地带有许多其他的意义了——如典型观念，强调意识形态，党的团结等等——这些是由其他理论中借来的，或是硬加进去的，都是为了要满足共产党政权政治上的需要。
 
因为没有发展成为一个完整的理论，所谓“社会主义现实主义”，在实际上的意义不过是共产党人对于意识形态的垄断而已，它所要求的不过是以艺术的形式把领袖们的狭隘与落后的许多思想加上一层外衣，并且把他们的工作用浪漫的、歌功颂德的笔调加以描写而已。这就被利用来作为官方对于思想控制和有必要对艺术本身进行审查的借口。
 
这种控制所采取的形式，在各共产党国家里，也彼此不同，由党及官僚检查制起，一直到通常的意识形态的影响为止。
 
例如，南斯拉夫就从未有过检查的制度。它用这样的方法来间接施行控制：在出版业，艺术家协会，定期刊物，报纸等方面，党员把任何认为“可疑的”东西，提交有关当局。从这种气氛里所产生的就是检查或事实上的自我检查。即使党员们可以贯彻他们的某些主张，但因为他们和许多知识分子一样必须进行    自我检查，所以他们必须伪装自己的言行并且说些毫无价值的吞吞吐吐的话。但这个现象却被当为进步，当为“社会主义的民主”，而不当为官僚专制。
 
不管是在苏联也好，或在其他共产党国家也好，检查制度之存在不能免除创作的艺术家们进行自我检查。知识分子们为他们的地位及社会关系的实际情况所迫，不得不进行自我检查。自我检查，在共产主义制度下，实际就是党在施行意识形态控制时的一种主要方式。在中世纪时，人们一定先要探究一下教会对他们工作的想法；而在共产主义制度下的情形也一样，人们必须首先想象政府需要那一种工作，或是先去探一探领袖们的口味如何。
 
检查，或自我检查，都被说成是一种“意识形态的帮助”。同样的，共产主义里的每一件事都被说成致力于实现绝对幸福。因此，许多名词如“人民”，“劳动人民”，以及其他类似的名词，虽然含义很模糊，也常常被引用到艺术方面。
 
不管是什么，如迫害，禁止，将形式与观念强加于人，屈辱，侮骂；又如，像那些半文盲的官僚们所加于天才们的学究式权威；这一切都是在代表人民或为人民的名义下进行着的。甚至在名词的运用上，共产党的“社会主义现实主义”与希特勒国家社会主义也无什么不同。有一位名叫辛科的祖籍匈牙利的南斯拉夫的作家，曾经把两种独裁制度下所谓“艺术”的理论家的话，作过一次有趣的比较：
 
苏联的理论家铁木非也夫在他那部《文学理论》里写着：“文学是一种意识形态，它帮助人们熟悉生活，帮助他认识他本身是在参加生活。”
 
而《国家社会主义文化政策的要义》上宣称：“一个艺术家不可能仅是一个艺术家而已，他也永远是一个教育家。”
 
希特勒青年团的领袖锡拉黑(Baldur von  Schirach)却如此说：“每一件真的艺术品适用于全体人民。”
 
苏联共产党中央委员会政治局的委员日丹诺夫说过：
 
“任何有创造性的东西都是为大家所可了解的。”
 
而在上述《文化政策的要义》里，舒尔兹(WolfgangSchulz)说：“国社党的政策，甚至它那被称之为文化政策的部分，都是由领袖自己或由其所授权的人们来加以决定的。”
 
假如我们要了解，国社党的文化政策到底如何，我们必须研究这些人物，研究他们为了教育他们的负责同僚，他们做了些什么和他们曾经发出些什么指示。
 
在苏联共产党第十八次代表大会上，雅罗斯拉夫斯基曾经说过：“斯大林同志给艺术家们以灵感，给他们以指导的思想……而苏共中央委员会的决议以及日丹诺夫的报告给予苏联作家们一套完整的工作程序表。”
 
凡是专制政治，即使是相互反对的制度，总是用同样的方法为自己辩护，他们甚至免不了用同样的字句来辩护。
 
六
作为一个以科学名义仇视思想的敌人，作为一个以民主名义反对自由的敌人，共产党的寡头集团所能完成的，不过是人类心灵之完全腐化而已。资本家巨头或封建贵族，常常依照自己的能力及愿望，来供养艺术家及科学家，因而既帮助了他们，却也腐化了他们。在共产主义制度下，腐化是国家政策不可分割的一部分。
 
一般说来，共产主义制度就是窒息并压制任何它自己不同意的求知活动；那也就是说，窒息并压制一切深刻的及富于创造性的东西。而在另一方面，凡是它以为有利于“社会主义”也即共产主义制度本身的东西，它都要加以奖励，而实际上也就是以收买的方法去腐化。
 
即使不谈如“斯大林奖金”之类的，隐蔽而激烈的收买手段，利用个人与当权者之间的联系，高级官僚们的滥肆要求与收买等等——这一切都是共产主义制度下的极端的情形——事实还是存在的，就是说这个制度本身确实使知识分子，特别是艺术家腐化。政府的直接奖金也许可以废除，也好像检查制度是可以废除一样，但它那种腐化及压制的精神却依然保留着。这种精神，是由党官僚垄断物质及心灵所建立和刺激起来的。知识分子们走头无路，不管为了思想或为了利益，他们都只有向当权者靠拢。纵使这个权力并不直接掌握在政府的手里，它也还是渗透到所有的机关和组织的。说到最后，一切决定都是由它作的。
 
对于艺术家来说，虽然他的社会地位也许不会因此而引起什么变更，但限制及集权主义的实施总以愈少愈好，这一点是非常重要的。因此，艺术家在南斯拉夫工作和生活，比在苏联要容易得多了。
 
一个遭受压迫的心灵不得不被迫腐化。假如一个人要想知道，为什么二十五年来，在苏联并没有产生任阿有意义的作品，特别是在文学方面，那末，他将发现，比起政府的压制来，腐化及收买政策对于作品稀少的影响，还要更大一点。
 
共产主义制度迫害，猜疑，以及刺激那些真有创造性的人们，使他们不得不从事自我批评。它给那些阿谀的人们以各种富有吸引力的“工作条件”与滥用的荣誉或头衔，奖金，别墅，休假中心，购物优待，汽车，大使级地位，宣傅鼓动的保护，以及“宽宏大量的干预”。因此，在原则上，它是偏爱那些无才的，寄生的以及缺乏发明能力的人物。同时，可以理解，许多伟大的思想家都已失去了他们的方向，信心以及力量。自杀，失望，纵酒，淫荡以及内心力量与人格完整之丧失等等都是因为艺术家被迫不得不对自己以及对他人说谎的缘故——所有这一切是在共产主义制度下最常见的现象，都可以在那些真正愿意从事创作、而且也具有创作能力的人们身上发现。
 
七
通常以为共产党的独裁是在实行一种野蛮的阶级歧视。这个说法不是完全准确的。从历史过程来看，当革命松懈的时候，阶级歧视随之衰退，而意识形态的歧视却反而增加。  目前有一个错觉，即是无产阶级已经当权，这个看法是不对的，同样的，以为共产党之迫害什么人，全因为他是一个资产阶级，这看法也不对。固然共产党的政策确是在极严厉地对付旧统治阶级的分子，特别是资产阶级分子。不过，凡是投降了的，改变了方向的资产阶级分子也能得到报酬优厚的位置与照顾。更重要的一点，就是秘密警察可以在他们里面物色到能干的密探，而新政权掌握者则可以找到他们能干的仆人，只有那些在意识形态上不赞成共产党的措施和观点的人们才会遭到惩处，并不考虑到他们的阶级，或他们对资本家财产的国有化政策的态度。
 
在共产主义制度下，对于那些与统治的寡头集团不同的民主与社会主义思想的迫害，比起对于以前旧政权最反动的信徒的迫害，却要更严厉，更完全得多。这是可以了解的：因为后者所具有的危险较小，他们只向往于过去，而过去则很少有卷土重来的可能。
 
当共产党人取得政权时，他们对于私有财产权的攻击造成一种错觉，以为他们的措施主要是为了工人阶级的利益来反对有产阶级。后来许多事件却证明他们的各种措施并不是为了这个目的，而是为了建立他们自己的所有权。所以，共产党自己所有权的建立这什事，必须主要在意识形态的歧视方面，而不是在阶级歧视方面，加以表现出来。反之，如果这个看法不对，如果共产党确也为劳动大众真正所有权的建立而奋斗，那末，阶级歧视确是应该流行下去的。
 
既然意识形态的歧视流行是事实，那末初看上去，就应该得出一个结论：这就是一个新的宗教教派已经出现。这个教派坚持着它自己的唯物主义及无神论教条，而且把它们强加于人。共产党做得确也像一个宗教的教派，虽然事实上他们并不是。
 
这种极权主义的意识形态不止是某种政府形式和所有权形式造成的结果。意识形态本身这方面也诚然为这些政府及所有权形式的产生帮了忙，而且也在用一切方法去支持它们。意识形态上的歧视是共产主义制度继续存在的一个先决条件。
 
如果以为其他各种歧视——如种族，等级，以及民族——都比意识形态的歧视还要坏，那就看错了。这些歧视在表面上似乎更野蛮一点，它们却并没有那么细放，那么完全。它们的目标只是在于各种社会活动，而意识形态歧视则以整个社会为目标，而且以每一个人为目标。其他类型的歧视可以在物质上粉碎人类，而意识形态则对准人类的命根加以打击，这个命根或许是为人类所特有的。对于思想之专制统治，是最完全与最残酷的专制统治形式。任何其他种类的专制统治则以思想专制统治始，以思想专制统治终。
 
共产主义制度下的意识形态的歧视，一方而它是以禁止其他不同的思想为目的，而另一方面，以把自己的思想武断地强加于人为目的。这两种形式都是最惊人的，令人难以置信的极权专制形式。
 
思想本来是一个最富创造性的力量。它揭开了新的事物。人们如果不思想或不考虑，他们就既不能生活下去，也不能生产。虽然共产党人口头上可能否认这个真理，但他们却不得不被迫在实际上接受它。这样一来，他们就使得除了他们自己的思想之外，其他任何思想都不可能得势。
 
一个人可以放弃很多的东西。但他却必须思想，而且具有把他的思想表示出来的深切需要。当有表现需要的时候而被迫保持缄默，这是非常令人难受的。专制统治最恶劣的表现就是在于它强迫人们不要像平常那样去思想，强迫人们表达不是他们自己的思想。
 
思想自由的限制不仅是对于某些特定政治及社会权利攻击而已，而且它是对于人类本身的一种攻击。不过，人类对于思想自由不可磨灭的愿望却永远是可以在具体形式下表示出来的。假使这些愿望，在共产主义制度下还没有明显表示出来的话，那也绝非说它们就不存在。今天它们存在于那些暗中的消极抵抗之中，存在于人民还没有成形的希望之中。看上去好像是，由于压制的全面性，它已把全国各阶层之间的差别都抹去了，它把所有要求思想自由和一般性自由的人们都团结起来了。
 
历史也许可以原谅共产党所犯的许多罪过，并承认他们有时确是被迫采取许多残暴的行为的，由于环境的关系或是由于保卫他们本身存在的关系。不过，共产党对于各种不同思想的窒息，以及为了保护他们自己私人利益对思想所采取的专横的垄断，这些罪行，将把共产党人钉在历史上耻辱的十字架上。

第七章  目的与手段
一
一切的革命与一切的革命者，都充分使用强迫的、不顾是非的手段。
 
但是，以前的革命者不像共产党人那样明白自己是在使用不顾是非的手段。他们也不像共产党人那样通权达变。
 
“对付运动中的敌人，你可以不挥手段。……你不但要惩治叛逆，也要惩治那些冷淡的人，你必须处罚一切在共和国里不积极的人，一切不替共和国效力的人。”
 
圣鞠斯特( Saint-Just)的这一番话，也可能出诸今日某些共产党领袖之口。但圣鞠斯特是在法国大革命激烈时讲这番话的，是为了维护大革命的命运。而共产党人却经常讲这种话，并依照这种话而行动——由他们开始搞革命直至攫得全部政权，始终如此，甚至在他们衰败时也还是如此。
 
共产党人的手段虽在应用范围，持续时间、与严酷程度上都超过了其他革命者所运用的任何手段，但在革命期间共产党人通常并不使用敌方所用的一切方法。纵使共产党人在革命期间，使用的方法或许不太残忍，可是，他们离革命越远，他们所用的方法也就越不人道。
 
正如每一场社会运动与政治运动一样，共产主义所使用的手段首先必须适合于共产党内当权集团的利益和他们的相互关系。其他一切考虑，包括道德上的在内，全是次要的。
 
在本章内，我们只谈当代共产主义所使用的手段，这些手段可以依情况的不同，有时温和，有时严峻，有时合乎人道，有时不人道；但和别的政治运动与社会运动所用的手段是有差别的。共产主义所运用的手段并使共产主义和其他运动——无论是革命的或非革命的运动——迥然不同。
 
不同之处，并非在于共产党的手段或许是有史以来最残暴的手段这个事实。残暴固然是共产党的手段的最显着特性，但还不是最根本的特性。一场运动既抱定目的要用专制手段来变革经济制度与社会制度，自然非常残暴方法不可。但其他一切革命运动也不得不使用或打算使用同样的方法。可是，这些革命运动中的专制时期比较短，这一事实就足以说明它们不可能使用共产党所使用的全部残暴手段。而且，它们的压迫也不能像共产党人那么全面，因为，它们施行压迫时的情况就不准许他们把压迫施行得像共产党人那样全面。
 
共产党人虽缺乏伦理的或道德的原则，但若以这个事实为理由来说明共产党人的不择手段，就更加说不通。除了他们是共产党人这一点与他人不同外，他们也是和其他一切人一样，其他的人在彼此关系上是受人类社会习以为常的道德原则约束的，共产党人也是如此。共产党人彼此间缺乏伦理，并不是他们所以使用那一套手段的原因，而是使用那一套手段的结果。共产党人无论在原则上或言词上都赞成伦理观念与人道方法。他们相信自己是“暂时”被迫采用一些违背自己伦理见解的手段。他们也想到：如果自己不曾被迫采取违背自己伦理见解的行动，一定要好得多。除了他们以更长久而丑恶的方式背离人道外，在伦理观点上他们和别的政治运动的参与者并无很大的差别。
 
当代共产主义和其他运动在使用手段上之所以有差别，还有许多别的特征。这些特征主要地是数量上的，或是由不同的历史条件以及共产党人的目的所造成的。
 
但当代共产主义有一项主要特征，它使共产主义所用的方法和别的政治运动所用方法迥然不同。骤然看去，这特征似和过去某些教会的特征相仿佛。它溯源于共产主义者要用一切手段以求促进其理想主义的目的。等到目的变为无法实现时，手段也就越来越粗暴。即使是为了达到理想主义的目的，他们所用的手段也是不能用任何道德原则来便辩解。谁运用了那一套手段，谁就是横行不法、残虐不仁的弄权者。以前的阶级、党派与所有权的形式虽不再存在或已无能为力，但手段并无根本改变。事实上，这些手段在目前正淋漓尽致地发挥其残暴性。
 
这个新的剥削阶级爬上政权的宝座后，打算抬出它的理想主义的目的来替非理想主义的手段作辩护。斯大林建设他的“社会主义的社会”时，所用手段的残暴达于极点。由于这个新阶级必须表现得好像它的利益就是整个社会的唯一而理想的目的，由于它必须保持知识方面的以及其他方面的垄断，这个新阶级必须宣称它所使用的手段是不重要的。它的代言人喊叫道：目的才是重要的，其他一切都算不得什么。重要的是我们现在“有了”社会主义。共产党人就这么替专制、卑鄙与罪恶作了辩解。
 
当然，目的必须由特殊的工具——共产党——来保证。党就成了一种居于统治地位的妄自尊大的东西，就像，中世纪的教会一样。这里且引凡尔登名誉主教第揣克?冯?尼亭( DietrichVon Nieheim)在1411年所写的一段话：
 
“当教会的存在遭到威胁时，它就不受道德律的约束了。以统一为目的，可使一切手段——无论其为不忠、背信、专制、买卖圣职、监禁或之人于死地——都变成了正当的行为。因为每一项圣职都是为了全社会的目的而存在的，个人必须为总善而牺牲。”
 
这一番话听来也好像是当代某些共产党人的口气。
 
在当代共产主义的教条主义中，有很多东西是封建的，盲信  的。然而我们既不是生活于中世纪，当代共产主义也不是一个  教会。当代共产主义强调意识形态上的与其他方面的垄断，这  不过使它自己颇像中世纪的教会；  两者的本质是各异的。教会  只享有部分的所有权与统治权；充其量，它曾想通过对于心灵的  绝对控制来使一个既定的社会制度永存不灭。教会曾迫害异教  徒，甚至只是为了教条上的理由，在实际上并无直接的需要。但  据教会宣称，这种迫害是想毁灭异教徒的身体，借此来挽救他们  罪恶的、异端的灵魂。为了进入天国，一切世俗的手段都被认为  是可取的。
 
而共产党人却首先要求实质上的或者说国家的权威。至于  为了教条上的理由而实施思想上的钳制与迫害，不过是为了加  强国家权力而作的辅助性举动。共产主义不同于教会，它不是制度的支持者，它是制度的化身。
 
这个新阶级并非突然兴起的，而是由一个革命的集团发展  为一个掌握所有权的反动的集团。它所使用的手段似乎前后相  同，实质上也已由革命的手段变成了暴虐的手段，由保护性手段  变为专制的手段。
 
共产党人的手段在实质上是非道德的与不讲是非的，甚至  它在形式上特别峻刻时也是如此。由于共产党的统治是十足极权主义的，它不容多择手段。这种“不容多择手段”的境况是共产党人所无法废弃的根本情况，因为共产党人要保持绝对权力与他们自私的利益。
 
共产党人必须——即令他们并不想如此——身兼二职：既是所有权者又是暴君，且必须为着这一目的而运用许多手段。尽管共产党人可能具冉巧妙的理论或良好的倾向，但制度的本身非驱使他们去运用一切手段不可。只要遇有紧急情况，共产党人总是以道德的及智识的维护者自居，同时又是用尽一切可用之手段的实际家。
 
二
共产党人大谈其“共产主义道德”、“社会主义新人”以及诸如此类的概念，仿佛自己在谈着一些较高的伦理上的范畴。这些迷迷糊糊的概念只有一种实际的意义——团结共产党员并抗御外来的影响。但若当作实在的伦理范畴看，这些概念根本不存在。
 
既然不能出现特殊的共产主义的伦理或什么“社会主义人”，于是共产党人自己所培养出的划分等级的风气、特殊的道德概念与其他概念就更为强有力地发展开了。这些不是绝对的原则，而是一些随时在变化的道德标准，深植在共产党阶级森严的制度中，居高位者（上层圈子）可以任意做一切事情，但同样的事若是下级人员（下层圈子）做了，就要受到处罚。
 
这种可变曲、不完备的划分等级的风气和道德，已经历过漫长而多样的发展过程，甚至往往刺激这个新阶级作进一步的发展。这一发展的结果是替各个不同的等级产生了各自特有的一套道德标准，所有这些道德标准都服从于寡头政治的实际需要。这些等级性伦理的形成大体上是和这个新阶级的兴起相一致的，它的形成也就是这个新阶级对人道的真正伦理标准的摒弃。
 
以上各命题需要群尽的说明。     
 
像共产主义的其他各个方面一样，等级道德也是由革命道德发展出来的。起初，这种道德虽是一个孤立的运动的一部分，但共产党人宣称它比任何别的派别或阶级的道德更为合乎人道。可是共产主义运动在开始时总像是一种具有最高的理想主义，并能作最无私的牺牲的运动，吸引全国最有才能的、最勇敢的人，甚至最卓越的知识分子，到它的行列里来。
 
这一项说明，正如本章中所提出的其他大部份说明一样，是指那些共产主义绝大部分是由于本国的情况而发展起来并获得了充分权力的国家（俄国、南斯拉夫与中国）。但把这项说明稍作修改后，也可以适用于其他国家里的共产主义。
 
无论在哪里，共产主义开头总是一种对于美丽的理想社会的愿望。因此，它吸引着鼓舞着具有高度道德水平以及其他方面出类拔萃的人们。但由于共产主义又是一种国际性的运动，它就像向日葵朝着太阳一般地倾向于运动的力量最强大的地方——至今为止主要是苏联。结果，即令是在别的国家里并未取得政权的共产党，也丧失了它们开头时所具有的特性，而取得了弄权的共产主义的特性，因此，西方各国以及其他地方的共产党领袖，都习惯于像苏联的共产党人一样，满不在乎地玩弄真理与伦理原则了。每个地方的共产主义运动在开头时也都有高尚的道德特性，个别的人员可能保持这些特性更为长久，而当共产党的领袖们采取非道德的行动和一意孤行的转向时，上述高尚的道德特性便会引起危机。
 
有史以来，像共产主义这样的运动并不很多。它开始进行时有那种崇高的道德原则，它的斗士都忠贞、热诚而能干，他们相依为命，不只由于志同道合，甘苦与共，并且由于无私的爱、友谊、团结一致，以及只有在不成功即成仁的战斗中才会产生的那种战友们的温暖与赤诚。彼此协力合作，同德同心；甚至以最大努力达到相同的思想感情；  通过全心全意献身于党和工人集体以寻求个人乐趣并建立各自人格；为他人而热诚地牺牲自己；敬老扶幼；……这一切都是运动刚起头时或运动仍名副其实时真正的共产主义者的理想。
 
女共产党员也不仅是一个同志或战友。我们决不可忘记，她在加入这个运动的时候已经决定牺牲一切——爱情与母性的乐趣。在这运动里培养出一种男女之间的纯洁、朴实而又温暖的关系，本着这种关系，同志间的关切已成为不分性别的爱。忠诚、互助、连最秘密的心事也坦白表露出来——这些通常都是真正的、理想的共产主义者的理想。
 
但只有当共产主义运动还年青、还没有尝到权力的果实时才真是这个样子。
 
通向这些理想的道路是非常遥远而崎岖的。共产主义者与共产主义运动是由各种各样的社会力量与中心形成的。内部的统一不是一朝一夕之间达到的，而是通过各种各样的集团与宗派的猛烈斗争才达到的。如果情况顺利，获胜的那一个集团或宗派就是最了解向共产主义前进的集团，在它接收权力的当时，也是最讲道德的。经过道德危机，经过政治阴谋与阿谀逢迎、互相诽谤、无缘无故的仇恨与野蛮的冲突，经过放荡淫乱与心智堕落，共产主义运动的前进就缓慢了。在这个过程中，它摧毁了许多集团与个人，丢弃了不必要的东西，锻炼出它自己的核心与教条、道德与心理、气氛以及工作态度。
 
当共产主义运动及其追随者真正地革命时，他们曾一度达到了本章所描述的崇高道德标准。在这段时期内，共产主义的言与行是很难划分的，更精确地说，这时候居于领导地位的、最重要的、最真实的、理想的共产党人诚挚地相信他们的理想，并渴望把这些理想在他们的工作方法与他们个人的生活中实现。
 
这段时期，是在夺取政权的战斗的前夜，只有当各地的共产主义运动达到了这样一个独特之点时，才会有这样的阶段。
 
固然，这些只是一个派别的道德，但确是高标准的道德。共产主义运动是孤立的，它常常看不到真理，但不能说这运动就不是以真理为其目的，也不能说它不爱真理。
 
内部的德与智的融合，是为意识形态与行动的统一而作的长期斗争的结果。没有这种融合，真正的共产主义革命运动简直想都不用想。若无心理，道德的统一，“思想与行动的统一”是不可能达到的。反过来也是一样。但这种心理与道德上的统一——从来不曾有什么法令规章对此作过规定，但它却自动发生，成为一种风气与自觉的习惯——其功劳比什么因素都更大，它使共产党成为一个无法摧毁的大家庭，使外人既无法理解又无法渗入这个党，使党的团结牢不可破，使全党的反应、思想与感情归于一致。这种心理与道德上的统一之存在——它不是一下子就达成的，而且若不是渴望形成它，它便不会形成一一是比什么都更可靠的征象，足以说明共产主义运动已站稳脚跟，它已不是它的追随者和其他许多人所能抵抗的，它是强有力的，因为它已把整个党融为一人，一心、一体。这也就证明一个新的、纯一的运动已经出现，它所面对的前途完全不是它在起头的时候所预见的那个前途了。
 
可是这一切，在共产党人一步步取得全部权力与所有权的过程中，慢慢地消失了，解体了，浸没了。剩下来的只是空无所有的形式与毫无实质的仪节。
 
至此，在共产主义运动对反对派与半共产主义集团的斗争中所产生的磐石般的内部团结，一变而为运动内部卑屈顺从的谋士们与机器人似的官僚们的团结一致。当共产党爬上政权时，偏狭、卑躬屈膝、不完整的思考、控制个人生活——在过去，此举一度是同志般的帮助，但现任却成为寡头支配的一种方式一一等级的森严与各顾私利、妇女作用的徒有其名和受到忽视、机会主义、自我中心主义以及暴行就压制了一度存在的崇高原则。旧时存在于孤立运动中的奇异人性，慢慢转变为特权阶级的偏狭而伪善的道德。于是，阴谋诡诈与卑躬屈膝代替了以往革命者的正直。昔日曾经准备为了别人，为了一个理想、为了人民的利益而牺牲一切，甚至不顾性命的英雄们，如果他们没有被杀或被排挤失势，到了夸天，他们也变成了抱着自我中心念头的懦夫，既无理想又无同志，甘愿抛弃一切——道义、名誉、真理与道德——以求苟全他在统治阶级与官僚集团里的地位。在革命前夕与革命期间，共产党人打算牺牲与受苦的英勇行径是世上少有的。可是，在取得政权之后，他们竟一变而为庸庸碌碌的无耻之徒与干枯公式的愚蠢卫护者，却也可能是史无前例的。奇异的人性是替共产土义运动产生力量并吸收力量的条件；而排他的、划分等级的风气以及伦理原则与品德的完全缺乏，又成了共产主义权力以及这个运动的维持的条件。道义，真诚、牺牲，热爱真理等一度是天经地义的东西：现在呢，处心积虑的谎言、谄媚、污蔑、欺骗与挑拨，已逐渐成为这个新阶级的黑暗、残忍与无所不包之权势的必然伴随者，甚至影响到这个阶级各个分子之间的关系。
 
三
谁若是不能领略共产主义发展的这一辩证过程，就不能理解所谓莫斯科大审判案，也无从懂得为何共产党人的周期性的道德危机——由于废弃当年他们曾委身奉献的神圣原则所致——不会产生重大的意义，而普通人民或别的运动若有这种道德危机，可就不得了啦。
 
赫鲁晓夫承认，斯大林清党大屠杀中遭殃者所作的“坦白认罪”与自我谴责，主要是靠逼供得来。他又宣称没有对这些人使用迷魂药，事实上却有证据证明用过此药。但逼使犯人“坦白认罪”的最有效的迷魂药，却含蕴在犯人自己构成的性格中。
 
—般的犯人，也即非共产党人，决不会进入神志昏迷状态，作发狂式的坦白认罪，祈求死刑作为自己有“罪”的报应。只有那些“盖着特殊印记的人”——共产党人——才会这么做。起初，他们遭受党内最高领导秘密施予的打击与指控，其暴烈与卑鄙使他们在道德上大感震惊，他们简直不能相信最高领导竟会这么卑鄙透顶，即使他们以前也曾偶尔发现最高领导的过错。现在他们陡然觉得自己是被人连根拔起了；  由共产党领导所代表的他们自己的阶级已背弃了他们，他们虽然是无辜的，而这个阶级却把他们当作犯人与叛徒钉上十字架。许久以前，党曾教育他们相信，而他们自己也曾宣称：他们本人每一丝每一缕都和党以及党的理想缠结在一起，现在，他们被连棍拔起之后，发觉自己完全一无所有了。对于共产党这一小小宗派及其狭隘观念以外的一切，他们或许是不知道，或许早已忘记了，或许已经抛弃了。现在要他们来结交共产主义以外的事物已为时太晚。他们完全孤立了。
 
人是不能在社会之外孤立作战或生活的。这是人的不变的特性，亚里斯多德早已看出这种特性并加以解释，称人为“政治的动物”。
 
由这样一个党派出来的人，一旦发觉自己在道德上已被摧毁与连根拔起，受到周密的残暴的拷问，他除了用“坦白认罪”来帮忙他原属的那个阶级与那些“同志”外，还有什么办法呢？他心里相信他的“坦白认罪”是那个阶级所必需的，借以抵抗“反社会主义”的反对派与“帝国主义者”。这种“坦白认罪”是被赶出党外的身败名裂的牺牲者唯一可能作的“伟大”的“革命性”贡献。
 
每一名真正的共产党人都受过教训并以此教育自己和别人：相信结成派系并从事派系斗争，是对党以及党的目的所犯的绝大罪恶之一。当然，共产党若分成许多派系，就不能在革命中取胜，也不能建立党的统治地位。不惜任何代价并且不顾一切地维护统一，已成为神秘的义务；一心一意要掌握全部权力的寡头统治者们，就以这种义务为护符，来保卫他们自己。精神沮丧的共产党党内的反对者，即令曾怀疑过此事，甚至知道此事，但他仍不能摆脱这个神秘的“统一”观念的迷惑。此外，他还会想到：领袖们可能今天是某甲明天换成某乙，无论他们是罪恶的、愚蠢的、自我本位的、前后矛盾的或是好弄权势的家伙，总之都要烟消云散，只有“目的”能继续存在。这“目的”就是一切；目的不就是如此长存于党内吗？
 
托洛茨基是共产党里一切反对派中的最重要人物，但他的推理并不比上文所说的更深刻多少。在自我批评的时候他曾大叫道：党是不会错的，因为它是历史必然性和无阶级社会的化身。流放期间，他曾企图用历史上类似的往事来解释莫斯科大审判的可怕的卑鄙，他指出皈依基督教前的罗马，以及资本主义萌芽时的文艺复兴时期，都曾出现过背弃信义的谋杀、诽谤、撒谎以及丑恶的大规模罪行等无可避免的现象。于是他下结论说，在过渡到社会主义去的时候，也一定要发生这类现象：这些都是仍存在于新社会中的旧阶级社会的残余。但他用这种说法，什么都不能说明，他只能抚慰自己的良心，以为自己并未“背叛”“无产阶级专政”或苏维埃——即过渡到新的无阶级社会去的一个形式。假如他对这问题探讨得更深一层，一定会看到：无论在共产主义或文艺复兴或其他历史时期，当一个所有权阶级为它自己开辟途径时，当它遭遇的困难愈来愈增加，它的控制权愈来愈需要完密无缺时，道德上的考虑也就愈来愈不关紧要了。
 
同样的，那些不明白在共产党人取得胜利之后哪一种社会变革是真正关键性的人，不得不把共产党人中各种各样的道德危机重新估价一番。对于所谓非斯大林化运动，或以前奉承斯大林的人对斯大林作无耻的、颇像斯大林方式的攻击，也不得不视为“一种道德危机”而加以重新估价。
 
任何独裁体制都无可避免地要发生大大小小的道德危机，因为它的追随者惯于认为政治思想的统一是最大的爱国品德与最神圣的公民义务，他们对于必然要出现的一百八十度大转变与变化一定大为烦恼。
 
但共产党人却感觉并知道，在这种一百八十度的转变中，他们的极权主义的统治不但不会削弱，反而更会增强；这是一条无可避免的路；道德的或诸如此类的理由即使不算是碍手碍脚的东西，也只能算是次要的东西。实际的行动使他们很快就知道这一切，结果，他们的道德危机无论深刻到什么地步，很快就终结了。当然，共产党人若是想要达到他们梦寐以求的真实目的——隐藏在理想目的下面的目的——那就只好不择手段了。
 
四
共产主义在别人眼中看来是道德沦丧的，但还不能说它是脆弱的。一般说来，至今为止情况恰恰相反。形形色色的清党与“莫斯科大审判”加强了共产主义制度与斯大林的纯治。无论如何，某些阶层——例如以纪德为最著名代表的知识分子——虽因此而鄙弃共产主义，并怀疑像今天这样的共产主义是否能实现他们所信仰的计划与理想；但共产主义并没有削弱：这个新阶级变得更强、跟巩固，摆脱了道德的顾虑，踏着共产主义信徒的鲜血前进。由别人眼里看来，共产主义在道德上是堕落了，但由它自己的阶级和它对社会的控制看来，它在事实上却加强了。
 
要想使当代共产主义被它自己的阶级成员所鄙视，还必须具备别的条件。必须这革命不但吞噬了它自己的儿女，而且可以说是吞噬了它本身。必须参与这革命的最有头脑的人们领会到它是一个剥削阶级，它的统治是不合理的。具体地说，必须这阶级发觉在最近的将来根本谈不到什么国家的消亡，什么各尽所能、各取所需的共产主义社会，必须这阶级承认建立这种社会的可能性是很容易给人驳倒的，正如容易给人证明一样。具备了这些条件，于是这个阶级所已经使用并正在使用以达成其目的及其统治的各项手段就成为荒谬、不人道、违背它的伟大宗旨——甚至背弃这个阶级的本身。这样一来，就会在统治阶级内部出现裂痕与动摇，而且再也无法遏止。换句话说，统治阶级为它自己的存在而作的斗争，迫使它或它内部的各宗派摒弃现正使用的手段，或者不再认为他们的目标已经在望而且是真实的。
 
在任何共产党国家中，至今还没有发生像这里所说的纯理论的假设的这种发展的希望，即使是在斯大林死后的苏联也是如此。在苏联，统治阶级仍然是一个紧密的阶级，对斯大林的手段所进行的谴责，即使是在理论上，已发展为防止苏联陷于个人独裁的暴政。赫鲁晓夫在苏共二十次党的代表大会上曾主张以 “必要的恐怖政治”对付“敌人”，这和斯大林以暴政对付“优秀的共产党员”恰成对比。由此看来，赫鲁晓夫并未谴责斯大林所用的手段，只是谴责把这种手段施于统治阶级高级分子。这个阶级的内部关系，自斯大林死后，似乎已有变化，这个阶级已足够坚强，能免于向它的领袖和特务机构的绝对控制投降。这个阶级和它所用的手段迄今并无多大改变，在道德的结各上还说不上内部有什么裂痕，不过，裂痕的初步征象已呈现出来了；在思想的危机里，这种征象日益明显。但尽管如此，我们必须认识：道德解体的过程还几乎没有开始，促成它开始的条件还几乎不存在。
 
寡头统治阶级既僭越了若干权利，就无法防止这些权利的碎屑落到人民手里。寡头集团若是大谈其在斯大林统治下没有权利，连共产党人也没有权利，那么群众也会同时应声而吼道：他们也没有权利——他们的权利更是被剥夺得一干二净。拿破仑本是法国资产阶级的帝王，但当他的穷兵黩武以及官僚暴政使人无法忍受时，资产阶级终于反叛他。而法国人民也由此终于能得到一些利益。斯大林的手段（其中教条地假定有个“未来社会”也起了重要作用）是不会卷土重来了。但这不是说现任的寡头统治者们就会废弃斯大林所用的全部手段，即使他们无法使用，也不是说苏联就会很快地在一夜之间变成一个法治的、民主的国家。
 
然而，有些事情已起了变化。统治阶级再也不能用什么只要目的好，手段一定对的理论来哄人了，甚至连它自己都哄不过去。它当然还要大谈其最后目的——共产主义社会——因为若不大谈这一套，就只好废弃它自己的绝对统治了。在这种情形下，统治阶级是不惜采取任何手段的。每一次它采取了什么手段后，它却又不得不对使用这些手段表示谴责。一种更大的力量——害怕世上的公众舆论，害怕舆论的制裁会使它本身和它的绝对统治受伤害——将指挥这个阶级，箝住它的手。当这个阶级觉得自己已强大得足可摧毁本身的创造者或整个制度的创造者（斯大林）的迷信时，它同时也就给了它自己的理想基础以致命的打击。这个统治阶级虽保持完全的统治，但已开始废弃并丧失它的意识形态，即使其获得政权的教条。这个阶级已开始分裂为许多宗派了。在最高层，一切都平安无事，但在最高层之下的深处，甚至在最高层分子之中，新思想、新观念已在萌芽，未来的大风暴已在酝酿中。
 
由于统治阶级不得不鄙弃斯大林的手段，它将无法保存它的教条。手段在实际上是教条的表现，也是教条所依据的那种实际行动的表现。
 
促使斯大林的左右看出斯大林手段的危害性的，既不是善意，更不是人道，而是迫切的需要，才促使统治阶级变得较为“明理”一点。但这些寡头们为了避免使用极端残暴的手段恰恰是撒下了对他们的目的怀疑的种子。目的一度作了使用任何手段的道德上的幌子。现在既鄙弃这种手段，这就令人怀疑到目的本身了。一旦那保证目的的手段给人揭露是有害的，那么目的的本身也就表明它永不可能实现。因为任何一个政策中的最极本事项首先便是它的手段——假定一切目的看求是好的。正如俗话所说，就连“通向地狱的路也是好意铺成的”。
 
五
有史以来，还没有过一个理想的目的是用非理想的、不人道的手段达成的，正如历史上没有一个自由社会是由奴隶造成的一样。最能表现目的的实质及其伟大者莫过于用以达到目的的手段。
 
假如必须要用目的来替手段开脱罪恶，那么一定是这目的在实质上有卑鄙的地方。真正抬高目的，并使一切为目的而作的努力与牺牲有道理的，是手段，是手段的不断改进以臻于完美，合乎人道，与增进自由。
 
当代共产主义却连这种情况的起头之点都还未达到。它反而停步不前了，对于手段总犹豫迟疑，但对于它的目的却总是满有信心。
 
在历史上从没有哪一个民主的政权——或在它存续的时候较为民主的政权——是主要地凭借对于理想目的所怀的愿望而建立的。民主的或较为民主的政权都建立在看得见的、日常应用的、小的手段之上。伴着这些手段的应用，各个这种政权多少有点自动地达到了伟大的目的。另一方面，每一种暴政都企图拿它的理想的目的来替自己掩饰。但从来没有任何一种暴政达到过伟大的目的。
 
绝对暴虐，或不择手段，这是同共产主义的目标之大而无当性，甚至不现实性相一致的。
 
当代共产主义，利用革命手段，已成功地破坏了一种社会形态而横暴地建立了另一种社会形态。起初，这种行动是受人类最美丽的、基本的人类理想——平等、博爱——所指导的；到了后来，共产党才以这些理想为幌子，运用一切手段，建立它的统治。
 
正如陀思妥耶夫斯基在《奴隶》（The Possessed）这部小说中借一个人物的口转述书中主角习加里也夫的话：
 
“……他那篇稿子写出了一桩精彩的事，”宛霍文斯基继续说道，……“社会里的每个人都监视别人，他有责任告密，出卖别人。每个人都属于全体，全体也属于每个人。大家都是奴隶，在奴隶身份上是一律平等的。他偶尔也会主张诽谤与谋杀，但主要的却是平等。……奴隶是必然会平等的。在历史上若没有专制，就不会有自由与平等。……”
 
像这样，由于用目的来替手段辩护，目的本身就变得越来越遥远而不现实了，而手段上可怕的现实则变得越来越明显且令人无法忍受。

第八章  本    质
一
在探讨当代共产主义本质的各种理论中，从未有对于这一问题作过透辟的论述，也没有一种理论表示如此做过。当代共产主义，是综合历史的、经济的、政治的、意识形态的、国家的、及国际的种种原因的产物。对于共产主义的本质作任何片面分析的理论，都不可能完全正确。
 
当代共产主义的本质，若非在其发展过程中自行彻底暴露，局外人根本无从理解。因为共产主义的发展已进入其特殊阶段——成熟阶段，共产主义的本质才自行暴露出来，也只有到这个时候才能自行暴露。  自此以后，对共产主义的权力，所有权及意识形态的性质的显露，才成为可能。当共产主义仍在发展，且主要地仍是一种意识形态时，对其本质几乎完全无法看清。
 
正如其他的真理一样，当代共产主义是许多作家、国家及运动的产品。共产主义多少随着它的发展，才逐步被透露出来。迄今为止，共产主义尚未能视为最后的定局，因其发展尚未全部完成。
 
在关于共产主义的大部分理论中，总有若干真理在内。每一理论通常都能掌握共产主义的一方面，或掌握其本质的一方面。
 
对于当代共产主义的本质，有如下两种基本理论。
 
第一种理论认为当代共产主义是一种新型的宗教。如上所述，我们认为共产主义既非一种宗教，也非一个教会，虽然事实上述两项要素，共产主义兼而有之。
 
第二种理论认为共产主义是革命的社会主义，为现代工业或资本主义以及无产阶级与其需要的产物。我们曾指出这一理论也只有部份正确。当代共产主义，最初在工业发达的国家以一种社会主义的意识形态出现，而为工人群众对工业革命所遭受痛苦的一种反应。但从它在不发达地区得势后，即已完全变质，成为一个违反无产阶级大部分利益的剥削制度。
 
有人提出进一步的理论，认为当代共产主义是一现代型的专制主义，由若干夺得权力者所创造。由于现代经济的性质，在在需要集中性管理，因而使这种专制主义的绝对化成为可能。这种理论虽也有若干真实性，即现代的共产主义是一现代的专制主义，必然要走向极权主义。但所有现代专制主义并非都是共产主义的变种，其极权化也没有抵达共产主义的程度。
 
因此，我们不论探讨哪一种理论都发现每一种理论都只能解释共产主义的一面，或只能道出其部分真相，而无法道出其全部的真相。
 
作者在本书中所提出的有关共产主义本质的理论也不能视为完整无缺。任何定义总有缺点的，尤其是对于复杂而变动的社会现象下定义时更是如此。
 
虽然如此，用最抽象的理论方法仍可能论述当代共产主义的本质，及什么是其中的最基本的因素，以及什么贯穿其一切表现与刺激其一切活动。深入了解其本质并说明其各方面是可能的，但其本质本身早已自形暴露了。
 
共产主义及其本质不断地由一形态转变为另一形态。没有这种转变，共产主义甚至不能存在。因而，对于这些转变必须不断加以探讨，并对已明显的事实作深一层的研究。
 
当代共产主义的本质是历史条件及其它特殊条件的产物但当共产主义强大以后，其本质的自身即变成一因素，并创造种种条件，以维持其本身继续的存在。因而，对共产主义的本质，显然必须依照任不同时期它的出现和活动所表现的形式及所处的种种条件东分别予以探讨。
 
二
当代共产主义是现代极权主义的一种类型，这个理论，不仅流传最广、而且也是最正确的。但对“现代极权主义”一词的真正了解，在讨论共产主义的地方，倒不很普通。
 
当代共产主义是具有三种基本要素以控制人民的一种极权主义。第一种是权力，第二是所有权，第三是意识形态。这些因素都被唯一的政党或——依照作者前面的解释及用语——由一个新阶级所垄断。而在日前，则由该党或该阶级的寡头集团所垄断。在历史上，甚至当代历史上，从未有一种极权制度——共产主义例外——能将这些要素成功地同时并用，而控制人民到这种程度。
 
如探讨并衡量这三项要素，则权力在共产主义的发展中，无论过去和现在，一直占有最重要地位。其它任何一种要素最后虽可能超越权力，但根据目前情势仍不能如此断定。我深信权力仍将继续成为共产主义的基本特征。
 
共产主义起源为一种意识形态，其中含有共产主义极权的及垄断的性质。现在我们可以肯定地说，在共产主义对人民的控制中，这种意识形态已不再占据重要地位。共产主义作为意识形态的阶段，已大体上成为过去。共产主义能向世界表现的新事物已不多。但对于权力及所有权两种要素，就不能这样说。
 
在每一种斗争中，甚至在人类每一社会行动中，可以说，不论是物质的、知识的、或经济的权力都起作用。这一说法相当有道理。也可以说，权力，即争取与保持权力的斗争，是任何政策的基本问题及目标。这一说法也有相当道理。但当代共产主义不仅是这样的一种权力，而它意味着更多的东西。它是一种特殊型态的权力，在这种权力之内，集思想控制、权威及所有权于一身。而且这种权力的本身变成一种目的。
 
迄今为止，存在最久与发展最充分的型态苏维埃共产主义业已经历三个阶段。其它型态的共产主义也多少如此（只有中国型的还是例外，迄今仍停留于第二阶段上）。
 
这三个阶段是：革命的，教条的，与非教条的共产主义。大致说来，这些阶段中的基本口号、目标及代表人物是，第一阶段是革命或权力之夺取，代表人物是列宁；第二阶段是“社会主义”或谈制度的建立，代表人物为斯大林；第三阶段为“法治”或制度的稳定，代表人物为“集体领导”。
 
值得注意的是，这些阶段并非界限分明不可逾越，其全部要素在每一阶段中都可以发现。如教条主义之盛行，与“社会主义的建立”，在列宁时代即已开始，斯大林并未放弃革命，或反对干预建立制度的种种教条。今天，非教条的共产主义也只是有条件的非教条：他们决不会为教条的理由而舍弃丝毫的实际利益。正因为这些利益，它同时可以对丝毫有怀疑教条的真实性与纯洁性的人予以无情的迫害。因此，  由实际需要与能力为出发点的共产主义，今天虽已卷起革命或自己的军事扩张的风帆，但却未曾舍弃其中的任何一项。
 
这种将共产主义的发展划分为三个阶段的作法，只有粗略的及抽象的来看，才算是正确的。截然分开的阶段事实上并不存在，而这三个阶段也未能与各国某一特殊时期的情形完全吻合。
 
各阶段间的界线常彼此重叠，且在各不同的共产党国家中，其出现的形态也互异。如南斯拉夫经过这三个阶段的时问比较短促，而且其最高阶层的代表人物也未曾更易；但在理论与运用的方法上，这种差别均极明显。
 
在全部三个阶段中，权力始终占一重要地位。在革命阶段，固然必需攫取权力，在建立社会主义阶段，也需利用权力来建立一新制度；而今天，则需要权力来保持这一制度。
 
从第一至第三阶段的发展过程中，共产主义的真髓——权力——也由手段变为自身的目的。实际上权力虽多少是一种目的，但共产党的领袖们，认为只有通过权力这一手段，他们才能达到理想的目的，而不肯承认权力的本身即为目的。正因为权力被作为使社会转变为乌托邦的一种手段，因而就无法避免使其本身成为一种目的，并成为共产主义最重要的目的。在第一及第二阶段中，权力可能被视为一种手段，但到了第三阶段，权力是共产主义真正的主要目的与本质这一事实，即无法再掩盖。
 
因为事实上共产主义不再是一种意识形态，它就必须保持权力以为控制人民的主要手段。
 
在革命中，正如在每一种战争中一样，为了使战争获胜，自然首先需要集中权力，进入工业化时期后，为了建立工业或建立“社会主义社会”，必须作许多牺牲，因而集中权力也被视为理所当然。但当这一切完成后，在共产主义制度中，权力即显然地已不仅是一种手段而且已变成目的，假如不是唯一的，也是主要的目的。
 
在目前，权力既是共产党人的手段，也是他们的目的，以维持其各种特权及所有权。但由于这种权力与所有权都是特殊形式，只有借权力才能行使所有权。权力本身即为一种目的。也是当代共产主义的本质。其它阶级可能不借权力的垄断以维持其所有权，或不借所有权的垄断以维持其权力。但迄今为止，由共产主义所形成的新阶级并不能如此，即使在将来也极少有这一可能。
 
在所有这三个阶段中，权力始终被掩藏起来，成为隐蔽的，不可见的，不提及的，自然的，和主要的目的。其地位之强弱视当时需要控制人民的程度而定。在第一阶段中，思想是夺取政权的鼓舞者及原动力；到第二阶段，权力作为对社会的鞭策，也为维持其自身而被行使，今天，“集体所有制”从属于权力的冲动与需要之下。权力成为当代共产主义彻头彻尾的化身，甚至共产主义要力图阻止这种倾向也不可能。
 
思想，哲学原则，道德考虑，国家，人民，历史，甚至一部分的所有权都可以改变或牺牲；唯有权力决不能如此。如果改变或牺牲权力，无异使共产主义舍弃其自身及其本质，个人可以如此，而阶级，党及寡头集团决不能如此。这就是它存在的目的与意义。
 
任何形态的权力，除作为手段外，同时即为其目的——至少对渴望权力者是如此。权力几乎是共产主义唯一的目标，因为这是一切特权的源泉与保证。凭借权力与通过权力的行使，较治阶级在物质上的特权与对全国财物的所有权，才能实现。权力决定思想的价值，并禁止或容许其表现。
 
由于这种原因，当代共产主义的权力与其它形态的权力不同，而共产主义与其他制度也有区别。
 
正因为权力是共产主义最主要的成份，因而共产主义必须是极权的，排它的与孤立的。如果共产主义真有其他的目的，则应使其它的力量有起来反对及独立行动的可能。
 
对当代共产主义应如何下定义是次要问题。每一个从事解释共产主义的人，均会面临如何给共产主义下定义的问题，即使实际情形并不强求其如此——在实际上，共产党人常将其制度，美其名为“社会主义”，“无阶级社会”，“人娄永恒梦想的实现”等等，而反对的人，则视共产主义为无人性的暴政，恐怖集团的侥幸成功，与人类的浩劫。
 
在科学中，为简单说明起见，常利用某一已有的范畴来说明某一事物。但假如我们为省事起见，究竟应将当代的共产主义归入社会学的哪一范畴？
 
近年以来，作者曾将共产主义与国家资本主义，或更确切的说，与极权国家资本主义相提并论。许多著作家，虽由其它立场出发，但见解大致相同。
 
在南斯拉夫与苏联政府决裂期间，这种见解为南共领袖们所采纳。但由于共产党人，根据实际需要，极易改变他们甚至“科学的”分析，因而当南斯拉夫与苏联政府“和解”以后，南共领袖们又改变其见解，再度宣称苏联是一社会主义国家。同时，他们宣称苏联对南斯拉夫的独立作帝国主义式的攻击是——照铁托的说法——一种“悲剧”和“不可思议”的事情，是由于“若干个人的专断”而引起的。
 
当代共产主义，绝大部分与极权国家资本主义相似。其历史渊源及所应解决的问题——如类似资本主义所完成的工业化变革，但借助于国家的机构——足以导致这样的结论。
 
假如在共产主义下，国家是真正代表社会和民族的所有者，则控制社会的政治权力的形态必须随社会及国家不同的需要而变化。国家在性质上是社会中统一而和谐的机构，而不只是一个控制社会的力量。国家不能同时兼具所有者与统治者两层身份。但实际上在共产主义下，其情形正相反。国家是一种工具，永远只服从独一无二的所有者的利益，或在经济及社会生活的其它领域中，也只是服从于同一方方针。
 
西方的国家所有权，看起来比共产党国家更近似国家资本主义。将当代共产主义作为国家资本主义的说法，是由那些从共产主义制度迷津中醒悟过来的人，本于“良心上的痛苦”所提出；但由于他们无法为共产主义下定义，因而将其一切流弊与资本主义的弊害等量齐观。因为在共产主义之下，事实上已无私人所有权，而只有形式上的国家所有权，那末将一切弊端归诸于国家，似乎没有比此更合逻辑。这个国家资本主义的观点也为那些认为私人资本“弊害较少”者所接受。所以他们喜欢指出共产主义是一种最坏的资本主义。
 
将当代共产主义视为某种事物的过渡之说法，事实上等于并未解释共产主义。试问其它制度又有那种不是某些事物的过渡？
 
即使我们承认当代共产主义含有一种无所不包的国家资本主义的许多特点，共产主义仍有其本身的许多恃点，因而认为它是一种特殊型态的新的社会制度，是更为恰当的。
 
当代共产主义有其自己的本质，不容与其它任何制度相混淆。共产主义虽然吸收其它制度的许多因素——封建的，资本主义的甚至奴隶所有制的——但同时它仍保持其个别的和独特的本质。

第九章    民族共产主义
一
在本质上，各国共产主义都是一样的；但在各个国家，表现的程度与方式却有所不同。所以我们可以说有各种共产主义制度，也可以说那只是一个制度的不同形式。
 
这种存在于共产主义国家之间的不同，最主要的是各国历史背景不同的结果，斯大林曾想用武力来消灭这不同，但徒劳无功。例如，就甚至最肤浅的观察也可以告诉我们，现今苏联的官僚制度与沙皇制度不是没有连带关系的，如恩格斯所说，沙皇制度下的官吏们是个“特殊阶级”。这种情形，在南斯拉夫的政府中，也可以说大体相同。共产党既在不同的国家内得势，他们便面临不同的文化与技术水平，及不同的社会关系，并面临各国不同的知识分子。这种不同更有不同的特殊发展。因为共产党的得势，其一般原因大抵相同，又因他们要对共同的内外敌人从事斗争，所以各国的共产党人，立即不得不联合奋斗，并且采取同一的意识形态作为根据。像共产主义的其他一切一样，一度曾是革命家的事业的国际共产主义，后来竟转变为共产党官僚的共同地盘，而各自站在国家的立场上互相斗争。过去的国际无产阶纸，因此成了空话与空洞的教条，在这些官僚的背后，只有防卫得很好的赤裸裸的国家与国际的利益、个人的野心，以及各国共产党寡头们的计划。
 
权力与财产的性质，相同的世界观以及一致的意识形态，不免使各共产党国家看来彼此相同。但若把各共产党国家在程度与方式上的不同一笔抹煞，或者认为不足重视，那却错了。共产主义实现的程度、形式，或其目的正是每个共产党国家的一个特定条件，其意义完全与共产主义本质相等。所以不论任何类型的共产主义，不管它和其他形式如何彼此相同，都不免是民族共产主义。他为了保全自己必须适应国情。
 
在所有共产党国家中，政府与财产的形式，像其思想一样，很少不同，或者根本没有不同。因为它具有相同的性质——极权——所以不会有多大的不同。但是他们希望获胜并继续存在，那末各国共产党人就得使其权力在程度和方式上，适应各个国家的条件。
 
因此，各共产党国家不同的程度，大抵与各国共产党在取得权力的过程中所表现的独立程度相等。具体说来，只有苏联，中国及南斯拉夫三国的共产党人是独立地完成革命的，也就是说以自己的方式与速度取得政权，而开始“社会主义建设”的。这三个国家都是独立的共产党国家，甚至当南斯拉夫处于苏联最强烈的影响之下时——像今天的中国一样——即在所谓“兄弟的爱”与“永恒的友谊”的笼罩下，仍保其独立。在苏共第二十次代表大会的秘密会讲中，据赫鲁晓夫的报告透露，斯大林与中国政府之间好容易才避免冲突。苏联与南斯拉夫的冲突，并非孤立事件，不过是最为严重而首先发生而已。对于其他共产党国家，苏联则用“武装的教士”——军队——强迫推行共产主义。在这些国家中，其发展方式和程度上的不同尚未达到南斯拉夫与中国的阶段。但是这些国家的统治官僚，一旦集合力量变成独立的集团，并且一旦他们知道服从与抄袭苏联的结果将削弱自己，他们便想努力“效法”南斯拉夫，即谋独立发展。我们知道东欧各共产党国家之所以成为苏联附庸，并不是因为由此可以得利，而是因为力量太弱小、无法阻止。所以只要他们一旦势力强大，或者创造了有利的条件，他们就会提出迫切要求，谋求独立，借以保护“他们自己的人民”免受苏联的支配。
 
共产主义革命既在一国取得胜利，一个新阶级就起而当权。他们尽管是将其“利益”附属于他国的同一阶级，却不甘以其辛苦获得的“特权”仅因意识形态上的一致，而让与他人。
 
那些以自己力量取得共产主义革命胜利的国家，必然要走上单独的特殊发展的道路。与其他共产党国家，尤其与最重要而最富有帝国主义性的苏联之间的分裂，便接着发生。在革命得胜国家中的统治官僚集团，早已在武装斗争中有了独立地位，并且早已尝到了权力在握与财产“国有化”的甜味。就哲学意义来说，他们已了解到、察觉到自身的本质，“自己的国家”与自己的权力，而以此为根据要求平等了。
 
但这并不是说这牵涉到一场一埸冲突只发生在两个官僚组织之间。冲突还涉及臣属国家中的革命分子，因为他们通常并不愿意遭受支配，他们认为，共产党国家之间的关系，应当如教条中所述的那样十全十美。同时，一国的群众，他们生来渴望独立，也不能对此种冲突坐视而无动于衷。总之，这对国家是有利的：从此可以不纳贡于外国政府；本国政府不再希望也不准抄袭外国方法，因此政府所受的压力也就变小了。这类冲突也引入外国的势力，引起其他情况和运动。但是冲突的性质与其基本势力，是一直不变的。在苏联与南斯拉夫的共产党人之间，不论是纷争以前，纷争期间或纷争以后，他们都不改变原来的态度。真的，他们借以保障垄断权力的不同程度与方式的共产主义，使他们彼此都否认对方阵地中存在社会主义。到他们把纷争解决以后，又再互相承认对方的国家内存在社会主义，并感到倘若要保存那些在本质上一致、并对彼此都极重要的东西，那末，彼此的差别是应该互相尊重的。
 
东欧共产党附庸国家的政府能够、并且事实上必须声明它们摆脱苏联而独立。无人可以断言，这种独立的要求将发展到何种程度，也无法断言将产生什么样的不和，其结果有赖于许多不可预知的国内外形势。但各国共产党的官僚集团势必要求有更完全的权力，那是不容怀疑的。这可由斯大林时代东欧国家反铁托过程来证明，这还可以由波兰与匈牙利最近尖锐地出现和流行的坦然强调“自己的社会主义道路”来证明。这是苏联中央政府所最感困难的，因为甚至它自己在苏维埃各共和国内所设立的政府中，如乌克兰，高加索，都有民族主义存在，而那些在东欧各国所设立的政府中则更为强烈。苏联之所以现在不能，将来也不能，在经济上将东欧国家加以同化，是民族主义在所有这些方面起了重要的作用。
 
此种民族独立的要求不消说必然具有很大的动力。只有以外面的压力，或者以共产党人方面对“帝国主义”与“资产阶级”的畏惧可加以阻止或压服，但决不能根本消除。反之，它们的力量将继续增长。
 
今后各共产党国家间的关系将采取何种形式，我们不能预言。尽管不同的共产党国家间的合作能在短时期内彼此合并或组成联邦，而彼此间的冲突仍可能造成战争。苏联与南斯拉夫间的公开武装冲突之所以不致发生，并不是由于彼此都是“社会主义”，而是由于斯大林没有兴趣去冒一场不可预卜规模大小的冲突的险。共产党国家间将来不论发生什么情况，仍须视寻常影响政治事件的所有那些因素而定。以“民族的”或“统一的”形式出现的各国共产党官僚的利益，和以国家为基础的有增无已的独立趋向，目前将对共产党国家间的关系发生重大作用。
 
二
民族共产主义的观念直到第二次世界大战终结时才有意义。因为当时的苏联帝国主义，不但表现于对资本主义国家，并且对共产党国家也是如此。到苏联与南斯拉夫发生冲突，这一观念才显得突出。赫鲁晓夫与布尔加宁的提出“集体领导”以否定斯大林的方法，也许可以缓和苏联与其他共产党国家的关系，不过却不能解决问题。因为苏联的行动，不仅与共产主义有关，同时还与大俄罗斯——苏维埃——国家的帝国主义有关。这一帝国主义可以改变其形式与手段，但它却不能消失，这比其他共产党国家要求独立的愿望还难消失。
 
其他共产党国家有同样的趋向。他们也企图根据他们的力量与条件，用各种方法变成帝国主义。
 
在苏联外交政策的发展上就有两个帝国主义阶段。初期的政策，几乎完全是通过在其他国家的革命宣博，而扩张其势力。那时在最高级领袖的政策上，即有强烈的帝国主义倾向，如对于高加索的政策。但我以为，把这一革命阶段绝对地看作是帝国主义阶段，并没有充分理由，因为当时是防卫重于侵略。
 
倘若我们不把革命阶段的政策看作帝国主义阶段，那末大体说来，苏联帝国主义的开始，当在斯大林胜利时期，即起始于二十世纪三十年代的工业化与新阶级的权力确立时期。在第二次世界大战的前夕，这一变化已明白显出，当时斯大林政府已能有所行动，而放弃了和平主义和反帝国主义阶段的政策。并且，这还可以在外交政策的转变中看出来，如以不讲是非和冷酷的莫洛托夫代替活泼风趣而相当有原则的李维诺夫，便是明证。
 
这种帝国主义政策的基本原因，完全隐藏于新阶级的剥削与专制的性质中。为了这一阶级本身可以显出它有帝国主义性质，它有必要达到一定的力量，而在适当的时机有所表现，当第二次世界大战爆发时，苏联已具有此种力量，而战争又使帝国主义的兼并有充分发挥的机会。例如波罗的海各小国，对于像苏联这样的大国的安全并无必要，在现代战争中尤其如此。这些小国也无力从事侵略，且曾为苏联的盟国，但是对于大俄罗斯共产党官僚贪得无厌的食欲来说，它们却是一口肥肉。
 
在第二次世界大战前，共产党的国际主义一直是苏联外交政策不可分割的一部分，但到大战时，它却与统治苏联的官僚利益发生了冲突。因此，共产国际的组织就失去了必要。共产国际的真正解散虽是在大战的第二阶段与西方国家结成同盟的时候，但根据季米特洛夫的说法，这个念头早在波罗的海各国被征服后、与希特勒合作的时期就有了。
 
由东欧与法国和意大利各国的共产党组成的共产党情报局，本是在斯大林的倡议下建立的，其目的在于保障苏联在附庸国的控制力，并加强其在西欧的势力。过去的共产国际，虽由莫斯科绝对控制，但至少在形式上还代表所有的共产党。所以共产党情报局比过去的共产国际更坏。共产党情报局是在苏联的真正而明显的影响下发展起来的。与南斯拉夫的冲突显出情报局是用来使那些因国内民族共产主义的成长而开始衰弱的共产党国家及共产党听命于苏联政府的。斯大林死后，共产党情报局终于解散了。甚至苏联想避免重大而危险的争论，接受了所谓走向社会主义的独立道路，纵然不说这就是民族共产主义。
 
这种组织的变化大有其深远的经济与政治的原因。因为东欧的共产党势力薄弱，而苏联的经济力量又不够强大，所以苏联政府要想降服东欧各国，就不得不用行政的方法；纵令没有斯大林的横暴与专制，也是必须如此。苏联帝国主义必须以政治、警察及军事的方法，来弥补其经济上与其他方面的弱点。军事形式的帝国主义只是比旧式沙皇军事封建帝国主义更先进的一个阶段，这与苏联的内部机构也是相称的，苏联的内部机构就是以集大权于一人的警察与行政机构起主要作用。斯大林主义就是  个人的共产党独裁与军事帝国主义的混合物。
 
苏联帝国主义的形式发展为下列几种：设立股份公司，以政治压力使物价低于世界市场，从而吸收东欧各国的出口货，形成人为的“社会主义世界市场”，对附庸国家与附庸党派的一切政治行动加以控制；把共产党人对“社会主义祖国”传统的爱转变为对苏维埃国家、斯大林、及苏维埃措施的膜拜。
 
但是结果怎样呢？
 
苏联统治阶级内部因此完成了一个变化。就另一意义说，东  欧各国也有同样的变化；新的民族官僚集团既渴望能日益巩固  其权力与财产关系，但同时由于苏联政府强霸的压力，他们已陷入困难。他们初时虽为了取得权力而否认民族特性，但是现在要想使其权力更有发展，这一行动却反成了阻碍。此外，在苏联政府方面，已不可能继续施行过度和危险的斯大林主义的武力镇压与孤立的外交政策，同时在这普遍的殖民地运动的时期，也不可能使欧洲各国处于耻辱的奴役之下。
 
南斯拉夫的领袖们曾被苏联领袖们诬栽为希特勒党徒及美国间谍，那只是因为他们要保卫其依据自己的道路以建立并巩固共产主义制度的权利；但是，经过了长期的摇摆不定的争论，苏联领袖们不得不表示让步。于是铁托变成了当代共产主义中最重要的人物。民族共产主义的原则现在正式受到了承认。但是，正因为如此，南斯拉夫也不再是共产主义革新的唯一创始者，南斯拉夫的革命现在消沉了，从此开始和平而常规的统治。但它与昨天的敌人并没有更亲密，并且两者间的争论也未终止。这只是一个新阶段的开始。
 
如今，苏联的帝国主义政策已进入了以絰济与政治为主的阶段。这可由当前的事实看出来。
 
现在，民族共产主义已是共产主义的普遍现象。所有共产主义运动——除了苏联的共产主义运动是民族共产主义的反对目标一一在不同程度上都受民族共产主义的支配。在以前，即斯大林得势的时候，苏联的共产主义也是民族共产主义。当时俄国共产主义，除了把国际主义作为外交政策的工具外，已放弃国际主义。现在，苏联的共产主义却不得不承认共产主义中的新现实，纵或它的承认并不十分明确。
 
因为内部的变化，苏联帝国主义也不得不改变其对外面世界的态度。过去对东欧各国，着重在政治上的控制，现在逐渐进而谋求经济上结合成一体。这一政策是通过重要经济部门的共同计划去完成的，当地的共产党政府因为自感内在外在力量都还薄弱，所以多对此自动表示赞同。
 
但是，因为其中含有基本的矛盾，这样的情形到底不能维持长久。一方面，共产主义的民族形式日趋强大；而在另一方面，苏联帝国主义却并未削弱。现在苏联政府与东欧各国、包括南斯拉夫在内的政府，正以协议与合作的方法来设法解决那些影响他们本质的相互间问题，即谋求保存权力与财产所有权的既定形式。但即使在财产所有权方面可能采取合作，在权力方面却不可能如此。虽然进一步与苏联一体化的条件已具备，但使东欧共产党各国政府走向独立的那些条件却发展更快。苏联既未放弃它在这些国家里的权威，而这些国家的政府也并未放弃其要想达到类似南斯拉夫的独立的要求。至于能独立到什么程度，那就要看国际与国内力量的情形了。
 
过去苏联对于共产主义的民族形式曾切齿反对，现在的表示承认自含有巨大意义，同时对于苏联帝国主义也藏有重大的危机。
 
这项行动包含某种程度的讨论自由；这也就是意识形态的独立。当前共产主义中若干异端的命运，不仅是倚靠莫斯科的宽容，还得要靠他们自己国家的潜力。在“志愿的”与“意识形态的”基础上要求保持自己在共产主义世界的影响，而与莫斯科分离的趋向到底不是可以遏阻的。
 
现在莫斯科本身就已不是往日的莫斯科了。他失去了对新思想的垄断权，也没有规定唯一可行的“路线”的道义上的权利。自从否定了斯大林后，它就不再是共产主义世界意识形态的中心了。如今，莫斯科的伟大共产主义帝国，及其伟大思想的时代已告终结，现在是平庸的共产党官僚统治的开始。
 
“集体领导”想不到在共产主义内外有许多的困难及失败。那末怎么办呢？斯大林帝国主义是太危险了，更糟的是竟无效能。在斯大林统治下，不仅人民，甚至共产党人也表不满，而且这是在国际局势十分紧张的时候发生的。
 
共产主义思想的世界中心现已不再存在了，并且处于全部解体的过程中。世界共产主义运动的统一受到不可救药的损害，竟毫无挽救的可能。但是，就像从斯大林独裁转变到“集体领导”并未改变苏联制度本身的性质一样，民族共产主义虽然增加了离开莫斯科而获得自由的可能，却也不能改变其本质，这种本质便是思想的完全控制与垄断，以及由共产党官僚之专享所有权。诚然，压迫已有缓和，对于财产的垄断也采取较慢的步骤，尤其是在农村地区。但是民族共产主义仍不想，也不能改变成共产主义以外的制度，并且还有一种势力自动地拉它去接近其发源地的苏联。民族共产主义的命运是不可能同那些跟它联系在一起的其他共产党国家及共产主义运动的命运分开的。
 
共产主义之作适应各个国家特定情况的修正，对于苏联帝国主义，尤其是斯大林时代的帝国主义，是一大危害，但对整个共产主义或其本质来说，却并不然。相反地，在共产主义得势的地方，这种变化能够影响其方向，甚至加强其势力，使它能为外面所接受。总之，民族共产主义是与非教条主义一致的，那就是说，是与共产主义发展中之反斯大林主义阶段一致的。事实上，民族共产主义是这个阶段的基本形式。
 
三
民族共产主义并不能改变各国之间当前国际关系及工人运动的性质。但它在这些关系中的作用可能有很大的意义。例如，作为民族共产主义的一种形式的南斯拉夫的共产主义，对于苏联帝国主义的削弱以及共产主义运动中斯大林主义的失势，都有过非常重大的作用。要求改变的动机，如正发生于苏联及东欧国家的，尤其可在各国本身找到。首先是在南斯拉夫以南斯拉夫的方式出现；也是最先在这里完成改变的。南斯拉夫共产主义，以及族共产主义的形式与斯大林相冲突，实际上这是在共产主义的发展中斯大林死后的新阶段的发端。南斯拉夫的共产主义对于共产主义本身的改变有很大的影响，但对于国际关系或非共产主义的工人运动却不曾有根本影响。
 
有人以为南斯拉夫的共产主义将能向民主社会主义发展，或能作为社会民主主义与共产主义之间的桥梁，那是没有根据的。对于这一问题，在南斯拉夫的领袖中间意见就不一致。当苏联向南斯拉夫施加压力的时期，他们很希望能与社会民主党人亲善。但是到了1956年与莫斯科握手言和的时期，铁托宣布共产党情报局和社会党国际都不必要，虽然社会党国际在共产党情报局猛烈攻击南斯拉夫时曾为南斯拉夫作无私地辩护。南斯拉夫的领袖们一味实行所谓积极共处政策（这项政策大体与他们当时的利益相符合），于是他们便宣称这两个组织，即共产党情报局与社会党国际都“偏于极端”，只因为那是两个集团的产物。
 
南斯拉夫的领袖们不仅将其愿望与现实混为一事，并且也把一时的利益与深远的历史性的及社会主义的分歧混在一起。
 
无论如何，共产党情报局是斯大林为建立东欧军事集团而产生的。而社会党国际活动多在西欧国家组织中，其与西方集团或大西洋公约有连带关系，也是无可否认的事实，但是，纵无西方集团，社会党国际也是存在的。社会党国际主要是发达的欧洲国家的社会主义者的组织，在这些国家里有政治民主和类似的各种关系。
 
军事的联盟与集团只是暂时的现象，但西方的社会主义与东方的共产主义却是比较长久而基本的趋向。
 
共产主义与社会民主主义截然不同，这不仅是在原则上不同的结果（这方面无关紧要），而且是两个适相反对的经济及知识力量的结果。1903年俄国社会民主工党第二次代表大会在伦敦开会的时候，马尔托夫与列宁间的冲突所涉及的有关于党员资格的问题，有关于中央集权的多少与党的纪律问题；杜次溪(Deutscher)正确地称它为历史上最大分裂的开始，其意义的重大实非当时创议人所能预料。自此以后，不仅形成了两种运动，还形成了两个社会制度。
 
除非两种运动的性质或造成两者之间不同的条件能够有所改变，则共产主义与社会民主主义的分裂是无法缝合的。半世纪来，两者之间虽也有一时的和个别的妥协，但大体说来，他们的不同只有增加，他们的性质只有更趋独特。今日的社会民主主义与共产主义，已不止是两个运动，且是两个世界了。
 
脱离莫斯科的民族共产主义，虽然可使这个裂痕较为和缓而不趋于恶化，但要缝合却不可能。例如南斯拉夫共产党人与社会比主党人的合作，只是表面而非真实，只有客气而无诚意，所以两方面都不能获得切实重要的结果。
 
为了完全不同的理由，甚至西方与亚洲的社会民主党间也不能联合一致。他们在本质上，原则上，都无多大的不同；所不同者是在实践方面。  为了国家的立场，亚洲的社会党仍然得与西欧的社会党分立。即使西欧社会党人也反对殖民主义（虽然他们并未居于领导地位），只因他们属于发达的国家，他们总是对不发达国家维持剥削者的立埸。亚洲社会民主党与西方社会民主党的不同，可说是不发达国家与发达国家在社会主义运动队伍中的不同。它们彼此之间的具体形式必须严格划分，但就今日所能推断的说，它们在本质上的接近是明显而必然的。
 
四
与南斯拉夫类似的民族共产主义，其在非共产党国家的共产党中，是能有重大国际意义的。并且，其意义的重大也许竟超过真正执政的共产党。最主要的例如法国与意大利的共产党，就有这种情形，因为两国的共产党在工人阶级中占有极大多数；再加上在亚洲的几个共产党，于是它们就成了非共产主义世界中仅有的几个意义重大的共产党。
 
但直到现在，民族共产主义在这些共产党中尚未显出重大的意义与影响。然而，这是不可避免的，最后，它们必将使这些共产党发生深远而根本的变化。
 
这些共产党必须与社会民主党人竞争，因为后者能越过他们自己的社会主义的口号与活动，去打动不满的群众跟他们走。这不是非共产主义世界中共产党终于脱离莫斯科的唯一原因。莫斯科及其他执政的共产党常有出于意外的倒行逆施，也许是次要的原因。这些倒行逆施的事使这些和其他没有执政的共产党感到“良心上的危机”，因为他们常常被迫唾弃以往所赞美的一切而突然改变其路线。无论是反对派的宣传或行政上的压力，都不能从根本上阻止非共产主义世界中各国共产党的转变。
 
这些党派所以与莫斯科分离的基本原因，可能在它们所活动的国家的社会制度的性质中找到。如果很显然——看来是可能的——这些国家的工人阶级能通过议会方式而改善其他位，并改变其社会制度本身，该阶级便将不顾它的革命传统与其他传统，而放弃共产主义。只有少数共产党教条主义者会把这工人离心之事淡然置之；而各该国认真的政治领袖们就将竭力设法避免，甚至不惜削弱其对莫斯科的关系。
 
在这些国家中，因议会选举，曾使共产党获得了许多选票，但这却不能代表共产党的真实力量。而且这在很大程度上还是不满与失望的表示。尽管现在还有许多群众坚决追随共产党领袖，但有一天他们看清楚，领袖们是在为了官僚制度、“无产阶级专政”及与莫斯科的联系，而牺牲其国家的制度与工人阶级的实际前途时，他们就会轻易离弃这些共产党领袖。
 
自然，这些都只是假定。但是，即在今天，这些共产党已感到处境困难了。倘若他们真想成为议会主义的信徒，那末他们的领袖就得放弃其反议会的性质，或者改变而为民族共产主义；这样一来，由于它们既未当权，他们的党就不免发生分裂。
 
这些国家中的共产党领袖，他们正被迫以民族共产主义的观念与形式来作试验。他们不得不如此做是由于下列的因素：以民主方式来改造社会与改善工人的地位的可能正日见增加；莫斯科打倒斯大林个人迷信的大转变终于破坏了意识形态中心；受社会民主党人的支持；西方正在深广而经久的社会与军事基础上趋向统一；由于西方集团武力的增强，使得苏军提供“兄弟援助”的机会愈来愈少；非有另一次世界大战，新的共产党革命是无可能了。同时，害怕终于会变成议会主义，害怕与莫斯科破裂，使这些领袖做不出任何真正有意义的事。并且东西两方间日趋深刻的社会差异发生着无情的作用。因此聪明的意大利共产党领袖陶里亚蒂感到惶惑了，坚强的法国共产党领袖多列士在动摇了。党的内外生活都正开始给他们提供另一条道路。
 
赫鲁晓夫在第二十次党代表大会中强调，如今议会政治可作为“向社会主义过渡的形式”，其用意即在便于“资本主义国家”中的共产党因势制宜，鼓动共产党与社会民主党合作，形成“人民阵线”。从他的言论看，由于导致共产主义加强的那些变化和世界的和平局势，他以为这类办法是切合实际的。所以他默认，在发达的国家中，共产主义的革命显然已无可能，并且，共产主义要在现形势下再事扩张，势必要冒引起一次新的世界大战的危险。因此，苏联今日的政策已降为维持现状，共产主义也退化到以新方式逐渐巩固其新地位。
 
但在非共产党国家的共产党中，实际上已开始有危机。倘若他们改变成为民族共产主义，那就冒着放弃其本质的危险；倘若不作改变，那末就有失去其党徒拥护的危险。于是在这些共产党中，代表共产主义精神的领袖们，为了要脱出这个矛盾的困境，便只好用狡猾巧诈手段和蛮不讲理的方法。他们也许不可能阻止党的转向与分裂，但是他们却不得不与显然导致新关系的国内外的真正发展趋势冲突。 
 
共产党国家以外的民族共产主义不可避免地要导致弃绝共产主义本身，或使共产党解体。在今日非共产党国家中，这样的可能性正在增大，不过，显然只能采取与共产主义本身分裂的路线。因此，在这些共产党中的民族共产主义早晚将得到胜利，但必须艰难而迟缓地，经历不断的变动。
 
即令民族共产主义有意于激励共产主义与增强其性质，但在没有取得政权的共产党中，它实际上是侵触共产主义的异端外道。民族共产主义本身就是矛盾的。它的性质与苏维埃共产主义相同，但它想脱离出来，而变成自己国家的东西。实际上，民族共产主义是衰落的共产主义。

第十章  今日世界
一
为了更清楚地确定当代共产主义的国际地位，我们必须略述当前的世界情况。
 
第一次世界大战的结果，使沙皇俄国变成了新型的国家，或是说变为具有新型社会关系的国家。在国际上，美国的工业水平及速度与西欧各国的差异已加深；第二次世界大战将这种差异变成了一条不可逾越的鸿沟，以致现在只有美国的经济结构未曾有巨大的变动。
 
战争不是使美国与其余世界之间造成这条鸿沟的唯一原因；这不过是加速这条鸿沟的形成而已。美国所以能迅速进步的原因，无疑地在于其国内的潜力，在于其自然与社会的条件，及其经济的性质。原来美国资本主义发展的环境与欧洲的不同，并且在欧洲资本主义开始衰落的时候，美国正在飞跃的发展。
 
今天这道鸿沟已达到这样的宽度：美国人口仅占世界人口的6%，但其生产的货物与劳务却居世界总量40%。在第一次与第二次世界大战期间，美国的生产量占世界总量的33%；第二次世界大战以后，增加到50%。欧洲（除去苏联）的情形恰巧相反，1870年时欧洲生产居世界产量68%，到1925-1929年间，降到42%，到1937年更降至34%，到1948年降至25%(根据联合国的资料)。
 
现代工业在殖民地经济中的发展也非常重要，这使它们当中大多数在第二次世界大战以后终能获得自由。
 
在第一次与第二次大战期间，资本主义经历一次经济危机，其程度之深，影响之大，只有那些为教条主义所支配的共产党，尤其是苏联共产党，才不承认此事实。若与十九世纪的危机相对比，1929年的大危机显示，今天的这类灾祸实足危及其社会秩序以至全部国民生活。 发达的国家——首先是美国——就必须设法逐渐摆脱这危机。美国运用了各种方法，终于实行了全国规模的计划经济。这个变更，对发达的国家及其余世界，实具有划时代的重要性，虽然在理论上并未为人们所充分认识。
 
在这期间，不同形式的极权主义在苏联及纳粹德国之类的资本主义国家有了发展。
 
德国与美国不同，他不能以寻常的经济手段来解决其内部与向外扩张的问题。于是战争与极权主义（纳粹主义）成了德国
垄断资本家的唯一出路，他们自愿服从民族优越论的好战政党的驱使。
 
至于苏联的走向极权主义，我们曾经说过是有其他的原因，那便是为了它的工业改造。
 
可是，还有一个不甚显明的要素，这对现代世界可说是革命性的要素。这要素便是现代战争。战争虽不至引致真正的革命，它却引致突质的变革。不管战后骇人的破坏是怎样，它使世界的关系及各国内部的关系都起了变化。
 
现代战争的革命性质，不但表现于促进技术发明，并且最重要的，是使经济与社会结构发生了变化。在英国，第二次大战，暴露和影响了各种关系，使其达到了大规模的国有化成为不可避免的程度。在印度、缅甸及印度尼西亚，则由战争成了独立国家。西欧的开始走向统一也是战争的结果。并且，这使美国与苏联登峰造极，成为经济上和政治上的两大强国。
 
现代战争对于国民生活与人类的影响，实比以前的战争更为深远。”这有两个原因：第一、因为现代战争必是总体站。无论经济、人力以及其他方面，莫不受到牵连，因为生产的技术水平已十分提高，使国家的任何部分或经济的任何部门都不能超然局外。第二、因为同一技术的经济的及共他原因，世界已在极大的程度上成为一个整体；这里的小小变化常在那里发生反响。于是，每一现代战争都有成为世界大战的可能。
 
这些无形的军事与经济的革命，其范围与意义实非常巨大。这种革命，比靠武力所完成的更为自然；那就是说，它不用有一套意识形态和一个庞大的组织去推动。所以此类革命可以使现代世界的各种趋向纳入较有秩序的轨道。
 
像今日的世界，由第二次世界大战而来的，显然与前已大不相同。
 
人类从物质中心及与宇宙间取得的原子能是最显着的特色，但这却不是新时代的唯一标志。
 
共产党官方关于人类前途所作的预言说，原子能是共产主义社会的象征，正如蒸汽为工业资本主义必备的象征和动力一样。我们虽认为这是极其天真而歪曲的理论，但另有一点却是真实的：原子能已在各国与整个世界引起了变化。当然这些变化并不是趋向共产主义与社会主义的变化，如共产党“理论家”所期望的。
 
原子能这一发见，并不是一国的产品，而为许多国家无数才智之士百年来的成就。原子能的不仅是科学上而且是经济上的应用也是许多国家共同努力的结果。倘若世界不是已成为一体，那末原子能的发见与应用都是不可能的。
 
原子能的效用首先是使世界更趋于统一。因此这就得完全摆腕一切过去沿袭下来的障碍——各种所有权关系与社会关系，尤其是排它性的与孤立的制度与意识形态例如斯大林生前和死后的那种共产主义制度。
 
二
世界大势之趋向统一是我们时代的基本特征。这并不是说，世界早先没有经由不同的道路走向统一的趋势。在十九世纪中叶，就有以世界市场把世界统一起来的趋势。这也是资本主义经济与民族战争的时代。通过民族经济与民族战争，那时已达到了某种世界统一。
 
以后由于不发达地区前资本主义生产方式的破坏，以及发达国家及其垄断企业对它们的分割，世界的统一又再进了一步。这就是在垄断资本主义、殖民征服与战争的时期，那时，垄断企业的内部联系和利益常比国防更有决定性的作用。当时世界统一的大势大抵由垄断资本之离合集散而造成。这是比市场的统一更为高度的统一。某些国家大量输出的资本深入、盘踞各地而支配了全世界。
 
今日世界统一的大势显见于其他领域；在生产的极高水平上，在现代科学上，在学术思想及其他思想上都可看到。但要统一趋势再向前进，那就不可能仍在排它的国家基础上，或者把世界分成个别而垄断的势力范围所能办到。
 
走向这种新统一，即生产统一的大势，是建筑于前期成就的基础——也即市场统一与资本统一之上的。但这些基础却与那已紧张而不适当的民族的、政府的关系，尤其是社会的关系彼此冲突。以前的统一是由民族斗争或势力范围的争夺战而达成，而现今的统一则必须破坏前期的社会关系，只有这样它才能成功。
 
今后世界生产的调整与统一之态势如何，  是用战争抑或用和平的手段，恐怕谁都不能断言。但是这一大势的不可阻挡，那是毫无疑问的。
 
第一个统一方法就是战争，这是以武力来促成统一，也就是由这一集团或那一集团来控制。但这样的结果，势必遗留下灾祸、互相冲突、彼此不公的新火种。以战争求统一的方法必然要牺牲弱者和失败者。  战争纵能建立有秩序的一定的关系，但必仍有未解决的纷争，而加深彼此的误解。
 
因为今日的世界冲突，主要是以制度的对立为基础，故其性质为一种阶段斗争，而非民族与国家间的对立。这便是时局所以非常严重而紧张的由来。将来的战争都将不止是政府与政府间及民族与民族间的世界大战和内战。不但战争本身的情况令人惊惧，并且其对自由发展的影响也是非常可怖的。
 
以和平方法来达到世界统一，虽比较缓慢，却是唯一稳妥健全而正当的道路。
 
当前世界的统一将由制度的对立而达成，看来与前期统一之由（民族的）对立而获致者不同。
 
这并不是说现今一切的冲突只由制度的冲突而来。自然还有其他的冲突，包含以前各期的冲突在内。经由此种制度的冲突而达到世界生产统一的大势，现在已经明白地，积极地表现出来了。
 
但若以为世界生产的统一在最近的将来便可达到，那却不合事实，这段过程要经过一个长时期。因为这需要在经济上与其他方面居于人类领导地位的国家进行有组织的努力才能办到，何况生产的完全统一实际上是不可能达到的。初期的统一决不是什么最后的统一；如今世界生产的统一也不过是一种趋势，至少最发达的国家是向往生产统一的。
 
三
第二次世界大战的终结已经证明这制度对立的大势是遍及，世界的。所有处于苏联势力下的国家，以及德国、朝鲜的一部分大体上都是同一制度。西方的情形也是这样。
 
苏联领袖对这一过程是完全了解的。我记得在1945年某一机密集会中，斯大林说道：“在现代战争中，胜利者要将其制度强加于人，这是过去战争所没有的。”他说这话时战争尚未结束，同盟国间之友爱、希望及信任正达到最高峰。在1948年2月，斯大林又对我们南斯拉夫人及保加利亚人说：“它们，西方国家要在西德建立起他们自己的国家，我们则要在东德建立起我们自己的国家，这是不可避免的。”
 
今天要对斯大林生前死后的苏联政策做一评价，这不仅是时髦的，也是相当合理的。然而这些制度并非由斯大林发明，而其继承人也与他一样对此抱有信心。所以自斯大林死后，所变更者只是苏联领袖处理不同制度间关系的方法，而不是制度本身，赫鲁晓夫不也是在第二十次党代表大会上，提出其“社会主义世界”、“世界社会主义制度”，好像是一种特别不同的组织吗？实际上，这不过表示其坚持制度的对立，坚持共产主义制度本身的格外排它与其独霸的统治而已。
 
因为西方与东方之间的斗争主要是制度的冲突，所以必然是表现为思想斗争的形式。其间虽然有暂时的妥协，但是思想的战争却并不因此稍减，这不过是麻醉敌对阵营使其不觉的手法。物质，经济、政治和其他方面的冲突愈为尖锐，使人觉得好像完全是思想的冲突。
 
除了共产主义与资本主义的对立外，尚有第三类国家，他们都是刚从殖民地而得到独立的，如印度、印度尼西亚、缅甸及阿拉伯国家等。这些国家，为了摆脱经济的隶属关系，正力谋建设独立的经济。但在他们内部夹杂着几个时期与许多制度，尤其是两个现行的制度。
 
这些转变中的国家，主要是为了其自己民族的理由，他们忠实地拥护国家主权，和平，互相谅解等类似的口号。但是他们到底不能消灭两个制度的冲突。他们只能设法加以缓和。并且，他们正是两个制度的战场。所以他们的努力虽极有意义和高尚，但在今天却不能发挥决定性的作用。    ，
 
这里值得注意的是两个制度各想以其自己的形式来统一世界。他们虽然都认为有世界统一的必要，但他们的立场是截然相反的。因此，今日世界统一的大势是表现于两个敌对势力的斗争中，其斗争之激烈为和平时期前所未闻。
 
如众所周知的，这一斗争之思想与政治的表现便是西方民主主义与东方共产主义。
 
由于政治的民主与较高的技术及文化水平，这种漫无组织的倾向统一的趋势，在西方表现得较为强烈，同时西方还是维护政治自由与知识自由的战士。
 
在这些国家中，这种或那种特定的所有权制度使统一的趋向受到阻止或者得到鼓励，这要看实际情形而定。但是统一的要求是很普遍的。今日妨碍这种统一的最大阻力是垄断制度。他们依据其自己的利益而要求统一，但其所借以达成统一的是已经陈旧的方法——用划分势力范围的形式。与之对立者，例如英国工党，也力主统一，其方法则不同。要求统一的趋势在英国也很强烈，因而促其实行国有化。此外，像美国那样也在实行更大规模的国有化，不过其方法并未变更所有权的形式，而是将很大一部分国民收入归政府掌握。倘若美国真能使其经济完全国有化，那末现今世界统一的趋势自将大受激励。
 
四
社会与人群的规律之一就是扩大生产并使之完美。这一法则已在当代的科学、技术及思想等水平上自行证明，世界生产正趋于统一。一般说来，若使人达到更高的文化与物质水平，这一趋势将更为不可抗拒。
 
西方要求世界统一的大势表现在经济，技术及其他需要上，并在这些因素后面，还有政治的所有权与其他力量。苏联阵营的情形是不同的。东方的共产党国家，纵然假定其并无其他理由，但因其比较落后，也不得不在经济上、思想上孤立自处，而以政治的手段来补偿其经济及其他方面的弱点。
 
说起来奇怪，但这却是真实的情形：共产主义的所谓社会主义的所有制实为世界统一的最大阻碍。因为这个新阶级的集体与全面的控制已造成了一个阻碍世界统一的孤立的政治经济制度。这个制度纵能有所变化，但极为缓慢，并且几乎完全不能与其他制度混合交流而趋向团结。它的变化只在为了增强其自身的势力。这个制度既导致一种类型的所有权、政府及思想，它本身必然是孤立的，也势必是排它的。
 
即令苏联的领袖们希望统一世界的实现，但他们所想象的只能是多少与其自己相同的，而且属于他们的世界。他们虽高唱制度的和平共处，但决不是说各种制度交流混合，而是一个制度静存于另一制度之旁，直至另一制度，即资本主义制度，归于失败或者内部崩溃为止。
 
存在着两个制度间的冲突并不意味着民族的及殖民地的冲突已告终止。相反地，两个制度的基本矛盾却通过民族及殖民地性质的冲突表现出来。例如关于苏伊士运河的斗争，虽然幸未转变为两个制度间的战争，但是斗争依然存在：这便是埃及的民族主义与碰巧以老殖民国家英、法为代表的世界贸易间之争执。
 
因为这些关系，所以国际生活各方面极为紧张是必然的。冷战已成了现今世界和平时期中的可常状态。冷战的形式虽已有改变并正在改变中；它时或缓和，时或紧张，但却已不能在一定的条件下加以消除。这必须先消灭更深的东四，即把植根于现今世界，现行制度，尤其是共产主义的性质的东西加以消灭才行。今日造成局势日益紧张的冷战，其本身实为其他更深刻和早已存在的矛盾因素的产物。
 
我们今天所处的世界是一个不安定的世界。科学向人们揭示，这是一个令人茫然和高深莫测的世界；它又是一个面对现代战争武器威胁，而令人震惊于宇宙毁灭将要到来的世界。
 
这个世界终须以某种方式改变。它不能老是这样子，一方面分裂而另一方面却不可抗拒地要求世界的统一。从这纷争中所最后出现的世界关系，既不是理想的，也不免于争执。但是一定比今日的世界关系好。
 
但是，现今制度的冲突并非表示人类将走向单一的制度。这种冲突只表示世界之更进向统一，更准确地说，即世界生产的统一，将通过制度间的冲突而达到。
 
世界生产统一的趋势，并不能使生产的形式到处相同，那就是说不能使所有制与政府等都趋相同。生产的统一只表示消除传统的与人为的障碍，而使现代生产活跃和更有效率，这是说要把生产更圆满地适应于地方的，自然的，国家的，以及其他的情况。这种统一的趋势必将使世界生产潜力得到更好的调整和利用。
 
所以世界上没有流行单一的制度是一件幸事。相反地，不同的制度太少实为一种不幸。尤其真正糟糕的是：不论哪种制度，都有排它的和孤立的性质。
 
社会单位、国家与政治制度间彼此的日趋不同，以及生产效率的日趋提高，是社会的法则之一。人们于是互相结合，与其四周的世界相适应，但在同时，却也日益个别化。
 
未来的世界可能日趋繁复，同时也更为统一。最当前的统一，可能是多种形式与人格的配合，而不是形式与人格的划一。至少到此时为止，其趋势是这样的。形式与人格的划一，意味奴役与停滞，而不是生产比今日更有高度自由的意义。
 
一个国家，倘若对于世界行程和趋向，不能有真正的认识，那末它就得付出重大的代价。它将必然落后，结果不管其人口与兵力有多大，仍不得不与世界的统一相适应。谁也不能逃避这形势，正如过去没有一国能够拒绝资本的进入，并经由世界市场而与其他国家发生关系一样。
 
这也就是今日自给自足或排它的国民经济，不管其所有权的形式或政治秩序、甚至技术的水平是怎样，必将陷于不可解决的矛盾与停顿的由来。并且，这在社会制度与思想等方面也是如此。凡是孤立的制度只能供应极低的生活；它不能解决由现代技术与现代思想所引起的问题而向前迈进。
 
世界的发展偶然地推翻了斯大林式的共产主义理论，即一国可能建成社会主义或共产主义社会，它使极权主义的专制政治更加增强，即加强了新剥削阶极的绝对统治。
 
在这种情形下，要在一国或许多国家内建立社会主义或共产主义或任何其他种类的社会，而与整个世界相隔离，其结果势必造成专制与暴政的强化。并且，还使该等国家求取经济与社会进步的国民潜力大为削弱。反之，国家建设与世界上进步的经济及民主的希望和协调，才能普通给人民以更多的面包与自由，而货物的分配更为公平，经济的发展也步调正常。要达到这一点的条件就是必须改变现有的财产及政治关系，特别是在共产主义制度下的那些关系需要改变，因为统治阶级的垄断制度对于国家的与世界的进步，纵然不是唯一的、也是最严重的障碍。
 
五
因为其他的原因，世界统一的大势也影响到财产关系的变化。
 
政府机关在经济上日益增强而具有决定性的作用，以及对  所有权的掌握扩大，也可说是一种世界统一的大势。自然，这在不同的制度与国家中有不同的表现；并且，在某些地区，例如在共产党国家中，形式上的国有化制度，因其本身实隐藏着一个新阶级的垄断与极权统治，甚至竟成为世界统一的障碍。
 
在英国，由于工党的国有化运动，其私人所有权，更正确地说是垄断所有权，已在法律上丧失其神圣不可侵犯性。20%以上的英国生产力已经国有化。而在斯堪的纳维亚半岛诸国，则除了国家所有制以外，更有集体所有制的合作社形式在发展中。
 
政府在经济上作用的日益增强，是近来殖民地及半独立的国家的显着特色；无论该国之有社会党政府（缅甸），或议会民主政治（印度），或为军事独裁（埃及），其政府都提供大部分投资；管制出口，掌握大部分出口资金等。政府到处都以经济改革的倡议者出现；而所谓国有化更经常地成为所有权的一种形式。
 
在资本主义高度发达的美国，情形也并无不同。不仅谁都可以看到自1929年大危机到现在，其政府在经济上的作用日趋增大，并且很少有人否认这种作用是势所必至。
 
沃克(James Blaine Walker）在其所着《美国工业史话》 【纽约哈普尔公司（ Harper）1949年版。】(The Epic of American Industry)中强调说：“美国政府与其经济生活间关系的日益密切是二十世纪显着特征之一。”
 
沃克指出在1938年美国国民收入约有20%已社会化，但到1940年，这百分比至少已达到25%。政府对国民经济的系统的计划开始于罗斯福总统。同时，政府人员数目及政府业务，尤其是联邦政府的，也日趋增大。约翰逊(Johnson)与克罗斯(Kro-ss)在其所着《美国经济的起源与发展》【纽约普伦提斯一霍尔公司（Prentice-Hail）1953年版。】（The Origins & De-velopment of the American Economy)中，也有同样的结论。他们肯定经理机构已与所有权相分离，而政府则有如债权人，其势力大为增加。他们说：“二十世纪的主要特征之一便是政府，尤其是联邦政府的势力在经济事务上的不断增加。”
 
又如克拉夫(Shepard B．Clough)在其所着《美国方式》【纽约克罗韦耳公司（T. Y. Crowell）1953年版。】(The American Way)中，曾列举数字以证明此种论点。如他所述，联邦政府的支出与公债，有如下表：
 
 年    份    联邦政府的支出    公 债（联邦）
               （单位：百万美元）   （单位：千美元）
    1870           309.6        2，436，453
    1940         8,998.1         42,967,531
    1950        40,166.8        256,708,000
 
克拉夫在该书中所说的“经理权的革命”，是指职业的经理人员的兴起，老板们没有了他们简直对事业无法经营。经理人员的数目，作用与团结正在美国继续增强。现在如洛克菲勒，约翰?瓦纳马克尔，查尔斯?施瓦布等那样的大企业天才家，不再出现于美国了。
 
芬索德(Fainsod)与戈登(Gordon)在所着《政府与美国经济》【纽约诺顿公司(W．W. Norton)1941年版。】(Government and  the American Economy)中指出：  政府已在经济中发挥了作用，各社会团体也想在经济生活中利用这种作用。但是，现在这里却有些主要的不同之点。上述作家所写的政府管制权力，不但出现于劳工范围，  且及于生产方面——如运输，天然气，煤炭及石油等关系全国的经济重要部门，无不受到干涉。他们说“新的广大的变化，  从公用事业的扩展与对自然资源及人力资源的保护日益关切等情况，也可明白看到。而在银行与信贷方面，在电力以及低价房屋的供应上，公用事业尤为重要。”他们认为政府所发挥的作用，比较半世纪，甚至十年以前，远为重大。“这些发展的结果产生了一种‘混合经济’，在这种经济制度下公用事业，一部分由政府管理的私人企业，以及比较不受政府管制的私人企业全都并存。”
 
上述作家和其他作家都列举此种发展的面面观，同时，更指出社会日益增长的需要，如社会福利、教育、及各种类似的福利都是由政府机关供给的，而政府所雇用的人员也作相对的及绝对的不断增加．
 
我们可以了解到，这种发展，曾因第二次世界大战时期的军事需要而大为促进。但是，大战以后，却未减退，并且以大于战前的速度继续发展。这不但在民主党执政时如此，甚至在1952年当选总统的艾森豪威尔的共和党政府，虽其口号为恢复私人创造力，却仍不能从根本上作任何变更。在英国的保守党政府执政时期情形也是相同的；除了钢铁工业以外，并未能解除其他工业的国有化。保守党在经济上的作用，与工党政府的作用比较起来，虽然并未增加，却也未有根本的削弱。
 
这种政府对经济的干涉显然是久已深入人心的客观趋势所造成，自凯因斯以来，所有认真的经济学家都主张国家对经济有干涉权。现在这多少已成为遍及世界的事实。国家干涉与国家所有权实为今日经济上一种主要的因素，在有些地方且是决定性的因素。
 
由上所述，我们几乎可以得到这样的结论，即在东方制度下，国家起着主要作用，而在西方制度下，私人所有权或者垄断企业与公司的所有权起着主要作用；  两者在事实上并无差别和根本矛盾。而且，由于私人所有权在西方的地位正日趋没落，国家的控制力大为增加，像这样的结论似乎更有根据了。
  
但事实却是不然。因为其间除了制度的不同以外，国家所有权与国家在经济中所起的作用也有主要的差别。固然，国家所有权，在表面上，多少都出现于两种制度之中，但他们是两种不同的、甚至矛盾的所有权形式。这也适用于国家在经济中的作用这一点上。
 
没有一个西方政府对经济的关系是像—个所有者。事实上，西方政府既不是国有财产的主人，也不是由税收所得之款项的所有人。因为政府常有变更，所以，它不能成为一个所有者。关于财产之经理与分配，他必须受议会的监督管制。在财产的分配中，政府须受各种势力的支配，所以它不是一个所有者。它所做的只是对于不属于他的财产，代为经理与分配，不论办得好坏。
 
但在共产党国家中，情形却不同。政府有权经理并分配国家财产。这个新阶级，或其执行机关（党的寡头统治），便自作为所有主，并且也真是所有主。像这种经济上的垄断，连那最反动的资产阶级的政府也梦想不到的。
 
总之，西方与东方在所有权上表面的相似点实在是真正最深的不同点，甚至是相互冲突的因素。
 
六
甚至在第一次世界大战以后，所有权的形式可能就是西方与苏联相冲突的主要原因了。那时候，各种垄断企业即发挥了重要得多的作用，它们不容许世界上任何一部分，特别是苏联，摆脱它们的支配。至于共产党官僚集团之成为统治阶级则只是近来的事情。
 
在苏联与各国的交涉上，所有权关系常是重要的因素。苏联对其特殊的所有权形式与政治关系，只要有可能，就不惜以武力来强制推行。不管它与世界各国的贸易关系发展到何种程度，它也跳不出货物交换的圈子，这是在民族国家时代所能做到的发展。这种情形，在南斯拉夫与莫斯科决裂时期，也是如此。因为除了货物交换以外，南斯拉夫也不能发展任何一种重要的经济合作，虽然它曾经而且依然希望能够如此。所以该国的经济还是孤立的。
 
此外还有使此种情形与关系更加复杂的因素。纵令西方对世界生产统一的大势加强，这并不能说有助于不发达国家；事实上，这不过更加强一国——美国——的，或者至多是数国的优势而已。
 
因为正由于交换的关系，不发达国家的经济与国民生活受到剥削，而被迫臣服于发达的国家。这就是说，在不发达国家，倘若想生存，  那就必须以政治手段把自己关闭起来借以自卫。这是一法。另一办法便是接受发达国家的外援。此外没有第三条路。直到现在仅有第二条路正在开始，援助的数量还很小。
 
今日美国工人与印度尼西亚工人彼此间的悬殊，实比美国工人与美国的富有股东之间的更大。根据联合国的资料，在  1949年，美国居民每人平均所得至少是一千四百四十美元，但  印度尼西亚工人则不过是其五十三分之一，即二十七美元。并  且大家公认，在发达与不发达国家之间，物质及其他方面的悬殊  并未减少，相反地，却有增加。
 
西方发达国家与不发达国家间的不平等主要表现在经济方面。由总督与地方贵族实行的传统的政治统治已成过去。现在，政治虽然独立而经济尚未发达的国家，其民族政府通常是他国的附庸。
 
今日谁也不愿接受这种隶属关系，正如谁也不愿放弃那由扩大后的生产力所能得到的利益一样。如要美国的或西欧的工人（且不必说所有主），自愿放弃由高度技术与更多的生产工作所得到的利益，固是不可思议的事；正如要劝告贫困的亚洲人民，说他们应该乐于接受如此微小的工作报酬，同样是不可思议的。
 
政府间的互助和各国人民间经济及其他不平等的逐渐消除，必须由需要而产生，以期成为善意的种籽。
 
目前，经济的援助大抵只给予那些购买力与生产力都很低，已变成发达国家的负担的不发达国家。今日两个制度的冲突，对于真正经济援助的扩展是主要的障碍。这不仅由于巨大经费用于军事一类的用途；也由于当今的各种关系仍是生产发展与统一大势的阻力，结果，对不发达国家的援助以及发达国家本身的进步都受到阻碍。
 
在发达国家与不发达国家之间物质的与其他的差异，也表现于他们的国内生活上。有人以为西方的民主只是表现富有国家共同对贫弱民族的劫掠，这说法是完全不正确的；西方国家，远在其取得殖民地超额利润以前，早已是民主的，虽则当时民主水平比今日的低。西方国家今日的民主与马克思和列宁生时的民主之间唯一的联系，是在于两个时期间的继续发展。过去的民主与现在的民主之间的相似点，比起自由的或垄断的资本主义与现代的国家主义之间的相似点来，当不会大好多。
 
英国社会主义者比万(Aneurin Bevan)在其所着《免于恐惧》(In Place of Fear)中说道：
 
“我们必须把自由主义的用意与其成就分别清楚。自由主义的用意是赢得权力，借以实行工业革命所造成的财产的新形式。但其成就则使人们，不论其有无财产，都赢得了政治权力。【西蒙与舒斯特（Simon & Schuster）公司，纽约1952年版，第9页。】
 
“……以历史的眼光看来，在普选制度之下，议会民主的作用实在于将财富特权暴露于人民之前而受其攻击。这是指向财产权力心脏的一把剑。议会便是争论之比武场。”【同上，第6页。】
 
比万的观察适用于英国。也可普遍适用于其他西方国家，但却只能以西方为限。
 
在西方，使世界走向统一的经济手段占主要地位。在东方，共产党方面，占主要地位以使世界统一的却是政治手段。苏联只能以征服的方式来达到“统一”。由此点看来，连新政权也不能从根本上改变任何事物。依照苏联的观念，被压迫的民族只是指那些被其他国家政府，而不是苏联政府，所加以统治的民族。苏联政府之所以不惜援助它们，甚至贷款给它们，无非为它的政治需要。
 
苏联经济尚未达到足以促进世界生产的统一的程度。苏联的矛盾与困难大多来自内部。纵与外界脱离，其制度本身尚能存在。这虽费很大的代价，但其成功是靠普通使用武力。这样的情形自不能持久，总有一天到达极限。到了那天，这将是政治官僚集团或新阶级的无限制专政之终结的开始。
 
当今共产主义最多不过能用政治手段——用国内的民主化和对外面世界更求接近——来达到世界统一的目的。然而，这还是十分遥远的事情。这是否真有其可能呢？
 
共产主义对其本身和外面世界的认识到底是怎样的呢？
 
在垄断时代，经过列宁修正的马克思主义，对沙皇俄国及同类各国所处的内外关系的观察，一度相当正确。得到这认识的鼓励，列宁所领导的运动终于战胜。在斯大林时代，这同一意识形态，有经过一番修正，它对于这个新国家在国际关系上的地位和任务的推断也近于实际，相当正确。当时的苏维埃国家或新阶级的内外地位甚为优越，一切可以如愿以偿。
 
但是今日的苏联领袖们却不容易这样来自谋安排了。他们不再能看到当今世界的现实。他们所看到的世界不是真实存在的世界。它只是一个在过去曾经存在的，或者是他们想当然存在的世界。
 
因为死抱着陈腐的教条，所以共产党领袖们以为其余的世界将停止不动，而在冲突斗争中自趋毁灭。但这却未曾发生。西方在经济上与知识上都进步了。他们在受到另一制度威胁的危险时，确实联合起来了。殖民地被解放了，但并没有变成共产党国家，也不因获得自由而与其旧日的宗主国断绝关系。
 
西方资本主义将经过经济危机与战争而崩溃的情况并没有发生。1949年时，维辛斯基以苏联领导的名义，在联合国中预言美国与资本主义的一个新的经济大危机就要开始了。但是适得其反。这并不是由于资本主义之好或坏，而是由于苏联领袖们所指贵的资本主义已不再存在了。苏联领袖们看不到印度、阿拉伯国家与其他类似的国家已获得独立，直至他们为自己的利益而证实其外交政策上苏联观点的时候才恍然大悟。苏联领袖们根本不曾知道而至今也不懂社会民主主义。他们只知拿那衡量过在其本国决斗场中社会民主党人命运的尺度，来衡量社会民主主义。苏联领袖们的思想是基于这一事实，即他们本国并未像社会民主党人所预见的那样发展，因而他们论断西方的社会民主主义既不合实际而又“大逆不道”。
 
至于谈到他们对于基本冲突——两个制度间的冲突或生产统一的基本趋势——的估计也是如此。在这儿他们的估计又不准了。
 
他们认为这种冲突是两个不同社会制度的一种斗争。一个当然是他们自己的制度，他们说在那里已没有阶级，或者阶级已在消灭的过程中，并且说他们的制度是国家所有制。另一个是外国的制度，他们力言在那里有激烈的阶级斗争与经济危机，由于所有的物资都属于个人私有，并且力言那里的政府只是一小撮贪婪的垄断资本家的工具。因为他们对世界的观察如此，所以他们相信倘若西方上述种种关系能够不起支配作用，那么今日的冲突便可避免。
 
困难就出在这里了。
 
纵或如共产党之意，西方没有上述种种关系的支配，冲突还是要继续不止的。也许这样一来，冲突还更要严重。因为不但所有权的形式势将不同，还有彼此间的不同的、相反的愿望问题。而在这些愿望的后面还站着现代的技术与所有各国重大的利益，以致各团体、各党派、各阶级都想依据其自己的需要来解决同一问题。
 
当苏联领袖认为西方国家是垄断资本家之盲目的工具时，其错误正如说他们自己的制度是无阶级的社会、而那里所有权都属于社会一样。诚然，垄断企业在西方国家的政治上居于重要的地位，但今日已与第一次世界大战前不同，甚至可说已与第二次世界大战前不同，垄断企业的地位完全变了，也没有以前那样的重要了。因为在背景上已出现一些新的更为主要的东西；这就是趋向世界统一的不可抵抗的愿望。现在，通过国家主义与国有化政策，即通过政府在经济中的作用，这种愿望表现得更为强烈，超过了过去由垄断企业的势力和行动所表现者。
 
如果到了这种地步，有一个阶级、一个政党或一个领袖完全阻塞批评，或掌握绝对权力，那末他对现实的判断必然陷入不切实际，自负而虚伪的境地。
 
这就是今日共产党领袖们的情形。他们不能控制其自身的行为，却被现实所支配。这样倒有些好处，他们现在比过去成为更实际的人物。但是，这样也有不利的地方，因为这些领袖们根本缺乏现实的甚至近乎现实的见解。所以他们得花更多的时间为自己辩护不接受现实而攻击现实，却费很少时间设法去适应现实。他们只知依据陈腐的教条来作无意义的行动，到了经过较成熟的考虑，他们时常抱着流血的脑袋退却。我们希望这种情形能在他们之间多多出现。诚然，倘若共产党人对世界作实际的解释，尽管他们会失败，但是他们将得到收状，而成为人类和人类社会的一部分。
 
无论如何，世界总要变的，并且将依照其向来行进和继续行进的方向走向更多的统一、进步与自由。现实的力量与生命的力量比任何暴力更为强大，比任何理论更为真实。



