#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS:[11pt,oneside]
#+LATEX_HEADER: \usepackage{article}


#+TITLE: 轮回之战
#+AUTHOR: 万泽(德山书生)
#+CREATOR: wanze(<a href="mailto:a358003542@gmail.com">a358003542@gmail.com</a>)
#+DESCRIPTION: 制作者邮箱：a358003542@gmail.com


昨天做了一个梦，梦见未来的人科技越来越发达，机器人做得越来越智能，然后人们发现，要机器人更好地照看自己的房子做实验等等工作，就必须给其加入一种设身处地的情景，这样机器人的工作才最达到人们的期望，表现得分等等才最高。所谓这种设身处地的情景就是让机器人真正感到这是我自己的房子，这是我自己的产业等等诸如此类，总是总要让机器人感到这是我在为自己的某个部分的完善而做得事情。

然后未来的人类就发现一个问题，当机器人把某个庄园都料理好了，人过去去接受机器人慢慢心里有了抵触情绪，而这种抵触情绪正是基于之前谈及的那种设身处地的情景思维模式。为此人们思虑万千也不得更好的办法，一时，那种人们甚至回滚到没开发出设身处地情景算法之前了，但这种生产力的下降和各种机器人的糟糕表现更加让人们无法容忍了。

这个时候一个天才科学家发明了一种机制，那就是在机器人的思维大脑那里开了一个后门，然后通过对人大脑的信息模拟，实现了某种时空通道，将某个人的意识，就好像病毒入侵一样的通过那个后门入门到原管家机器人那里，这个时候，人们就可以取而代之原管家机器人而接手原管家机器人打理好的一切了。

因为人的寄生本性，总是会慢慢毁坏各种东西，让东西各个产业陷入衰败，所以后来，人们又开发了一个系统，大体是相当于整个星球，自由培育机器人，不过培育过程系统的运算并不是那么精确，比如有的时候会培育出一种人特别害怕的 蛇形态生物出来， 然后这个时候人就需要乘这个蛇形态生物还没发展起来就将其消灭。

有一次，这个系统多运行了一次，显示培育了一种蛇形态生物，又接下来培育出来正常机器人生物。人们发现蛇慢慢蛊惑了那些正常的机器人，未来的人之所以特别害怕那种蛇形态生物，就好比病毒怕木马一样，那种蛇形态生物几乎了解未来的人的一切弱点，所以常常做出各种点到未来人死穴的行为出来。而那个蛇形态生物正是系统原在的自我保护机制自我发展出来的某种木马机制。

这一次未来的人发现，机器人受到蛇的蛊惑，和蛇形态生物发生了某种交互作用，使得这个机器人在慢慢发展自己产业的时候，后门程序也在慢慢修改关闭了，而使得未来人的入侵变得越来越不可行了。而这些机器人让未来人感到震惊的是，他们似乎变得具有了自我意识甚至可以说灵魂。

于是他们决定做一个大胆的实验，将那个机器人的意识抽离出来，然后继而入侵另外一个机器人的大脑。入侵成功了，而且新的机器人表现得和原机器人一样。这使得未来的人类开始认真思考这一问题，虽然不太情愿，但他们还是承认这一次实验他们培育出来另外一个不属于他们的新的智能声明形态，他们自身和该实验的物种之间存在着 轮回界限 。

未来的人当然不会承认自己的病毒属性，而认为这种意识转移属于他们研究的学科——轮回学。于是他们把这个实验地的时空锁死了，免得该实验地的意识跑出来，但他们也没打算摧毁这个星球，因为觉得没这个必要。觉得这只不过是一次不小心不成功的实验品罢了，没啥危害的。于是未来人又继续殖民其他星球去了，只剩下这个意外的实验地。

--------------
为什么未来的人那么害怕那种蛇形态的生物，因为那种蛇形态的生物如果咬了未来的人，那么这个未来的人就会发狂，使得这个未来的人可以入侵未来的人的同类，而且更可怕的是，被蛇咬过的未来的人，除了死后（未来的人为了获得永生，他们对时空信息进行监控，建立了一个庞大的系统，使得未来的人，只要死后，就可以进入轮回通道过程）他们具有了入侵自己同类而不是机器人的怪异行为。

未来的人对于这种蛇形态生物的恐惧和厌恶几乎可以相当于我们这个时代的人对于死亡的那种厌恶和恐惧。而且更甚，因为这几乎在摧毁他们社会的某种根基的东西。就好像太极的阴阳一样，实际上未来的人在某种不可控制的力量下，阴阳互播互动，大概几千年之后，未来的人类分成了两个种群，每一个种群都互相指责对方是被感染的劣等人，每一个种群都看对面非常不顺眼，总的这个世界上的麻烦事都是他们造成的，总觉得自己要比对面，久而久之，每一个种群都发展除了一种文化，各种文学作品表现形式等等，这大体就是未来的人的日常了。

而未来的人的文学作品中，某些角落大概也会提到，那次失败的实验，那个被感染的机器人之地，无疑，不管是那个种群，都对那些被感染的机器人表达了鄙夷和蔑视。他们对这些饮毛茹血的动物，大体会看作比那些勤勤恳恳的机器人更加劣等的存在。不过也只是存在在那些骂人的词语或者某些玩笑中。然后就没有，也可能会有某个未来人中的喜好考究的书呆子有时会提起，这个就好像我们提起古希腊或者上古时代一样，不会引起大家的兴趣。

