#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS:[11pt,oneside]
#+LATEX_HEADER: \usepackage{article}


#+TITLE: http学习笔记
#+AUTHOR: 万泽(德山书生)
#+CREATOR: wanze(<a href="mailto:a358003542@gmail.com">a358003542@gmail.com</a>)
#+DESCRIPTION: 制作者邮箱：a358003542@gmail.com


* URL结构
URL结构如下:
#+BEGIN_EXAMPLE
scheme:[//[user:password@]host[:port]][/]path[?query][#fragment]
#+END_EXAMPLE

其中:
- scheme :: 描述访问服务器的协议，也就是如何获取该资源，最常见的是http，此外还有ftp等。
- user:password :: 这里用于http认证
- host :: 那里获取资源
- port :: 连接端口号是多少
- path :: 具体访问该资源的path
- query :: 其他额外参数
- fragment :: 片段，为client使用。还有一个params不太常用。

URL是只支持ascii字符表示的，其他的字符要经过utf-8编码操作。具体转义字符是 ~%~ ，比如空格SPACE，具体在URL中的表示就是 ~%20~ 。即使是ascii里面，也有一些字符需要转义，然后比如中文字符等，也需要如此utf-8编码和转义。比如 "书"

#+BEGIN_EXAMPLE
>>> '书'.encode('utf-8')
b'\xe4\xb9\xa6'
#+END_EXAMPLE

在URL中对应的就是 ~%e4%b9%a6~ 。还有其他一些细节，当然实际操作中各个编程语言都提供了良好的函数接口了的，比如python的urlencode函数。


* http header详解
本小节主要参考了 [[http://kb.cnblogs.com/page/92320/][这个网页]] ，内容整理得不错，都搬过来了。



* 名词解释
- MIME type :: 其全称是Multipurpose Internet Mail Extensions ，可以看得出来和email系统有关，但不管怎么说，我们知道其在http里面用于描述文件类型即可。具体就是对应的
#+BEGIN_EXAMPLE
Content-type : image/jpeg
#+END_EXAMPLE
这一行，image/jpeg 就是MIME type描述，image是主文件类型，jpeg是次文件类型。最常见的是html文件，其MIME type是 ~text/html~ 。

- URI :: Uniform Resource Identifier ，此外常见的还有URN和URL概念。参考了 [[http://stackoverflow.com/questions/4913343/what-is-the-difference-between-uri-url-and-urn][这个网页]] 。URN和URL都属于URI的范畴，也就是都视同用一连串的字符串来将所有的资源文件分别表示出来，而URN和URL是两种不同的标识方法，URL有点类似于门牌号码街道的描述，其大致有如下结构:

#+BEGIN_EXAMPLE
scheme:[//[user:password@]host[:port]][/]path[?query][#fragment]
#+END_EXAMPLE

而URN比如:
#+BEGIN_EXAMPLE
urn:isbn:0451450523
#+END_EXAMPLE

目前几乎绝大部分URI就是URL，URN只在某些特别领域使用。

* 参考资料
1. http权威指南





