#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS:[11pt,oneside]
#+LATEX_HEADER: \usepackage{article}


#+TITLE: 大陆人的命运
#+AUTHOR: 万泽(德山书生)
#+CREATOR: wanze(<a href="mailto:a358003542@gmail.com">a358003542@gmail.com</a>)
#+DESCRIPTION: 制作者邮箱：a358003542@gmail.com


作为一个热爱学习的汲汲以求者，我的运命充满了波折，我曾经以为那都是自己的性格使然，但现在我看清了，这一切都是大陆人不可回避的命运。

大学毕业以后，本想好好在一家塑料厂里面干，可恰好发生了08年金融危机，而我在的塑料厂因为车子销量的影响订单下降得非常严重，而那个上海人主管渐渐的越来越对我发各种脾气，曾经我以为那是我做的不够好，现在想来其就是要裁员罢了。当时不自知的我辞职的时候说的是，追求个人更好的发展。

时金融危机之下，我只想找一个和化学相关的工作而不得，在那种大环境下，都可想而知的。于是无论个人怎么努力，无论个人怎么选择自己道路，在这种历史大势下，在这种经济大环境下，他将只有命运。

在那个时候我经历了我人生的最低谷，后来决定去考研，去追求学术，而我的个人经历告诉我，在现在大陆这种政治环境下，所谓的学术不过是为了骗经费罢了。加上学校的资源严重分配不均，渴求上进的我自己努力学习计算机，学习编程，并梦想着能够将化学和计算机结合起来，来真正做一些更有价值的东西出来。

个人的力量是渺小的，要做出的好的东西常常需要很多人往一个地方使劲，而作坊式的大陆工厂环境，只求压缩成本，两个人做的事，他们希望找一个人就全部做出来，两个月才能做完的事，他们希望一个月就做出来。一切都是为了压缩成本，这本无可厚非，但正如前面提及的，个人的决策，个人的道路，终将因为大环境，历史大势而变得毫无意义，无论如何，等待大陆人都是一样的运命。

刻苦的自学，遇到的是苛刻的要求工作经验的公司大环境，而我终于于去年进了一家IT公司，这家IT公司前面就已经解散了，我在他们还没有解散就已经内心充满了不安感，然后离职了。然后又去了上一家，这一家最后把我开除了，因为我迟到了两次，那是我根本无曾预见的，我还本想，因为我自知自己的不足，我还本想，呆在深圳一个狭小的小单间在努力提升自己，多学点东西。而现在想来，那个技术主管，死死逮住我迟到两次不放，就是因为他要裁员，而别人不曾言及的，我在这里要大声出来，那就是15年中期，大陆已经开始发生经济危机了。

再一次，大环境历史大势，将个人的命运吹起，肆意的蹂躏。

我从16年到深圳来，面试已经十几次了，跑了这么多公司，各色各样，一开始，我还总觉得我不会说话，所以才总会被别人最后拍板不行。因为人家在最后面试之前，有急着周六我过去面试的，有看了我的笔试结果人事就有说有笑的过来，最后由那个创始人来否决的。我在这里讲的就是历史大势和个人命运的冲突。

那就是，公司都活不下去了，个人更加活不下去了。面试再好技能提得再高，也挡不住经济恶化，于是那些用人单位人事部门总要做事情的啊，于是就一个劲的提高对应聘者的要求，恨不得你一个人能够把所有的问题解决了，比如今天那个土流网发给我的笔试题目有九道大题，这些题目全部都是项目里面的难点，而且特别难的那种，然后他希望可能遇到一个天才，帮他们全部都解决了。而这些题目，你几乎可以看作就是实际项目，甚至可能国外特别厉害的技术人才也要几个人合作几个月才做得出来。其实这就是变相不招人。而那些面试我的技术员们，总是一副自鸣得意自己认为自己很了不起的样子，一旦问出一个我不会的了，就死抓不放。就算技术我通过了，到了技术主管那边，一般他们不懂技术了，总要问东问西，比如问到我不懂C++，就死抓住说道我们这个项目对C++要求很高，一问到我对php不熟悉，就死抓住说，我们这个项目主要是php编程，那我问了你招python工程师干嘛呢，他说我上面写着php python一起的，但主要还是以php为主。话都是随他们说的，更加不要提了，还有几乎一般的面试，主管都不在，其实不在的意思就是不打算招人。还有的面试最后技术主管也发现抓不住什么，最后只是回了一句，好的，然后等消息吧。


企业活不下去，人自然更加活不下去了。这大概就是现在大陆正在发生的事吧。

群租房这里，都是做业务的搞推销弄贷款，经济更加恶化的话，我估计将会有更多的搞推销的搞传销的吧。

我只是希望能够稳定的继续努力学习提升自己，继续努力编程，可能如果更好进入一个不错的团队，做出一些有价值的东西。而现在看来都是一个奢望了。很显然，大陆这里，正在发生这一种历史大势，在这个历史大势面前 ，任何个人的决策和努力和改变最终化为徒劳，而只剩下一个命运 。一个注定等待他们的命运 。

而你们要告诉你们，你们终将到达那个命运点，无论你们现在想什么，说什么，做什么。到了那个时候，你们终将明白，群体的命运，国家的运命，整个社会经济政治大环境，绝不是那么无足轻重。到了那个时候，你们终将明白，骗子和戏子是根本靠不住的，到了那个时候，你们终将明白，雄心壮志，豪言壮语，标语口号，都改变不了自身的运命，都不过是一场空罢了。而真正的改变，就是明白，明白那些骗子那些戏子的谎言，把他们揪出来，让他们迎接本属于他们的命运。因为他们没有接受他们的命运，他们不下地狱，人间将长是地狱，他们不接受他们的命运，那么我们的命运都是注定的，如同风中羽翼一般随波逐流，而虚度此生的。
