#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS:[11pt,oneside]
#+LATEX_HEADER: \usepackage{article}


#+TITLE: 穷人的国和富人的国
#+AUTHOR: 万泽(德山书生)
#+CREATOR: wanze(<a href="mailto:a358003542@gmail.com">a358003542@gmail.com</a>)
#+DESCRIPTION: 制作者邮箱：a358003542@gmail.com



似乎整个人类社会的游戏规则都是一种导向战争的发展模式，而大陆尤甚。

就以找工作为例子，企业都不愿意培养人，只愿意接受有工作经验的，这样势必造成相应的人才市场供给越来越萎缩。而他们招人也是那种思维，就是你没有工作的从骨子里就看不起你，不愿意用你，希望把你排除在这个体系之外，只愿意考虑那些所谓的跳槽的。再以经济系统的交易为例，一切交易都是为了赚钱，而所谓赚钱不过是一种财富转移过程罢了，所以长此以往则必然社会贫富差距越来越大，而且最离谱的是贫富差距加大之后引起人们的心理歧视思维，比如相同能力的穷学生企业就不愿意用 ，更进一步负反馈让贫富差距加大。

等等等等，似乎整个社会的游戏规则骨子里就是这种竞争性排他性的。这也必然造成整个社会最后游戏圈子越来越窄越来越单一。最后只有两种可能性，要某是完全把那些穷人灭绝了或者发生战争。

而科技在如上所述的游戏规则中，只是扮演了一种缓冲剂的作用。如果科技突然出现局限了，那么人类的必然走向无休止的轮回战斗杀戮之中，因为整个社会的游戏规则就决定了这一切。

其中大陆尤其严重，你称之为经济危机也好，称之为历史轮回也好，人类社会的历史就是这样的。如果说大陆再一次回到与世隔绝的现状，我几乎可能肯定的是，无穷无尽的王朝更迭和周而复始的战争杀戮会一直延续下去，而现在就是因为欧美那边的科技进步影响缓冲了这一过程。

所以马克思谈论的其实不是什么新鲜的东西，说到底早在柏拉图时代人们就在谈论这个政治周期了，那就是贫富差距加大现象。而所谓的社会主义或者共产主义声明自己能够消灭这一周期，事实上他们没有，反倒是他们批判的资本主义社会的民主制度和科技进步等一定程度上缓冲了这一周期。

而且就目前来看，似乎除了欧美国家发展出来的哪一套文明社会法则之外，不走这条路的不管声明自己是什么主义或者什么的国家，最终都不过是走向历史循环的快车道罢了。

如果非得要用一个词语来描述，那么我说社会就好像一个有机体，其内部有一套游戏规则，使得其是进化的或者说向死的。而要维持这个有机体的健康，维持整个文明社会的健康运作，绝非易事。从这个角度来看，无关特色，只有健康和生病衰弱的国度区别。﻿




实际上穷人，穷到一定程度的人，就应该自然而然的结成一个柏拉图所谓的穷人的国。从而最终导向一个国家分裂为两个国家，穷人的国和富人的国。穷人的国有穷人的国的哪一套文化，富人的国有富人的国的哪一套文化，而且两者最终几乎是慢慢的脱离任何利益纠缠互相割裂开来了的。

这个所谓的穷人的国实际上就是马克思言及的无产阶级。而穷人或者说无产阶级从天性上就应该是:

所有的无产阶级团结起来。

这就是穷人的天性，从本质上那些穷得一无所有的人都应该彼此团结，不分彼此，成为一个新的国家社团。

但无产阶级中，比如我们经常看到，明明他是一个穷人，却不停的维护富人国家的利益。这就是所谓的流氓无产阶级。那么什么才是穷人，什么才是无产阶级呢？我觉得这是非常好理解的概念，而人们却屡次受到欺骗，这是匪夷所思的事情。

就以那些人大代表为例子把，他们说自己是无产阶级，恩，连财产都不敢公开的无产阶级，好无产阶级啊。

再比如说有一些穷得叮当响的城管之类，明明身无分文，丢了工作于是什么都没有了的穷人，在富人的国家里面没有任何话语权的穷人，他们却总是梦想着自己似乎是富人，似乎是富人国家有话语权的样子，岂不是如同阿Q一样的可笑。﻿

所以按照历史规律来看，最终大陆将愈来愈分裂为穷人的国和富人的国，而穷人不敢反抗那个富人的国，实际上就是奴隶。而我们需要做的就是团结那些穷人，去让他们认清自己的历史地位，去反抗，不当奴隶，至少要当一个历史主旋律下的穷人，堂堂正正，挺起胸膛的对抗富人。

我觉得我应该整理好我的言论，写成各种演讲稿，以备将来所用吧。

永远不要低估了 笔头子 的力量 。﻿
