#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS:[11pt,oneside]
#+LATEX_HEADER: \usepackage{article}



#+TITLE: 人工智能的为和不为
#+AUTHOR: 万泽(德山书生)
#+CREATOR: 编者:wanze(<a href="mailto:a358003542@163.com">a358003542@163.com</a>)
#+DESCRIPTION: 制作者邮箱：a358003542@gmail.com




* 人工智能的为与不为



完全具有独立意识的人工智能研究就好比原子弹的研究一样，可以研究但不需要实际制作出来，当然更不能实际使用他们。

完全独有独立意识的人工智能是视图僭越上帝的大智慧行为，这必定是在撒旦的诱惑下和撒旦的操纵下人类才会如此去做的。

上帝的大智慧是和谐的，智能生命，从最小的细胞到植物到动物都是统一的逐步发展的。人脑也是如此，人脑有脊椎动物的本能脑，爬行动物的情绪脑，哺乳动物的皮层脑和人类自己独立发展出来的额脑。

这些后发展出来的部分都是建构在之前部分的基础上的，他们协同并存融为一体。而人工智能未来的发展方向不应该是在撒旦的蛊惑下研究如何取代人脑的额脑本能脑情绪脑部分，而应该是如何在额脑的基础之上辅助架构，从而和人脑的其他部位和谐融为一体，从而达到人类自我提升的目的。

视图僭越上帝的造化，视图僭越大自然的几十亿年的鬼斧神工，企图自己开天辟地建造完全独立自主的人工智能，是人心受撒旦蛊惑的大僭妄行为，必须得到人类整个社群智能理性的批判。

未来我们的研究方向应该更多的放在，如何更好地和人自身额脑部位的通信，搭建一个信号发射器。然后建立信号接受服务器，从而进行一些云计算，辅助额脑的资讯和逻辑运算需求。虽然计算机作为服务器在各种程度上影响着人脑的资讯和思考，这是必然的。但人作为人之前的眼睛，触觉，听觉，额脑决策推理，皮层脑存储，包括本能情绪和自身身体其他肉体器官互动的能力都得到完全保留，未来人工智能的变得更加智慧，不是在僭越人的智慧，而是作为一个更好的参谋的存在让人的思维行动能力都变得更强（人的肉体行动能力目前就在因为机械而扩展，这并不让人们感到困惑。）。

我认为霍金的说法是完全经过理性思考和值得大家深思的，技术我们可以发明出来，就好比原子弹，但一定要制造出来和使用它吗？埃博拉病毒我们也可以制造出来，也要制造出来并使用他们吗？那我们是什么吗？是受到撒旦诱惑的走向自我毁灭的种族啊。


